<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>9.4 Log-linear models as an alternative to Chi-square test for contingency tables | BIO4158 Applied biostats with R</title>
  <meta name="description" content="Laboratory manual for BIO4158 Applied biostatistics" />
  <meta name="generator" content="bookdown 0.26 and GitBook 2.6.7" />

  <meta property="og:title" content="9.4 Log-linear models as an alternative to Chi-square test for contingency tables | BIO4158 Applied biostats with R" />
  <meta property="og:type" content="book" />
  <meta property="og:image" content="/images/missing.png" />
  <meta property="og:description" content="Laboratory manual for BIO4158 Applied biostatistics" />
  <meta name="github-repo" content="Bio4158-4558-uottawa/lab_manual/" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="9.4 Log-linear models as an alternative to Chi-square test for contingency tables | BIO4158 Applied biostats with R" />
  
  <meta name="twitter:description" content="Laboratory manual for BIO4158 Applied biostatistics" />
  <meta name="twitter:image" content="/images/missing.png" />

<meta name="author" content="Julien Martin" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="graphs-for-contingency-tables-and-testing-for-independence.html"/>
<link rel="next" href="testing-an-external-hypothesis.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>
<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="css/style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">BIO4158 Laboratory manual</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Note</a></li>
<li class="chapter" data-level="" data-path="preface.html"><a href="preface.html"><i class="fa fa-check"></i>Preface</a>
<ul>
<li class="chapter" data-level="" data-path="general-points-to-keep-in-mind.html"><a href="general-points-to-keep-in-mind.html"><i class="fa fa-check"></i>General points to keep in mind</a></li>
<li class="chapter" data-level="" data-path="what-is-r-and-why-use-it-in-this-course.html"><a href="what-is-r-and-why-use-it-in-this-course.html"><i class="fa fa-check"></i>What is R and why use it in this course?</a></li>
<li class="chapter" data-level="" data-path="software-installation.html"><a href="software-installation.html"><i class="fa fa-check"></i>Software installation</a>
<ul>
<li class="chapter" data-level="" data-path="software-installation.html"><a href="software-installation.html#r"><i class="fa fa-check"></i>R</a></li>
<li class="chapter" data-level="" data-path="software-installation.html"><a href="software-installation.html#rstudio-or-vs-code"><i class="fa fa-check"></i>Rstudio or VS code</a></li>
<li class="chapter" data-level="" data-path="software-installation.html"><a href="software-installation.html#r-libraries"><i class="fa fa-check"></i>R libraries</a></li>
<li class="chapter" data-level="" data-path="software-installation.html"><a href="software-installation.html#gpower"><i class="fa fa-check"></i>G*Power</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="general-laboratory-instructions.html"><a href="general-laboratory-instructions.html"><i class="fa fa-check"></i>General laboratory instructions</a></li>
<li class="chapter" data-level="" data-path="notes-about-the-manual.html"><a href="notes-about-the-manual.html"><i class="fa fa-check"></i>Notes about the manual</a>
<ul>
<li class="chapter" data-level="" data-path="notes-about-the-manual.html"><a href="notes-about-the-manual.html#resources"><i class="fa fa-check"></i>Resources</a></li>
<li class="chapter" data-level="" data-path="notes-about-the-manual.html"><a href="notes-about-the-manual.html#license"><i class="fa fa-check"></i>License</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="1" data-path="introduction-to-r.html"><a href="introduction-to-r.html"><i class="fa fa-check"></i><b>1</b> Introduction to R</a>
<ul>
<li class="chapter" data-level="1.1" data-path="set-intro.html"><a href="set-intro.html"><i class="fa fa-check"></i><b>1.1</b> Packages and data needed for the lab</a></li>
<li class="chapter" data-level="1.2" data-path="importing-and-exporting-data.html"><a href="importing-and-exporting-data.html"><i class="fa fa-check"></i><b>1.2</b> Importing and exporting data</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="importing-and-exporting-data.html"><a href="importing-and-exporting-data.html#working-directory"><i class="fa fa-check"></i><b>1.2.1</b> Working directory</a></li>
<li class="chapter" data-level="1.2.2" data-path="importing-and-exporting-data.html"><a href="importing-and-exporting-data.html#opening-a-.rdata-file"><i class="fa fa-check"></i><b>1.2.2</b> Opening a <code>.Rdata</code> file</a></li>
<li class="chapter" data-level="1.2.3" data-path="importing-and-exporting-data.html"><a href="importing-and-exporting-data.html#open-a-.csv-file"><i class="fa fa-check"></i><b>1.2.3</b> Open a <code>.csv</code> file</a></li>
<li class="chapter" data-level="1.2.4" data-path="importing-and-exporting-data.html"><a href="importing-and-exporting-data.html#entering-data-in-r"><i class="fa fa-check"></i><b>1.2.4</b> Entering data in R</a></li>
<li class="chapter" data-level="1.2.5" data-path="importing-and-exporting-data.html"><a href="importing-and-exporting-data.html#cleaning-up-correcting-data"><i class="fa fa-check"></i><b>1.2.5</b> Cleaning up / correcting data</a></li>
<li class="chapter" data-level="1.2.6" data-path="importing-and-exporting-data.html"><a href="importing-and-exporting-data.html#exporting-data-from-r"><i class="fa fa-check"></i><b>1.2.6</b> Exporting data from R</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="preliminary-examination-of-data.html"><a href="preliminary-examination-of-data.html"><i class="fa fa-check"></i><b>1.3</b> Preliminary examination of data</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="preliminary-examination-of-data.html"><a href="preliminary-examination-of-data.html#summary-statistics"><i class="fa fa-check"></i><b>1.3.1</b> Summary statistics</a></li>
<li class="chapter" data-level="1.3.2" data-path="preliminary-examination-of-data.html"><a href="preliminary-examination-of-data.html#histogram-empirical-probability-density-boxplot-and-visual-assessment-of-normality"><i class="fa fa-check"></i><b>1.3.2</b> Histogram, empirical probability density, boxplot, and visual assessment of normality</a></li>
<li class="chapter" data-level="1.3.3" data-path="preliminary-examination-of-data.html"><a href="preliminary-examination-of-data.html#scatterplots"><i class="fa fa-check"></i><b>1.3.3</b> Scatterplots</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="creating-data-subsets.html"><a href="creating-data-subsets.html"><i class="fa fa-check"></i><b>1.4</b> Creating data subsets</a></li>
<li class="chapter" data-level="1.5" data-path="data-transformation.html"><a href="data-transformation.html"><i class="fa fa-check"></i><b>1.5</b> Data transformation</a></li>
<li class="chapter" data-level="1.6" data-path="exercice.html"><a href="exercice.html"><i class="fa fa-check"></i><b>1.6</b> Exercice</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="power-analysis-with-r-and-gpower.html"><a href="power-analysis-with-r-and-gpower.html"><i class="fa fa-check"></i><b>2</b> Power Analysis with R and G*Power</a>
<ul>
<li class="chapter" data-level="2.1" data-path="the-theory.html"><a href="the-theory.html"><i class="fa fa-check"></i><b>2.1</b> The theory</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="the-theory.html"><a href="the-theory.html#what-is-power"><i class="fa fa-check"></i><b>2.1.1</b> What is power?</a></li>
<li class="chapter" data-level="2.1.2" data-path="the-theory.html"><a href="the-theory.html#why-do-a-power-analysis"><i class="fa fa-check"></i><b>2.1.2</b> Why do a power analysis?</a></li>
<li class="chapter" data-level="2.1.3" data-path="the-theory.html"><a href="the-theory.html#factors-affecting-power"><i class="fa fa-check"></i><b>2.1.3</b> Factors affecting power</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="what-is-gpower.html"><a href="what-is-gpower.html"><i class="fa fa-check"></i><b>2.2</b> What is G*Power?</a></li>
<li class="chapter" data-level="2.3" data-path="how-to-use-gpower.html"><a href="how-to-use-gpower.html"><i class="fa fa-check"></i><b>2.3</b> How to use G*Power</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="how-to-use-gpower.html"><a href="how-to-use-gpower.html#general-principle"><i class="fa fa-check"></i><b>2.3.1</b> General Principle</a></li>
<li class="chapter" data-level="2.3.2" data-path="how-to-use-gpower.html"><a href="how-to-use-gpower.html#types-of-power-analyses"><i class="fa fa-check"></i><b>2.3.2</b> Types of power analyses</a></li>
<li class="chapter" data-level="2.3.3" data-path="how-to-use-gpower.html"><a href="how-to-use-gpower.html#how-to-calculate-effect-size"><i class="fa fa-check"></i><b>2.3.3</b> How to calculate effect size</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="power-analysis-for-a-t-test-on-two-independent-means.html"><a href="power-analysis-for-a-t-test-on-two-independent-means.html"><i class="fa fa-check"></i><b>2.4</b> Power analysis for a t-test on two independent means</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="power-analysis-for-a-t-test-on-two-independent-means.html"><a href="power-analysis-for-a-t-test-on-two-independent-means.html#post-hoc-analysis"><i class="fa fa-check"></i><b>2.4.1</b> Post-hoc analysis</a></li>
<li class="chapter" data-level="2.4.2" data-path="power-analysis-for-a-t-test-on-two-independent-means.html"><a href="power-analysis-for-a-t-test-on-two-independent-means.html#a-priori-analysis"><i class="fa fa-check"></i><b>2.4.2</b> A priori analysis</a></li>
<li class="chapter" data-level="2.4.3" data-path="power-analysis-for-a-t-test-on-two-independent-means.html"><a href="power-analysis-for-a-t-test-on-two-independent-means.html#sensitivity-analysis---calculate-the-detectable-effect-size"><i class="fa fa-check"></i><b>2.4.3</b> Sensitivity analysis - Calculate the detectable effect size</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="important-points-to-remember.html"><a href="important-points-to-remember.html"><i class="fa fa-check"></i><b>2.5</b> Important points to remember</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="correlation-and-simple-linear-regression.html"><a href="correlation-and-simple-linear-regression.html"><i class="fa fa-check"></i><b>3</b> Correlation and simple linear regression</a>
<ul>
<li class="chapter" data-level="3.1" data-path="set-lm.html"><a href="set-lm.html"><i class="fa fa-check"></i><b>3.1</b> R packages and data</a></li>
<li class="chapter" data-level="3.2" data-path="scatter-plots.html"><a href="scatter-plots.html"><i class="fa fa-check"></i><b>3.2</b> Scatter plots</a></li>
<li class="chapter" data-level="3.3" data-path="data-transformations-and-the-product-moment-correlation.html"><a href="data-transformations-and-the-product-moment-correlation.html"><i class="fa fa-check"></i><b>3.3</b> Data transformations and the product-moment correlation</a></li>
<li class="chapter" data-level="3.4" data-path="testing-the-significance-of-correlations-and-bonferroni-probabilities.html"><a href="testing-the-significance-of-correlations-and-bonferroni-probabilities.html"><i class="fa fa-check"></i><b>3.4</b> Testing the significance of correlations and Bonferroni probabilities</a></li>
<li class="chapter" data-level="3.5" data-path="non-parametric-correlations-spearmans-rank-and-kendalls-tau.html"><a href="non-parametric-correlations-spearmans-rank-and-kendalls-tau.html"><i class="fa fa-check"></i><b>3.5</b> Non-parametric correlations: Spearman’s rank and Kendall’s <span class="math inline">\(\tau\)</span></a></li>
<li class="chapter" data-level="3.6" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html"><i class="fa fa-check"></i><b>3.6</b> Simple linear regression</a>
<ul>
<li class="chapter" data-level="3.6.1" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#testing-regression-assumptions"><i class="fa fa-check"></i><b>3.6.1</b> Testing regression assumptions</a></li>
<li class="chapter" data-level="3.6.2" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#formal-tests-of-regression-assumptions"><i class="fa fa-check"></i><b>3.6.2</b> Formal tests of regression assumptions</a></li>
</ul></li>
<li class="chapter" data-level="3.7" data-path="data-transformations-in-regression.html"><a href="data-transformations-in-regression.html"><i class="fa fa-check"></i><b>3.7</b> Data transformations in regression</a></li>
<li class="chapter" data-level="3.8" data-path="dealing-with-outliers.html"><a href="dealing-with-outliers.html"><i class="fa fa-check"></i><b>3.8</b> Dealing with outliers</a></li>
<li class="chapter" data-level="3.9" data-path="quantifying-effect-size-in-regression-and-power-analysis.html"><a href="quantifying-effect-size-in-regression-and-power-analysis.html"><i class="fa fa-check"></i><b>3.9</b> Quantifying effect size in regression and power analysis</a>
<ul>
<li class="chapter" data-level="3.9.1" data-path="quantifying-effect-size-in-regression-and-power-analysis.html"><a href="quantifying-effect-size-in-regression-and-power-analysis.html#power-to-detect-a-given-slope"><i class="fa fa-check"></i><b>3.9.1</b> Power to detect a given slope</a></li>
<li class="chapter" data-level="3.9.2" data-path="quantifying-effect-size-in-regression-and-power-analysis.html"><a href="quantifying-effect-size-in-regression-and-power-analysis.html#sample-size-required-to-achieve-desired-power"><i class="fa fa-check"></i><b>3.9.2</b> Sample size required to achieve desired power</a></li>
</ul></li>
<li class="chapter" data-level="3.10" data-path="bootstrapping-the-simple-linear-regression.html"><a href="bootstrapping-the-simple-linear-regression.html"><i class="fa fa-check"></i><b>3.10</b> Bootstrapping the simple linear regression</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="two---sample-comparisons.html"><a href="two---sample-comparisons.html"><i class="fa fa-check"></i><b>4</b> Two - sample comparisons</a>
<ul>
<li class="chapter" data-level="4.1" data-path="set-ttest.html"><a href="set-ttest.html"><i class="fa fa-check"></i><b>4.1</b> R packages and data</a></li>
<li class="chapter" data-level="4.2" data-path="visual-examination-of-sample-data.html"><a href="visual-examination-of-sample-data.html"><i class="fa fa-check"></i><b>4.2</b> Visual examination of sample data</a></li>
<li class="chapter" data-level="4.3" data-path="comparing-means-of-two-independent-samples-parametric-and-non-parametric-comparisons.html"><a href="comparing-means-of-two-independent-samples-parametric-and-non-parametric-comparisons.html"><i class="fa fa-check"></i><b>4.3</b> Comparing means of two independent samples: parametric and non-parametric comparisons</a></li>
<li class="chapter" data-level="4.4" data-path="bootstrap-and-permutation-tests-to-compare-2-means.html"><a href="bootstrap-and-permutation-tests-to-compare-2-means.html"><i class="fa fa-check"></i><b>4.4</b> Bootstrap and permutation tests to compare 2 means</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="bootstrap-and-permutation-tests-to-compare-2-means.html"><a href="bootstrap-and-permutation-tests-to-compare-2-means.html#bootstrap"><i class="fa fa-check"></i><b>4.4.1</b> Bootstrap</a></li>
<li class="chapter" data-level="4.4.2" data-path="bootstrap-and-permutation-tests-to-compare-2-means.html"><a href="bootstrap-and-permutation-tests-to-compare-2-means.html#permutation"><i class="fa fa-check"></i><b>4.4.2</b> Permutation</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="comparing-the-means-of-paired-samples.html"><a href="comparing-the-means-of-paired-samples.html"><i class="fa fa-check"></i><b>4.5</b> Comparing the means of paired samples</a></li>
<li class="chapter" data-level="4.6" data-path="bibliography.html"><a href="bibliography.html"><i class="fa fa-check"></i><b>4.6</b> Bibliography</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="one-way-anova.html"><a href="one-way-anova.html"><i class="fa fa-check"></i><b>5</b> One-way ANOVA</a>
<ul>
<li class="chapter" data-level="5.1" data-path="set-ano.html"><a href="set-ano.html"><i class="fa fa-check"></i><b>5.1</b> R packages and data</a></li>
<li class="chapter" data-level="5.2" data-path="one-way-anova-with-multiple-comparisons.html"><a href="one-way-anova-with-multiple-comparisons.html"><i class="fa fa-check"></i><b>5.2</b> One-way ANOVA with multiple comparisons</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="one-way-anova-with-multiple-comparisons.html"><a href="one-way-anova-with-multiple-comparisons.html#visualiser-les-données"><i class="fa fa-check"></i><b>5.2.1</b> Visualiser les données</a></li>
<li class="chapter" data-level="5.2.2" data-path="one-way-anova-with-multiple-comparisons.html"><a href="one-way-anova-with-multiple-comparisons.html#testing-the-assumptions-of-a-parametric-anova"><i class="fa fa-check"></i><b>5.2.2</b> Testing the assumptions of a parametric ANOVA</a></li>
<li class="chapter" data-level="5.2.3" data-path="one-way-anova-with-multiple-comparisons.html"><a href="one-way-anova-with-multiple-comparisons.html#performing-the-anova"><i class="fa fa-check"></i><b>5.2.3</b> Performing the ANOVA</a></li>
<li class="chapter" data-level="5.2.4" data-path="one-way-anova-with-multiple-comparisons.html"><a href="one-way-anova-with-multiple-comparisons.html#performing-multiple-comparisons-of-means-test"><i class="fa fa-check"></i><b>5.2.4</b> Performing multiple comparisons of means test</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="data-transformations-and-non-parametric-anova.html"><a href="data-transformations-and-non-parametric-anova.html"><i class="fa fa-check"></i><b>5.3</b> Data transformations and non-parametric ANOVA</a></li>
<li class="chapter" data-level="5.4" data-path="dealing-with-outliers-1.html"><a href="dealing-with-outliers-1.html"><i class="fa fa-check"></i><b>5.4</b> Dealing with outliers</a></li>
<li class="chapter" data-level="5.5" data-path="permutation-test.html"><a href="permutation-test.html"><i class="fa fa-check"></i><b>5.5</b> Permutation test</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="multiway-anova-factorial-and-nested-designs.html"><a href="multiway-anova-factorial-and-nested-designs.html"><i class="fa fa-check"></i><b>6</b> Multiway ANOVA: factorial and nested designs</a>
<ul>
<li class="chapter" data-level="6.1" data-path="set-anomul.html"><a href="set-anomul.html"><i class="fa fa-check"></i><b>6.1</b> R packages and data needed</a></li>
<li class="chapter" data-level="6.2" data-path="two-way-factorial-design-with-replication.html"><a href="two-way-factorial-design-with-replication.html"><i class="fa fa-check"></i><b>6.2</b> Two-way factorial design with replication</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="two-way-factorial-design-with-replication.html"><a href="two-way-factorial-design-with-replication.html#fixed-effects-anova-model-i"><i class="fa fa-check"></i><b>6.2.1</b> Fixed effects ANOVA (Model I)</a></li>
<li class="chapter" data-level="6.2.2" data-path="two-way-factorial-design-with-replication.html"><a href="two-way-factorial-design-with-replication.html#mixed-effects-anova-model-iii"><i class="fa fa-check"></i><b>6.2.2</b> Mixed effects ANOVA (Model III)</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="way-factorial-anova-without-replication.html"><a href="way-factorial-anova-without-replication.html"><i class="fa fa-check"></i><b>6.3</b> 2-way factorial ANOVA without replication</a></li>
<li class="chapter" data-level="6.4" data-path="nested-designs.html"><a href="nested-designs.html"><i class="fa fa-check"></i><b>6.4</b> Nested designs</a></li>
<li class="chapter" data-level="6.5" data-path="two-way-non-parametric-anova.html"><a href="two-way-non-parametric-anova.html"><i class="fa fa-check"></i><b>6.5</b> Two-way non-parametric ANOVA</a></li>
<li class="chapter" data-level="6.6" data-path="multiple-comparisons.html"><a href="multiple-comparisons.html"><i class="fa fa-check"></i><b>6.6</b> Multiple comparisons</a></li>
<li class="chapter" data-level="6.7" data-path="test-de-permutation-pour-lanova-à-deux-facteurs-de-classification.html"><a href="test-de-permutation-pour-lanova-à-deux-facteurs-de-classification.html"><i class="fa fa-check"></i><b>6.7</b> Test de permutation pour l’ANOVA à deux facteurs de classification</a></li>
<li class="chapter" data-level="6.8" data-path="bootstrap-for-two-way-anova.html"><a href="bootstrap-for-two-way-anova.html"><i class="fa fa-check"></i><b>6.8</b> Bootstrap for two-way ANOVA</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="multiple-regression.html"><a href="multiple-regression.html"><i class="fa fa-check"></i><b>7</b> Multiple regression</a>
<ul>
<li class="chapter" data-level="7.1" data-path="set-reg-mul.html"><a href="set-reg-mul.html"><i class="fa fa-check"></i><b>7.1</b> R packages and data</a></li>
<li class="chapter" data-level="7.2" data-path="points-to-keep-in-mind.html"><a href="points-to-keep-in-mind.html"><i class="fa fa-check"></i><b>7.2</b> Points to keep in mind</a></li>
<li class="chapter" data-level="7.3" data-path="first-look-at-the-data.html"><a href="first-look-at-the-data.html"><i class="fa fa-check"></i><b>7.3</b> First look at the data</a></li>
<li class="chapter" data-level="7.4" data-path="multiple-regression-models-from-scratch.html"><a href="multiple-regression-models-from-scratch.html"><i class="fa fa-check"></i><b>7.4</b> Multiple regression models from scratch</a></li>
<li class="chapter" data-level="7.5" data-path="stepwise-multiple-regression-procedures.html"><a href="stepwise-multiple-regression-procedures.html"><i class="fa fa-check"></i><b>7.5</b> Stepwise multiple regression procedures</a></li>
<li class="chapter" data-level="7.6" data-path="detecting-multicollinearity.html"><a href="detecting-multicollinearity.html"><i class="fa fa-check"></i><b>7.6</b> Detecting multicollinearity</a></li>
<li class="chapter" data-level="7.7" data-path="polynomial-regression.html"><a href="polynomial-regression.html"><i class="fa fa-check"></i><b>7.7</b> Polynomial regression</a></li>
<li class="chapter" data-level="7.8" data-path="checking-assumptions-of-a-multiple-regression-model.html"><a href="checking-assumptions-of-a-multiple-regression-model.html"><i class="fa fa-check"></i><b>7.8</b> Checking assumptions of a multiple regression model</a></li>
<li class="chapter" data-level="7.9" data-path="visualizing-effect-size.html"><a href="visualizing-effect-size.html"><i class="fa fa-check"></i><b>7.9</b> Visualizing effect size</a></li>
<li class="chapter" data-level="7.10" data-path="testing-for-interactions.html"><a href="testing-for-interactions.html"><i class="fa fa-check"></i><b>7.10</b> Testing for interactions</a></li>
<li class="chapter" data-level="7.11" data-path="dredging-and-the-information-theoretical-approach.html"><a href="dredging-and-the-information-theoretical-approach.html"><i class="fa fa-check"></i><b>7.11</b> Dredging and the information theoretical approach</a></li>
<li class="chapter" data-level="7.12" data-path="bootstrapping-multiple-regression.html"><a href="bootstrapping-multiple-regression.html"><i class="fa fa-check"></i><b>7.12</b> Bootstrapping multiple regression</a></li>
<li class="chapter" data-level="7.13" data-path="permutation-test-1.html"><a href="permutation-test-1.html"><i class="fa fa-check"></i><b>7.13</b> Permutation test</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="ancova-and-general-linear-model.html"><a href="ancova-and-general-linear-model.html"><i class="fa fa-check"></i><b>8</b> ANCOVA and general linear model</a>
<ul>
<li class="chapter" data-level="8.1" data-path="set-anco.html"><a href="set-anco.html"><i class="fa fa-check"></i><b>8.1</b> R packages and data</a></li>
<li class="chapter" data-level="8.2" data-path="linear-models.html"><a href="linear-models.html"><i class="fa fa-check"></i><b>8.2</b> Linear models</a></li>
<li class="chapter" data-level="8.3" data-path="ancova.html"><a href="ancova.html"><i class="fa fa-check"></i><b>8.3</b> ANCOVA</a></li>
<li class="chapter" data-level="8.4" data-path="homogeneity-of-slopes.html"><a href="homogeneity-of-slopes.html"><i class="fa fa-check"></i><b>8.4</b> Homogeneity of slopes</a>
<ul>
<li class="chapter" data-level="8.4.1" data-path="homogeneity-of-slopes.html"><a href="homogeneity-of-slopes.html#case-1---size-as-a-function-of-age-equal-slopes-example"><i class="fa fa-check"></i><b>8.4.1</b> Case 1 - Size as a function of age (equal slopes example)</a></li>
<li class="chapter" data-level="8.4.2" data-path="homogeneity-of-slopes.html"><a href="homogeneity-of-slopes.html#case-2---size-as-a-function-of-age-different-slopes-example"><i class="fa fa-check"></i><b>8.4.2</b> Case 2 - Size as a function of age (different slopes example)</a></li>
</ul></li>
<li class="chapter" data-level="8.5" data-path="the-ancova-model.html"><a href="the-ancova-model.html"><i class="fa fa-check"></i><b>8.5</b> The ANCOVA model</a></li>
<li class="chapter" data-level="8.6" data-path="comparing-model-fits.html"><a href="comparing-model-fits.html"><i class="fa fa-check"></i><b>8.6</b> Comparing model fits</a></li>
<li class="chapter" data-level="8.7" data-path="bootstrap-1.html"><a href="bootstrap-1.html"><i class="fa fa-check"></i><b>8.7</b> Bootstrap</a></li>
<li class="chapter" data-level="8.8" data-path="permutation-test-2.html"><a href="permutation-test-2.html"><i class="fa fa-check"></i><b>8.8</b> Permutation test</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="analysis-of-frequency-data-contingency-tables-log-linear-models-and-poisson-regression.html"><a href="analysis-of-frequency-data-contingency-tables-log-linear-models-and-poisson-regression.html"><i class="fa fa-check"></i><b>9</b> Analysis of frequency data: Contingency Tables, Log-Linear Models, and Poisson Regression</a>
<ul>
<li class="chapter" data-level="9.1" data-path="set-freq.html"><a href="set-freq.html"><i class="fa fa-check"></i><b>9.1</b> R packages and data</a></li>
<li class="chapter" data-level="9.2" data-path="organizing-the-data-3-forms.html"><a href="organizing-the-data-3-forms.html"><i class="fa fa-check"></i><b>9.2</b> Organizing the data: 3 forms</a></li>
<li class="chapter" data-level="9.3" data-path="graphs-for-contingency-tables-and-testing-for-independence.html"><a href="graphs-for-contingency-tables-and-testing-for-independence.html"><i class="fa fa-check"></i><b>9.3</b> Graphs for contingency tables and testing for independence</a></li>
<li class="chapter" data-level="9.4" data-path="log-linear-models-as-an-alternative-to-chi-square-test-for-contingency-tables.html"><a href="log-linear-models-as-an-alternative-to-chi-square-test-for-contingency-tables.html"><i class="fa fa-check"></i><b>9.4</b> Log-linear models as an alternative to Chi-square test for contingency tables</a></li>
<li class="chapter" data-level="9.5" data-path="testing-an-external-hypothesis.html"><a href="testing-an-external-hypothesis.html"><i class="fa fa-check"></i><b>9.5</b> Testing an external hypothesis</a></li>
<li class="chapter" data-level="9.6" data-path="poisson-regression-to-analyze-multi-way-tables.html"><a href="poisson-regression-to-analyze-multi-way-tables.html"><i class="fa fa-check"></i><b>9.6</b> Poisson regression to analyze multi-way tables</a></li>
<li class="chapter" data-level="9.7" data-path="ex-glm.html"><a href="ex-glm.html"><i class="fa fa-check"></i><b>9.7</b> Exercice</a></li>
</ul></li>
<li class="appendix"><span><b>Appendix</b></span></li>
<li class="chapter" data-level="A" data-path="software-tools.html"><a href="software-tools.html"><i class="fa fa-check"></i><b>A</b> Software Tools</a>
<ul>
<li class="chapter" data-level="A.1" data-path="r-and-r-packages.html"><a href="r-and-r-packages.html"><i class="fa fa-check"></i><b>A.1</b> R and R packages</a></li>
<li class="chapter" data-level="A.2" data-path="pandoc.html"><a href="pandoc.html"><i class="fa fa-check"></i><b>A.2</b> Pandoc</a></li>
<li class="chapter" data-level="A.3" data-path="latex.html"><a href="latex.html"><i class="fa fa-check"></i><b>A.3</b> LaTeX</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://bookdown.org" target="_blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">BIO4158 Applied biostats with R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="log-linear-models-as-an-alternative-to-chi-square-test-for-contingency-tables" class="section level2 hasAnchor" number="9.4">
<h2><span class="header-section-number">9.4</span> Log-linear models as an alternative to Chi-square test for contingency tables<a href="log-linear-models-as-an-alternative-to-chi-square-test-for-contingency-tables.html#log-linear-models-as-an-alternative-to-chi-square-test-for-contingency-tables" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>By now, hopefully, you have learned to appreciate the flexibility and generality of general linear models and you realize that the t-test is a special, simple, case of a linear model with one categorical independent variable. The analysis of contingency tables by chi square test can similarly be generalized. Indeed, generalized linear models for poisson distributed data can be used when the dependent variable are frequencies (count data) and the independent variables can be categorical only (like for contingency tables, these are also called log- linear models), continuous only (Poisson regression), or a combination of categorical and continuous independent variables (this, too is a Poisson regression, but with added categorical variables, analogous to an ANCOVA sensu largo).</p>
<p>Such models predict the natural log frequency of observations given the independent variables. Like for linear models assuming normality of residuals, one can assess the overall quality of the fit (by AIC for example), and the significance of terms (say by comparing the fit of models including or excluding particular terms). One can even, if desired, obtain estimates of the parameters for each model term, with confidence intervals and p-values for the null hypothesis that the value of the parameter is 0.</p>
<p>The <code>glm()</code> function with the option <code>family=poisson()</code> allows the estimation, by maximum likelihood, of linear models for count data. One “peculiarity” of fitting such models to contingency table data is that generally the only terms of interest are the interactions. Going back to the population survey data in frequency form, with sex and ageclass as independent variables, one can fit a glm model by:</p>
<div class="sourceCode" id="cb442"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb442-1"><a href="log-linear-models-as-an-alternative-to-chi-square-test-for-contingency-tables.html#cb442-1" aria-hidden="true"></a>mymodel &lt;-<span class="st"> </span><span class="kw">glm</span>(frequency <span class="op">~</span><span class="st"> </span>sex <span class="op">*</span><span class="st"> </span>ageclass, <span class="dt">family =</span> <span class="kw">poisson</span>(), <span class="dt">data =</span> USPopSurvey)</span>
<span id="cb442-2"><a href="log-linear-models-as-an-alternative-to-chi-square-test-for-contingency-tables.html#cb442-2" aria-hidden="true"></a><span class="kw">summary</span>(mymodel)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = frequency ~ sex * ageclass, family = poisson(), 
##     data = USPopSurvey)
## 
## Deviance Residuals: 
##  [1]  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
## 
## Coefficients:
##                        Estimate Std. Error  z value Pr(&gt;|z|)    
## (Intercept)            9.776733   0.007534 1297.730  &lt; 2e-16 ***
## sexmale               -0.004608   0.010667   -0.432   0.6657    
## ageclass10-19          0.018445   0.010605    1.739   0.0820 .  
## ageclass20-29          0.191793   0.010179   18.842  &lt; 2e-16 ***
## ageclass30-39          0.082698   0.010441    7.921 2.36e-15 ***
## ageclass40-49         -0.293697   0.011528  -25.477  &lt; 2e-16 ***
## ageclass50-59         -0.416508   0.011951  -34.850  &lt; 2e-16 ***
## ageclass60-69         -0.466276   0.012134  -38.428  &lt; 2e-16 ***
## ageclass70-79         -0.826200   0.013654  -60.511  &lt; 2e-16 ***
## ageclass80+           -1.454582   0.017316  -84.004  &lt; 2e-16 ***
## sexmale:ageclass10-19  0.018991   0.014981    1.268   0.2049    
## sexmale:ageclass20-29  0.007275   0.014400    0.505   0.6134    
## sexmale:ageclass30-39 -0.011245   0.014803   -0.760   0.4475    
## sexmale:ageclass40-49 -0.039519   0.016416   -2.407   0.0161 *  
## sexmale:ageclass50-59 -0.081269   0.017136   -4.742 2.11e-06 ***
## sexmale:ageclass60-69 -0.160154   0.017633   -9.083  &lt; 2e-16 ***
## sexmale:ageclass70-79 -0.361447   0.020747  -17.422  &lt; 2e-16 ***
## sexmale:ageclass80+   -0.754343   0.029598  -25.486  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for poisson family taken to be 1)
## 
##     Null deviance: 5.3611e+04  on 17  degrees of freedom
## Residual deviance: 6.5463e-12  on  0  degrees of freedom
## AIC: 237.31
## 
## Number of Fisher Scoring iterations: 2</code></pre>
<p>Fitting the full model, with the sex:ageclass interaction, allows the proportion of males and females to vary among ageclass levels, and hence to estimate exactly the frequencies for each combination of sex and ageclass (note that the deviance residuals are all 0’s and that the Residual deviance is also approximately zero).</p>
<p>A masochist can use the coefficient table to obtain the predicted values for sex and ageclass categories by summing the appropriate coefficients. The predicted values, like for multiway ANOVA model, are obtained by combining the coefficients. Remembering that the first level of a factor (alphabetically) is used as a reference, here the coefficient for the intercept (9.776733) is the predicted value for the natural log of the number of observations for females in the first alphabetical ageclass (0 to 9). Indeed e<sup>9.776733</sup> is approximately equal to 17619, the observed number of females in that age class. For example, for males in the 80+ ageclass, calculate the antilog of the coefficient for the intercept (for female in the youngest age class) plus the coefficient for sexmale (equal to the difference between ln frequency of females and males overall), plus the coefficient for the ageclass 80+ corresponding in the difference in frequency on average between the oldest and reference ageclass, plus the coefficient for the interaction terms sexmale:ageclass80+ (corresponding to the difference in the proportion of male for this ageclass compared to the youngest ageclass), so <span class="math inline">\(ln(frequency)=9.776733-0.004608-1.454582- 0.754343 = 7.5632\)</span>, and the frequency is equal to e<sup>7.5632</sup> = 1926</p>
<p>Although there are numerous p values in this output, they are not really helpful. To test whether the effect of sex on observed frequency is the same across ageclass levels, i.e is sex and age are independent, one needs to fit a model where the interaction sex:ageclass is removed, and see how badly this affects the fit. The <code>Anova()</code> function of the <code>car</code> package provides a handy shortcut:</p>
<div class="sourceCode" id="cb444"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb444-1"><a href="log-linear-models-as-an-alternative-to-chi-square-test-for-contingency-tables.html#cb444-1" aria-hidden="true"></a><span class="kw">Anova</span>(mymodel, <span class="dt">type =</span> <span class="dv">3</span>, <span class="dt">test =</span> <span class="st">&quot;LR&quot;</span>)</span></code></pre></div>
<pre><code>## Analysis of Deviance Table (Type III tests)
## 
## Response: frequency
##              LR Chisq Df Pr(&gt;Chisq)    
## sex               0.2  1     0.6657    
## ageclass      21074.6  8     &lt;2e-16 ***
## sex:ageclass   1182.2  8     &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>The use of type=3 and test=“LR” ensures that the test performed to compare the full and reduced models is the Likelihood Ratio Chi- Square using the Residual deviance, and that it is a partial test, not a sequential one.</p>
<p>According to these tests, there is no main effect of sex (p=0.667) but there is a main effect of ageclass and a significant sex:ageclass interaction. The significant interaction means that the effect of sex on frequency varies with ageclass, or that the sex ratio varies with age. The main effect of ageclass means that the frequency of individuals varies with age (i.e some ageclass are more populous than others), The absence of a main effect of sex suggests that there are approximately the same frequency of males and females in this sample (although, since there is an interaction, you have to be careful in making this assertion. It is “true” overall, but appears incorrect for individual age categories).</p>
</div>
<script src="js/solution.js"></script>
            </section>

          </div>
        </div>
      </div>
<a href="graphs-for-contingency-tables-and-testing-for-independence.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="testing-an-external-hypothesis.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": false,
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/Bio4158-4558-uottawa/lab_manual/edit/main/09-model_freq.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["Labs_BIO4158.pdf", "Labs_BIO4158.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
