<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>7.4 Multiple regression models from scratch | BIO4158 Applied biostats with R</title>
  <meta name="description" content="Laboratory manual for BIO4158 Applied biostatistics" />
  <meta name="generator" content="bookdown 0.26 and GitBook 2.6.7" />

  <meta property="og:title" content="7.4 Multiple regression models from scratch | BIO4158 Applied biostats with R" />
  <meta property="og:type" content="book" />
  <meta property="og:image" content="/images/missing.png" />
  <meta property="og:description" content="Laboratory manual for BIO4158 Applied biostatistics" />
  <meta name="github-repo" content="Bio4158-4558-uottawa/lab_manual/" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="7.4 Multiple regression models from scratch | BIO4158 Applied biostats with R" />
  
  <meta name="twitter:description" content="Laboratory manual for BIO4158 Applied biostatistics" />
  <meta name="twitter:image" content="/images/missing.png" />

<meta name="author" content="Julien Martin" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="first-look-at-the-data.html"/>
<link rel="next" href="stepwise-multiple-regression-procedures.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>
<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="css/style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">BIO4158 Laboratory manual</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Note</a></li>
<li class="chapter" data-level="" data-path="preface.html"><a href="preface.html"><i class="fa fa-check"></i>Preface</a>
<ul>
<li class="chapter" data-level="" data-path="general-points-to-keep-in-mind.html"><a href="general-points-to-keep-in-mind.html"><i class="fa fa-check"></i>General points to keep in mind</a></li>
<li class="chapter" data-level="" data-path="what-is-r-and-why-use-it-in-this-course.html"><a href="what-is-r-and-why-use-it-in-this-course.html"><i class="fa fa-check"></i>What is R and why use it in this course?</a></li>
<li class="chapter" data-level="" data-path="software-installation.html"><a href="software-installation.html"><i class="fa fa-check"></i>Software installation</a>
<ul>
<li class="chapter" data-level="" data-path="software-installation.html"><a href="software-installation.html#r"><i class="fa fa-check"></i>R</a></li>
<li class="chapter" data-level="" data-path="software-installation.html"><a href="software-installation.html#rstudio-or-vs-code"><i class="fa fa-check"></i>Rstudio or VS code</a></li>
<li class="chapter" data-level="" data-path="software-installation.html"><a href="software-installation.html#r-libraries"><i class="fa fa-check"></i>R libraries</a></li>
<li class="chapter" data-level="" data-path="software-installation.html"><a href="software-installation.html#gpower"><i class="fa fa-check"></i>G*Power</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="general-laboratory-instructions.html"><a href="general-laboratory-instructions.html"><i class="fa fa-check"></i>General laboratory instructions</a></li>
<li class="chapter" data-level="" data-path="notes-about-the-manual.html"><a href="notes-about-the-manual.html"><i class="fa fa-check"></i>Notes about the manual</a>
<ul>
<li class="chapter" data-level="" data-path="notes-about-the-manual.html"><a href="notes-about-the-manual.html#resources"><i class="fa fa-check"></i>Resources</a></li>
<li class="chapter" data-level="" data-path="notes-about-the-manual.html"><a href="notes-about-the-manual.html#license"><i class="fa fa-check"></i>License</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="1" data-path="introduction-to-r.html"><a href="introduction-to-r.html"><i class="fa fa-check"></i><b>1</b> Introduction to R</a>
<ul>
<li class="chapter" data-level="1.1" data-path="set-intro.html"><a href="set-intro.html"><i class="fa fa-check"></i><b>1.1</b> Packages and data needed for the lab</a></li>
<li class="chapter" data-level="1.2" data-path="importing-and-exporting-data.html"><a href="importing-and-exporting-data.html"><i class="fa fa-check"></i><b>1.2</b> Importing and exporting data</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="importing-and-exporting-data.html"><a href="importing-and-exporting-data.html#working-directory"><i class="fa fa-check"></i><b>1.2.1</b> Working directory</a></li>
<li class="chapter" data-level="1.2.2" data-path="importing-and-exporting-data.html"><a href="importing-and-exporting-data.html#opening-a-.rdata-file"><i class="fa fa-check"></i><b>1.2.2</b> Opening a <code>.Rdata</code> file</a></li>
<li class="chapter" data-level="1.2.3" data-path="importing-and-exporting-data.html"><a href="importing-and-exporting-data.html#open-a-.csv-file"><i class="fa fa-check"></i><b>1.2.3</b> Open a <code>.csv</code> file</a></li>
<li class="chapter" data-level="1.2.4" data-path="importing-and-exporting-data.html"><a href="importing-and-exporting-data.html#entering-data-in-r"><i class="fa fa-check"></i><b>1.2.4</b> Entering data in R</a></li>
<li class="chapter" data-level="1.2.5" data-path="importing-and-exporting-data.html"><a href="importing-and-exporting-data.html#cleaning-up-correcting-data"><i class="fa fa-check"></i><b>1.2.5</b> Cleaning up / correcting data</a></li>
<li class="chapter" data-level="1.2.6" data-path="importing-and-exporting-data.html"><a href="importing-and-exporting-data.html#exporting-data-from-r"><i class="fa fa-check"></i><b>1.2.6</b> Exporting data from R</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="preliminary-examination-of-data.html"><a href="preliminary-examination-of-data.html"><i class="fa fa-check"></i><b>1.3</b> Preliminary examination of data</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="preliminary-examination-of-data.html"><a href="preliminary-examination-of-data.html#summary-statistics"><i class="fa fa-check"></i><b>1.3.1</b> Summary statistics</a></li>
<li class="chapter" data-level="1.3.2" data-path="preliminary-examination-of-data.html"><a href="preliminary-examination-of-data.html#histogram-empirical-probability-density-boxplot-and-visual-assessment-of-normality"><i class="fa fa-check"></i><b>1.3.2</b> Histogram, empirical probability density, boxplot, and visual assessment of normality</a></li>
<li class="chapter" data-level="1.3.3" data-path="preliminary-examination-of-data.html"><a href="preliminary-examination-of-data.html#scatterplots"><i class="fa fa-check"></i><b>1.3.3</b> Scatterplots</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="creating-data-subsets.html"><a href="creating-data-subsets.html"><i class="fa fa-check"></i><b>1.4</b> Creating data subsets</a></li>
<li class="chapter" data-level="1.5" data-path="data-transformation.html"><a href="data-transformation.html"><i class="fa fa-check"></i><b>1.5</b> Data transformation</a></li>
<li class="chapter" data-level="1.6" data-path="exercice.html"><a href="exercice.html"><i class="fa fa-check"></i><b>1.6</b> Exercice</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="power-analysis-with-r-and-gpower.html"><a href="power-analysis-with-r-and-gpower.html"><i class="fa fa-check"></i><b>2</b> Power Analysis with R and G*Power</a>
<ul>
<li class="chapter" data-level="2.1" data-path="the-theory.html"><a href="the-theory.html"><i class="fa fa-check"></i><b>2.1</b> The theory</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="the-theory.html"><a href="the-theory.html#what-is-power"><i class="fa fa-check"></i><b>2.1.1</b> What is power?</a></li>
<li class="chapter" data-level="2.1.2" data-path="the-theory.html"><a href="the-theory.html#why-do-a-power-analysis"><i class="fa fa-check"></i><b>2.1.2</b> Why do a power analysis?</a></li>
<li class="chapter" data-level="2.1.3" data-path="the-theory.html"><a href="the-theory.html#factors-affecting-power"><i class="fa fa-check"></i><b>2.1.3</b> Factors affecting power</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="what-is-gpower.html"><a href="what-is-gpower.html"><i class="fa fa-check"></i><b>2.2</b> What is G*Power?</a></li>
<li class="chapter" data-level="2.3" data-path="how-to-use-gpower.html"><a href="how-to-use-gpower.html"><i class="fa fa-check"></i><b>2.3</b> How to use G*Power</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="how-to-use-gpower.html"><a href="how-to-use-gpower.html#general-principle"><i class="fa fa-check"></i><b>2.3.1</b> General Principle</a></li>
<li class="chapter" data-level="2.3.2" data-path="how-to-use-gpower.html"><a href="how-to-use-gpower.html#types-of-power-analyses"><i class="fa fa-check"></i><b>2.3.2</b> Types of power analyses</a></li>
<li class="chapter" data-level="2.3.3" data-path="how-to-use-gpower.html"><a href="how-to-use-gpower.html#how-to-calculate-effect-size"><i class="fa fa-check"></i><b>2.3.3</b> How to calculate effect size</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="power-analysis-for-a-t-test-on-two-independent-means.html"><a href="power-analysis-for-a-t-test-on-two-independent-means.html"><i class="fa fa-check"></i><b>2.4</b> Power analysis for a t-test on two independent means</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="power-analysis-for-a-t-test-on-two-independent-means.html"><a href="power-analysis-for-a-t-test-on-two-independent-means.html#post-hoc-analysis"><i class="fa fa-check"></i><b>2.4.1</b> Post-hoc analysis</a></li>
<li class="chapter" data-level="2.4.2" data-path="power-analysis-for-a-t-test-on-two-independent-means.html"><a href="power-analysis-for-a-t-test-on-two-independent-means.html#a-priori-analysis"><i class="fa fa-check"></i><b>2.4.2</b> A priori analysis</a></li>
<li class="chapter" data-level="2.4.3" data-path="power-analysis-for-a-t-test-on-two-independent-means.html"><a href="power-analysis-for-a-t-test-on-two-independent-means.html#sensitivity-analysis---calculate-the-detectable-effect-size"><i class="fa fa-check"></i><b>2.4.3</b> Sensitivity analysis - Calculate the detectable effect size</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="important-points-to-remember.html"><a href="important-points-to-remember.html"><i class="fa fa-check"></i><b>2.5</b> Important points to remember</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="correlation-and-simple-linear-regression.html"><a href="correlation-and-simple-linear-regression.html"><i class="fa fa-check"></i><b>3</b> Correlation and simple linear regression</a>
<ul>
<li class="chapter" data-level="3.1" data-path="set-lm.html"><a href="set-lm.html"><i class="fa fa-check"></i><b>3.1</b> R packages and data</a></li>
<li class="chapter" data-level="3.2" data-path="scatter-plots.html"><a href="scatter-plots.html"><i class="fa fa-check"></i><b>3.2</b> Scatter plots</a></li>
<li class="chapter" data-level="3.3" data-path="data-transformations-and-the-product-moment-correlation.html"><a href="data-transformations-and-the-product-moment-correlation.html"><i class="fa fa-check"></i><b>3.3</b> Data transformations and the product-moment correlation</a></li>
<li class="chapter" data-level="3.4" data-path="testing-the-significance-of-correlations-and-bonferroni-probabilities.html"><a href="testing-the-significance-of-correlations-and-bonferroni-probabilities.html"><i class="fa fa-check"></i><b>3.4</b> Testing the significance of correlations and Bonferroni probabilities</a></li>
<li class="chapter" data-level="3.5" data-path="non-parametric-correlations-spearmans-rank-and-kendalls-tau.html"><a href="non-parametric-correlations-spearmans-rank-and-kendalls-tau.html"><i class="fa fa-check"></i><b>3.5</b> Non-parametric correlations: Spearman’s rank and Kendall’s <span class="math inline">\(\tau\)</span></a></li>
<li class="chapter" data-level="3.6" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html"><i class="fa fa-check"></i><b>3.6</b> Simple linear regression</a>
<ul>
<li class="chapter" data-level="3.6.1" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#testing-regression-assumptions"><i class="fa fa-check"></i><b>3.6.1</b> Testing regression assumptions</a></li>
<li class="chapter" data-level="3.6.2" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#formal-tests-of-regression-assumptions"><i class="fa fa-check"></i><b>3.6.2</b> Formal tests of regression assumptions</a></li>
</ul></li>
<li class="chapter" data-level="3.7" data-path="data-transformations-in-regression.html"><a href="data-transformations-in-regression.html"><i class="fa fa-check"></i><b>3.7</b> Data transformations in regression</a></li>
<li class="chapter" data-level="3.8" data-path="dealing-with-outliers.html"><a href="dealing-with-outliers.html"><i class="fa fa-check"></i><b>3.8</b> Dealing with outliers</a></li>
<li class="chapter" data-level="3.9" data-path="quantifying-effect-size-in-regression-and-power-analysis.html"><a href="quantifying-effect-size-in-regression-and-power-analysis.html"><i class="fa fa-check"></i><b>3.9</b> Quantifying effect size in regression and power analysis</a>
<ul>
<li class="chapter" data-level="3.9.1" data-path="quantifying-effect-size-in-regression-and-power-analysis.html"><a href="quantifying-effect-size-in-regression-and-power-analysis.html#power-to-detect-a-given-slope"><i class="fa fa-check"></i><b>3.9.1</b> Power to detect a given slope</a></li>
<li class="chapter" data-level="3.9.2" data-path="quantifying-effect-size-in-regression-and-power-analysis.html"><a href="quantifying-effect-size-in-regression-and-power-analysis.html#sample-size-required-to-achieve-desired-power"><i class="fa fa-check"></i><b>3.9.2</b> Sample size required to achieve desired power</a></li>
</ul></li>
<li class="chapter" data-level="3.10" data-path="bootstrapping-the-simple-linear-regression.html"><a href="bootstrapping-the-simple-linear-regression.html"><i class="fa fa-check"></i><b>3.10</b> Bootstrapping the simple linear regression</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="two---sample-comparisons.html"><a href="two---sample-comparisons.html"><i class="fa fa-check"></i><b>4</b> Two - sample comparisons</a>
<ul>
<li class="chapter" data-level="4.1" data-path="set-ttest.html"><a href="set-ttest.html"><i class="fa fa-check"></i><b>4.1</b> R packages and data</a></li>
<li class="chapter" data-level="4.2" data-path="visual-examination-of-sample-data.html"><a href="visual-examination-of-sample-data.html"><i class="fa fa-check"></i><b>4.2</b> Visual examination of sample data</a></li>
<li class="chapter" data-level="4.3" data-path="comparing-means-of-two-independent-samples-parametric-and-non-parametric-comparisons.html"><a href="comparing-means-of-two-independent-samples-parametric-and-non-parametric-comparisons.html"><i class="fa fa-check"></i><b>4.3</b> Comparing means of two independent samples: parametric and non-parametric comparisons</a></li>
<li class="chapter" data-level="4.4" data-path="bootstrap-and-permutation-tests-to-compare-2-means.html"><a href="bootstrap-and-permutation-tests-to-compare-2-means.html"><i class="fa fa-check"></i><b>4.4</b> Bootstrap and permutation tests to compare 2 means</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="bootstrap-and-permutation-tests-to-compare-2-means.html"><a href="bootstrap-and-permutation-tests-to-compare-2-means.html#bootstrap"><i class="fa fa-check"></i><b>4.4.1</b> Bootstrap</a></li>
<li class="chapter" data-level="4.4.2" data-path="bootstrap-and-permutation-tests-to-compare-2-means.html"><a href="bootstrap-and-permutation-tests-to-compare-2-means.html#permutation"><i class="fa fa-check"></i><b>4.4.2</b> Permutation</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="comparing-the-means-of-paired-samples.html"><a href="comparing-the-means-of-paired-samples.html"><i class="fa fa-check"></i><b>4.5</b> Comparing the means of paired samples</a></li>
<li class="chapter" data-level="4.6" data-path="bibliography.html"><a href="bibliography.html"><i class="fa fa-check"></i><b>4.6</b> Bibliography</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="one-way-anova.html"><a href="one-way-anova.html"><i class="fa fa-check"></i><b>5</b> One-way ANOVA</a>
<ul>
<li class="chapter" data-level="5.1" data-path="set-ano.html"><a href="set-ano.html"><i class="fa fa-check"></i><b>5.1</b> R packages and data</a></li>
<li class="chapter" data-level="5.2" data-path="one-way-anova-with-multiple-comparisons.html"><a href="one-way-anova-with-multiple-comparisons.html"><i class="fa fa-check"></i><b>5.2</b> One-way ANOVA with multiple comparisons</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="one-way-anova-with-multiple-comparisons.html"><a href="one-way-anova-with-multiple-comparisons.html#visualiser-les-données"><i class="fa fa-check"></i><b>5.2.1</b> Visualiser les données</a></li>
<li class="chapter" data-level="5.2.2" data-path="one-way-anova-with-multiple-comparisons.html"><a href="one-way-anova-with-multiple-comparisons.html#testing-the-assumptions-of-a-parametric-anova"><i class="fa fa-check"></i><b>5.2.2</b> Testing the assumptions of a parametric ANOVA</a></li>
<li class="chapter" data-level="5.2.3" data-path="one-way-anova-with-multiple-comparisons.html"><a href="one-way-anova-with-multiple-comparisons.html#performing-the-anova"><i class="fa fa-check"></i><b>5.2.3</b> Performing the ANOVA</a></li>
<li class="chapter" data-level="5.2.4" data-path="one-way-anova-with-multiple-comparisons.html"><a href="one-way-anova-with-multiple-comparisons.html#performing-multiple-comparisons-of-means-test"><i class="fa fa-check"></i><b>5.2.4</b> Performing multiple comparisons of means test</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="data-transformations-and-non-parametric-anova.html"><a href="data-transformations-and-non-parametric-anova.html"><i class="fa fa-check"></i><b>5.3</b> Data transformations and non-parametric ANOVA</a></li>
<li class="chapter" data-level="5.4" data-path="dealing-with-outliers-1.html"><a href="dealing-with-outliers-1.html"><i class="fa fa-check"></i><b>5.4</b> Dealing with outliers</a></li>
<li class="chapter" data-level="5.5" data-path="permutation-test.html"><a href="permutation-test.html"><i class="fa fa-check"></i><b>5.5</b> Permutation test</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="multiway-anova-factorial-and-nested-designs.html"><a href="multiway-anova-factorial-and-nested-designs.html"><i class="fa fa-check"></i><b>6</b> Multiway ANOVA: factorial and nested designs</a>
<ul>
<li class="chapter" data-level="6.1" data-path="set-anomul.html"><a href="set-anomul.html"><i class="fa fa-check"></i><b>6.1</b> R packages and data needed</a></li>
<li class="chapter" data-level="6.2" data-path="two-way-factorial-design-with-replication.html"><a href="two-way-factorial-design-with-replication.html"><i class="fa fa-check"></i><b>6.2</b> Two-way factorial design with replication</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="two-way-factorial-design-with-replication.html"><a href="two-way-factorial-design-with-replication.html#fixed-effects-anova-model-i"><i class="fa fa-check"></i><b>6.2.1</b> Fixed effects ANOVA (Model I)</a></li>
<li class="chapter" data-level="6.2.2" data-path="two-way-factorial-design-with-replication.html"><a href="two-way-factorial-design-with-replication.html#mixed-effects-anova-model-iii"><i class="fa fa-check"></i><b>6.2.2</b> Mixed effects ANOVA (Model III)</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="way-factorial-anova-without-replication.html"><a href="way-factorial-anova-without-replication.html"><i class="fa fa-check"></i><b>6.3</b> 2-way factorial ANOVA without replication</a></li>
<li class="chapter" data-level="6.4" data-path="nested-designs.html"><a href="nested-designs.html"><i class="fa fa-check"></i><b>6.4</b> Nested designs</a></li>
<li class="chapter" data-level="6.5" data-path="two-way-non-parametric-anova.html"><a href="two-way-non-parametric-anova.html"><i class="fa fa-check"></i><b>6.5</b> Two-way non-parametric ANOVA</a></li>
<li class="chapter" data-level="6.6" data-path="multiple-comparisons.html"><a href="multiple-comparisons.html"><i class="fa fa-check"></i><b>6.6</b> Multiple comparisons</a></li>
<li class="chapter" data-level="6.7" data-path="test-de-permutation-pour-lanova-à-deux-facteurs-de-classification.html"><a href="test-de-permutation-pour-lanova-à-deux-facteurs-de-classification.html"><i class="fa fa-check"></i><b>6.7</b> Test de permutation pour l’ANOVA à deux facteurs de classification</a></li>
<li class="chapter" data-level="6.8" data-path="bootstrap-for-two-way-anova.html"><a href="bootstrap-for-two-way-anova.html"><i class="fa fa-check"></i><b>6.8</b> Bootstrap for two-way ANOVA</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="multiple-regression.html"><a href="multiple-regression.html"><i class="fa fa-check"></i><b>7</b> Multiple regression</a>
<ul>
<li class="chapter" data-level="7.1" data-path="set-reg-mul.html"><a href="set-reg-mul.html"><i class="fa fa-check"></i><b>7.1</b> R packages and data</a></li>
<li class="chapter" data-level="7.2" data-path="points-to-keep-in-mind.html"><a href="points-to-keep-in-mind.html"><i class="fa fa-check"></i><b>7.2</b> Points to keep in mind</a></li>
<li class="chapter" data-level="7.3" data-path="first-look-at-the-data.html"><a href="first-look-at-the-data.html"><i class="fa fa-check"></i><b>7.3</b> First look at the data</a></li>
<li class="chapter" data-level="7.4" data-path="multiple-regression-models-from-scratch.html"><a href="multiple-regression-models-from-scratch.html"><i class="fa fa-check"></i><b>7.4</b> Multiple regression models from scratch</a></li>
<li class="chapter" data-level="7.5" data-path="stepwise-multiple-regression-procedures.html"><a href="stepwise-multiple-regression-procedures.html"><i class="fa fa-check"></i><b>7.5</b> Stepwise multiple regression procedures</a></li>
<li class="chapter" data-level="7.6" data-path="detecting-multicollinearity.html"><a href="detecting-multicollinearity.html"><i class="fa fa-check"></i><b>7.6</b> Detecting multicollinearity</a></li>
<li class="chapter" data-level="7.7" data-path="polynomial-regression.html"><a href="polynomial-regression.html"><i class="fa fa-check"></i><b>7.7</b> Polynomial regression</a></li>
<li class="chapter" data-level="7.8" data-path="checking-assumptions-of-a-multiple-regression-model.html"><a href="checking-assumptions-of-a-multiple-regression-model.html"><i class="fa fa-check"></i><b>7.8</b> Checking assumptions of a multiple regression model</a></li>
<li class="chapter" data-level="7.9" data-path="visualizing-effect-size.html"><a href="visualizing-effect-size.html"><i class="fa fa-check"></i><b>7.9</b> Visualizing effect size</a></li>
<li class="chapter" data-level="7.10" data-path="testing-for-interactions.html"><a href="testing-for-interactions.html"><i class="fa fa-check"></i><b>7.10</b> Testing for interactions</a></li>
<li class="chapter" data-level="7.11" data-path="dredging-and-the-information-theoretical-approach.html"><a href="dredging-and-the-information-theoretical-approach.html"><i class="fa fa-check"></i><b>7.11</b> Dredging and the information theoretical approach</a></li>
<li class="chapter" data-level="7.12" data-path="bootstrapping-multiple-regression.html"><a href="bootstrapping-multiple-regression.html"><i class="fa fa-check"></i><b>7.12</b> Bootstrapping multiple regression</a></li>
<li class="chapter" data-level="7.13" data-path="permutation-test-1.html"><a href="permutation-test-1.html"><i class="fa fa-check"></i><b>7.13</b> Permutation test</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="ancova-and-general-linear-model.html"><a href="ancova-and-general-linear-model.html"><i class="fa fa-check"></i><b>8</b> ANCOVA and general linear model</a>
<ul>
<li class="chapter" data-level="8.1" data-path="set-anco.html"><a href="set-anco.html"><i class="fa fa-check"></i><b>8.1</b> R packages and data</a></li>
<li class="chapter" data-level="8.2" data-path="linear-models.html"><a href="linear-models.html"><i class="fa fa-check"></i><b>8.2</b> Linear models</a></li>
<li class="chapter" data-level="8.3" data-path="ancova.html"><a href="ancova.html"><i class="fa fa-check"></i><b>8.3</b> ANCOVA</a></li>
<li class="chapter" data-level="8.4" data-path="homogeneity-of-slopes.html"><a href="homogeneity-of-slopes.html"><i class="fa fa-check"></i><b>8.4</b> Homogeneity of slopes</a>
<ul>
<li class="chapter" data-level="8.4.1" data-path="homogeneity-of-slopes.html"><a href="homogeneity-of-slopes.html#case-1---size-as-a-function-of-age-equal-slopes-example"><i class="fa fa-check"></i><b>8.4.1</b> Case 1 - Size as a function of age (equal slopes example)</a></li>
<li class="chapter" data-level="8.4.2" data-path="homogeneity-of-slopes.html"><a href="homogeneity-of-slopes.html#case-2---size-as-a-function-of-age-different-slopes-example"><i class="fa fa-check"></i><b>8.4.2</b> Case 2 - Size as a function of age (different slopes example)</a></li>
</ul></li>
<li class="chapter" data-level="8.5" data-path="the-ancova-model.html"><a href="the-ancova-model.html"><i class="fa fa-check"></i><b>8.5</b> The ANCOVA model</a></li>
<li class="chapter" data-level="8.6" data-path="comparing-model-fits.html"><a href="comparing-model-fits.html"><i class="fa fa-check"></i><b>8.6</b> Comparing model fits</a></li>
<li class="chapter" data-level="8.7" data-path="bootstrap-1.html"><a href="bootstrap-1.html"><i class="fa fa-check"></i><b>8.7</b> Bootstrap</a></li>
<li class="chapter" data-level="8.8" data-path="permutation-test-2.html"><a href="permutation-test-2.html"><i class="fa fa-check"></i><b>8.8</b> Permutation test</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="analysis-of-frequency-data-contingency-tables-log-linear-models-and-poisson-regression.html"><a href="analysis-of-frequency-data-contingency-tables-log-linear-models-and-poisson-regression.html"><i class="fa fa-check"></i><b>9</b> Analysis of frequency data: Contingency Tables, Log-Linear Models, and Poisson Regression</a>
<ul>
<li class="chapter" data-level="9.1" data-path="set-freq.html"><a href="set-freq.html"><i class="fa fa-check"></i><b>9.1</b> R packages and data</a></li>
<li class="chapter" data-level="9.2" data-path="organizing-the-data-3-forms.html"><a href="organizing-the-data-3-forms.html"><i class="fa fa-check"></i><b>9.2</b> Organizing the data: 3 forms</a></li>
<li class="chapter" data-level="9.3" data-path="graphs-for-contingency-tables-and-testing-for-independence.html"><a href="graphs-for-contingency-tables-and-testing-for-independence.html"><i class="fa fa-check"></i><b>9.3</b> Graphs for contingency tables and testing for independence</a></li>
<li class="chapter" data-level="9.4" data-path="log-linear-models-as-an-alternative-to-chi-square-test-for-contingency-tables.html"><a href="log-linear-models-as-an-alternative-to-chi-square-test-for-contingency-tables.html"><i class="fa fa-check"></i><b>9.4</b> Log-linear models as an alternative to Chi-square test for contingency tables</a></li>
<li class="chapter" data-level="9.5" data-path="testing-an-external-hypothesis.html"><a href="testing-an-external-hypothesis.html"><i class="fa fa-check"></i><b>9.5</b> Testing an external hypothesis</a></li>
<li class="chapter" data-level="9.6" data-path="poisson-regression-to-analyze-multi-way-tables.html"><a href="poisson-regression-to-analyze-multi-way-tables.html"><i class="fa fa-check"></i><b>9.6</b> Poisson regression to analyze multi-way tables</a></li>
<li class="chapter" data-level="9.7" data-path="ex-glm.html"><a href="ex-glm.html"><i class="fa fa-check"></i><b>9.7</b> Exercice</a></li>
</ul></li>
<li class="appendix"><span><b>Appendix</b></span></li>
<li class="chapter" data-level="A" data-path="software-tools.html"><a href="software-tools.html"><i class="fa fa-check"></i><b>A</b> Software Tools</a>
<ul>
<li class="chapter" data-level="A.1" data-path="r-and-r-packages.html"><a href="r-and-r-packages.html"><i class="fa fa-check"></i><b>A.1</b> R and R packages</a></li>
<li class="chapter" data-level="A.2" data-path="pandoc.html"><a href="pandoc.html"><i class="fa fa-check"></i><b>A.2</b> Pandoc</a></li>
<li class="chapter" data-level="A.3" data-path="latex.html"><a href="latex.html"><i class="fa fa-check"></i><b>A.3</b> LaTeX</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://bookdown.org" target="_blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">BIO4158 Applied biostats with R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="multiple-regression-models-from-scratch" class="section level2 hasAnchor" number="7.4">
<h2><span class="header-section-number">7.4</span> Multiple regression models from scratch<a href="multiple-regression-models-from-scratch.html#multiple-regression-models-from-scratch" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We begin the multiple regression exercise by considering a situation with one dependent variable and three (possibly) independent variables. First, we will start from scratch and build a multiple regression model based on what we know from building simple regression models. Next, we will look at automated methods of building multiple regressions models using simultaneous, forward, and backward stepwise procedures.</p>

<div class="rmdcode">
Using the subset of the <code>Mregdat.csv</code> data file, regress <code>logherp</code> on <code>logarea</code>.
</div>
<p>On the basis of the regression, what do you conclude?</p>
<div class="sourceCode" id="cb301"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb301-1"><a href="multiple-regression-models-from-scratch.html#cb301-1" aria-hidden="true"></a>model_loga &lt;-<span class="st"> </span><span class="kw">lm</span>(logherp <span class="op">~</span><span class="st"> </span>logarea, <span class="dt">data =</span> mydata)</span>
<span id="cb301-2"><a href="multiple-regression-models-from-scratch.html#cb301-2" aria-hidden="true"></a><span class="kw">summary</span>(model_loga)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = logherp ~ logarea, data = mydata)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.38082 -0.09265  0.00763  0.10409  0.46977 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  0.18503    0.15725   1.177 0.249996    
## logarea      0.24736    0.06536   3.784 0.000818 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.1856 on 26 degrees of freedom
##   (2 observations deleted due to missingness)
## Multiple R-squared:  0.3552, Adjusted R-squared:  0.3304 
## F-statistic: 14.32 on 1 and 26 DF,  p-value: 0.0008185</code></pre>
<div class="sourceCode" id="cb303"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb303-1"><a href="multiple-regression-models-from-scratch.html#cb303-1" aria-hidden="true"></a><span class="kw">par</span>(<span class="dt">mfrow =</span> <span class="kw">c</span>(<span class="dv">2</span>, <span class="dv">2</span>))</span>
<span id="cb303-2"><a href="multiple-regression-models-from-scratch.html#cb303-2" aria-hidden="true"></a><span class="kw">plot</span>(model_loga)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-90"></span>
<img src="Labs_BIO4158_files/figure-html/unnamed-chunk-90-1.svg" alt="Checking model asusmptions for regression of *logherp* as a function of *logarea*" width="672" />
<p class="caption">
Figure 7.2: Checking model asusmptions for regression of <em>logherp</em> as a function of <em>logarea</em>
</p>
</div>
<p>It looks like there is a positive relationship between herptile species richness and wetland area: the larger the wetland, the greater the number of species. Note, however, that about 2/3 of the observed variability in species richness among wetlands is not “explained” by wetland area (R<sup>2</sup> = 0.355). Residual analysis shows no major problems with normality, heteroscedasticity or independence of residuals.</p>

<div class="rmdcode">
Rerun the above regression, this time replacing <code>logarea</code> with <code>cpfor2</code> as the independent variable, such that the expression in the formula field reads: <code>logherp ~ cpfor2</code> . What do you conclude?
</div>
<div class="sourceCode" id="cb304"><pre class="sourceCode r exer"><code class="sourceCode r"><span id="cb304-1"><a href="multiple-regression-models-from-scratch.html#cb304-1" aria-hidden="true"></a>model_logcp &lt;-<span class="st"> </span><span class="kw">lm</span>(logherp <span class="op">~</span><span class="st"> </span>cpfor2, <span class="dt">data =</span> mydata)</span>
<span id="cb304-2"><a href="multiple-regression-models-from-scratch.html#cb304-2" aria-hidden="true"></a><span class="kw">summary</span>(model_logcp)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = logherp ~ cpfor2, data = mydata)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.49095 -0.10266  0.05881  0.16027  0.25159 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 0.609197   0.104233   5.845 3.68e-06 ***
## cpfor2      0.002706   0.001658   1.632    0.115    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.2202 on 26 degrees of freedom
##   (2 observations deleted due to missingness)
## Multiple R-squared:  0.09289,    Adjusted R-squared:  0.058 
## F-statistic: 2.662 on 1 and 26 DF,  p-value: 0.1148</code></pre>
<p>According to this result, we would accept the null hypothesis, and conclude that there is no relationship between herptile density and the proportion of forest on adjacent lands. But what happens when we enter both variables into the regression simultaneously?</p>

<div class="rmdcode">
Rerun the above regression one more time, this time adding both independent variables into the model at once, such that <code>logherp ~ logarea + cpfor2</code> . What do you conclude?
</div>
<div class="sourceCode" id="cb306"><pre class="sourceCode r exer"><code class="sourceCode r"><span id="cb306-1"><a href="multiple-regression-models-from-scratch.html#cb306-1" aria-hidden="true"></a>model_mcp &lt;-<span class="st"> </span><span class="kw">lm</span>(logherp <span class="op">~</span><span class="st"> </span>logarea <span class="op">+</span><span class="st"> </span>cpfor2, <span class="dt">data =</span> mydata)</span>
<span id="cb306-2"><a href="multiple-regression-models-from-scratch.html#cb306-2" aria-hidden="true"></a><span class="kw">summary</span>(model_mcp)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = logherp ~ logarea + cpfor2, data = mydata)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.40438 -0.11512  0.01774  0.08187  0.36179 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 0.027058   0.166749   0.162 0.872398    
## logarea     0.247789   0.061603   4.022 0.000468 ***
## cpfor2      0.002724   0.001318   2.067 0.049232 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.175 on 25 degrees of freedom
##   (2 observations deleted due to missingness)
## Multiple R-squared:  0.4493, Adjusted R-squared:  0.4052 
## F-statistic:  10.2 on 2 and 25 DF,  p-value: 0.0005774</code></pre>
<p>Now we reject both null hypotheses that the slope of the regression of <code>logherp</code> on logarea is zero and that the slope of the regression of <code>logherp</code> on <code>cpfor2</code> is zero.</p>
<p>Why is <code>cpfor2</code> a significant predictor of <code>logherp</code> in the combined model when it was not significant in the simple linear model? The answer lies in the fact that it is sometimes necessary to control for one variable in order to detect the effect of another variable. In this case, there is a significant relationship between <code>logherp</code> and <code>logarea</code> that masks the relationship between <code>logherp</code> and <code>cpfor2</code> . When both variables are entered into the model at once, the effect of logarea is controlled for, making it possible to detect a <code>cpfor2</code> effect (and vice versa).</p>

<div class="rmdcode">
Run another multiple regression, this time substituting <code>thtden</code> for <code>cpfor2</code> as an independent variable (<code>logherp ~ logarea + thtden</code>).
</div>
<div class="sourceCode" id="cb308"><pre class="sourceCode r exer"><code class="sourceCode r"><span id="cb308-1"><a href="multiple-regression-models-from-scratch.html#cb308-1" aria-hidden="true"></a>model_mden &lt;-<span class="st"> </span><span class="kw">lm</span>(logherp <span class="op">~</span><span class="st"> </span>logarea <span class="op">+</span><span class="st"> </span>thtden, <span class="dt">data =</span> mydata)</span>
<span id="cb308-2"><a href="multiple-regression-models-from-scratch.html#cb308-2" aria-hidden="true"></a><span class="kw">summary</span>(model_mden)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = logherp ~ logarea + thtden, data = mydata)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.31583 -0.12326  0.02095  0.13201  0.31674 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  0.37634    0.14926   2.521 0.018437 *  
## logarea      0.22504    0.05701   3.947 0.000567 ***
## thtden      -0.04196    0.01345  -3.118 0.004535 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.1606 on 25 degrees of freedom
##   (2 observations deleted due to missingness)
## Multiple R-squared:  0.5358, Adjusted R-squared:  0.4986 
## F-statistic: 14.43 on 2 and 25 DF,  p-value: 6.829e-05</code></pre>
<p>In this case we reject the null hypotheses that there are no effects of wetland area ( <code>logarea</code> ) and road density ( <code>thtden</code> ) on herptile richness ( <code>logherp</code> ). Note here that road density has a negative effect on richness, whereas wetland area and forested area ( <code>cpfor2</code>; results from previous regression) both have positive effects on herptile richness.</p>
<p>The R<sup>2</sup> of this model is even higher than the previous multiple regression model, reflecting a higher correlation between logherp and thtden than between logherp and <code>cpfor2</code> (if you run a simple regression between logherp and thtden and compare it to the <code>cpfor2</code> regression you should be able to detect this).</p>
<p>Thus far, it appears that herptile richness is related to wetland area ( <code>logarea</code> ), road density ( <code>thtden</code> ), and possibly forest cover on adjacent lands ( <code>cpfor2</code> ). But, does it necessarily follow that if we build a regression model with all three independent variables, that all three will show significant relationships? No, because we have not yet examined the relationship between Logarea , <code>cpfor2</code> and thtden . Suppose, for example, two of the variables (say, <code>cpfor2</code> and <code>thtden</code> ) are perfectly correlated. Then the <code>thtden</code> effect is nothing more than the <code>cpfor2</code> effect (and vice versa), so that once we include one or the other in the regression model, none of the remaining variability would be explained by the third variable.</p>

<div class="rmdcode">
Fit a regression model with logherp as the dependent variable and logarea , cpfor2 and thtden as the independent variables. What do you conclude?
</div>
<div class="sourceCode" id="cb310"><pre class="sourceCode r exer"><code class="sourceCode r"><span id="cb310-1"><a href="multiple-regression-models-from-scratch.html#cb310-1" aria-hidden="true"></a>model_mtri &lt;-<span class="st"> </span><span class="kw">lm</span>(logherp <span class="op">~</span><span class="st"> </span>logarea <span class="op">+</span><span class="st"> </span>cpfor2 <span class="op">+</span><span class="st"> </span>thtden, <span class="dt">data =</span> mydata)</span>
<span id="cb310-2"><a href="multiple-regression-models-from-scratch.html#cb310-2" aria-hidden="true"></a><span class="kw">summary</span>(model_mtri)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = logherp ~ logarea + cpfor2 + thtden, data = mydata)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.30729 -0.13779  0.02627  0.11441  0.29582 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  0.284765   0.191420   1.488 0.149867    
## logarea      0.228490   0.057647   3.964 0.000578 ***
## cpfor2       0.001095   0.001414   0.774 0.446516    
## thtden      -0.035794   0.015726  -2.276 0.032055 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.1619 on 24 degrees of freedom
##   (2 observations deleted due to missingness)
## Multiple R-squared:  0.5471, Adjusted R-squared:  0.4904 
## F-statistic: 9.662 on 3 and 24 DF,  p-value: 0.0002291</code></pre>
<p>Several things to note here:</p>
<ol style="list-style-type: decimal">
<li>The regression coefficient for <code>cpfor2</code> has become non-significant: once the variability explained by <code>logarea</code> and <code>thtden</code> is removed, a non-significant part of the remaining variability is explained by <code>cpfor2</code>.</li>
<li>The <em>R<sup>2</sup></em> for this model (.547 is only marginally larger than the <em>R<sup>2</sup></em> for the model with only logarea and thtden (.536, which is again consistent with the non-significant coefficient for <code>cpfor2</code>.</li>
</ol>
<p>Note also that although the regression coefficient for <code>thtden</code> has not changed much from that obtained when just <code>thtden</code> and <code>logarea</code> were included in the fitted model (-.036 vs -.042, the standard error for the regression coefficient for <code>thtden</code> has increased slightly, meaning the estimate is less precise. If the correlation between <code>thtden</code> and <code>cpfor2</code> was greater, the change in precision would also be greater.</p>
<p>We can compare the fit of the last two models (<em>i.e.</em>, the model with all 3 variables and the model with only <code>logarea</code> and <code>thtden</code> to decide which model is best to include.</p>
<div class="sourceCode" id="cb312"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb312-1"><a href="multiple-regression-models-from-scratch.html#cb312-1" aria-hidden="true"></a><span class="kw">anova</span>(model_mtri, model_mden)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Model 1: logherp ~ logarea + cpfor2 + thtden
## Model 2: logherp ~ logarea + thtden
##   Res.Df     RSS Df Sum of Sq     F Pr(&gt;F)
## 1     24 0.62937                          
## 2     25 0.64508 -1 -0.015708 0.599 0.4465</code></pre>
<p>Note that this is the identical result we obtained via the t-test of the effect
of <code>cpfor2</code> in the model with all 3 variables above as they are testing the same thing (this should make sense to you). From this analysis, we would conclude that the full model with all three variables included does not offer a significant improvement in fit over the model with only <code>logarea</code> and <code>thtden</code>. This isn’t surprising given that we already know that we cannot reject the null hypothesis of no effect of <code>cpfor2</code> in the full model. Overall, we would conclude, on the basis of these analyses, that:</p>
<ol style="list-style-type: decimal">
<li>Given the three variables <code>thtden</code> , <code>logarea</code> and <code>cpfor2</code> , the best model is one that includes the first two variables.</li>
<li>There is evidence of a negative relationship between herptile richness and the density of roads on adjacent lands.</li>
<li>There is evidence that the larger the wetland area, the greater the herptile species richness. Note that by “best”, I don’t mean the best possible model, I mean the best one given the three predictor variables we started with. It seems pretty clear that there are other factors controlling richness in wetlands, since even with the “best” model, almost half of the variability in richness is unexplained.</li>
</ol>
</div>
<script src="js/solution.js"></script>
            </section>

          </div>
        </div>
      </div>
<a href="first-look-at-the-data.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="stepwise-multiple-regression-procedures.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": false,
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/Bio4158-4558-uottawa/lab_manual/edit/main/07-reg_mult.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["Labs_BIO4158.pdf", "Labs_BIO4158.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
