<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>5.2 One-way ANOVA with multiple comparisons | BIO4158 Applied biostats with R</title>
  <meta name="description" content="Laboratory manual for BIO4158 Applied biostatistics" />
  <meta name="generator" content="bookdown 0.24 and GitBook 2.6.7" />

  <meta property="og:title" content="5.2 One-way ANOVA with multiple comparisons | BIO4158 Applied biostats with R" />
  <meta property="og:type" content="book" />
  
  <meta property="og:image" content="/images/missing.png" />
  <meta property="og:description" content="Laboratory manual for BIO4158 Applied biostatistics" />
  <meta name="github-repo" content="Bio4158-4558-uottawa/lab_manual/" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="5.2 One-way ANOVA with multiple comparisons | BIO4158 Applied biostats with R" />
  
  <meta name="twitter:description" content="Laboratory manual for BIO4158 Applied biostatistics" />
  <meta name="twitter:image" content="/images/missing.png" />

<meta name="author" content="Julien Martin" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="set-ano.html"/>
<link rel="next" href="data-transformations-and-non-parametric-anova.html"/>
<script src="libs/header-attrs-2.11/header-attrs.js"></script>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>
<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="css/style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">BIO4158 Laboratory manual</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Note</a></li>
<li class="chapter" data-level="" data-path="preface.html"><a href="preface.html"><i class="fa fa-check"></i>Preface</a>
<ul>
<li class="chapter" data-level="" data-path="general-points-to-keep-in-mind.html"><a href="general-points-to-keep-in-mind.html"><i class="fa fa-check"></i>General points to keep in mind</a></li>
<li class="chapter" data-level="" data-path="what-is-r-and-why-use-it-in-this-course.html"><a href="what-is-r-and-why-use-it-in-this-course.html"><i class="fa fa-check"></i>What is R and why use it in this course?</a></li>
<li class="chapter" data-level="" data-path="software-installation.html"><a href="software-installation.html"><i class="fa fa-check"></i>Software installation</a>
<ul>
<li class="chapter" data-level="" data-path="software-installation.html"><a href="software-installation.html#r"><i class="fa fa-check"></i>R</a></li>
<li class="chapter" data-level="" data-path="software-installation.html"><a href="software-installation.html#rstudio-or-vs-code"><i class="fa fa-check"></i>Rstudio or VS code</a></li>
<li class="chapter" data-level="" data-path="software-installation.html"><a href="software-installation.html#r-libraries"><i class="fa fa-check"></i>R libraries</a></li>
<li class="chapter" data-level="" data-path="software-installation.html"><a href="software-installation.html#gpower"><i class="fa fa-check"></i>G*Power</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="general-laboratory-instructions.html"><a href="general-laboratory-instructions.html"><i class="fa fa-check"></i>General laboratory instructions</a></li>
<li class="chapter" data-level="" data-path="notes-about-the-manual.html"><a href="notes-about-the-manual.html"><i class="fa fa-check"></i>Notes about the manual</a>
<ul>
<li class="chapter" data-level="" data-path="notes-about-the-manual.html"><a href="notes-about-the-manual.html#resources"><i class="fa fa-check"></i>Resources</a></li>
<li class="chapter" data-level="" data-path="notes-about-the-manual.html"><a href="notes-about-the-manual.html#license"><i class="fa fa-check"></i>License</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="1" data-path="introduction-to-r.html"><a href="introduction-to-r.html"><i class="fa fa-check"></i><b>1</b> Introduction to R</a>
<ul>
<li class="chapter" data-level="1.1" data-path="set-intro.html"><a href="set-intro.html"><i class="fa fa-check"></i><b>1.1</b> Packages and data needed for the lab</a></li>
<li class="chapter" data-level="1.2" data-path="importing-and-exporting-data.html"><a href="importing-and-exporting-data.html"><i class="fa fa-check"></i><b>1.2</b> Importing and exporting data</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="importing-and-exporting-data.html"><a href="importing-and-exporting-data.html#working-directory"><i class="fa fa-check"></i><b>1.2.1</b> Working directory</a></li>
<li class="chapter" data-level="1.2.2" data-path="importing-and-exporting-data.html"><a href="importing-and-exporting-data.html#opening-a-.rdata-file"><i class="fa fa-check"></i><b>1.2.2</b> Opening a <code>.Rdata</code> file</a></li>
<li class="chapter" data-level="1.2.3" data-path="importing-and-exporting-data.html"><a href="importing-and-exporting-data.html#open-a-.csv-file"><i class="fa fa-check"></i><b>1.2.3</b> Open a <code>.csv</code> file</a></li>
<li class="chapter" data-level="1.2.4" data-path="importing-and-exporting-data.html"><a href="importing-and-exporting-data.html#entering-data-in-r"><i class="fa fa-check"></i><b>1.2.4</b> Entering data in R</a></li>
<li class="chapter" data-level="1.2.5" data-path="importing-and-exporting-data.html"><a href="importing-and-exporting-data.html#cleaning-up-correcting-data"><i class="fa fa-check"></i><b>1.2.5</b> Cleaning up / correcting data</a></li>
<li class="chapter" data-level="1.2.6" data-path="importing-and-exporting-data.html"><a href="importing-and-exporting-data.html#exporting-data-from-r"><i class="fa fa-check"></i><b>1.2.6</b> Exporting data from R</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="preliminary-examination-of-data.html"><a href="preliminary-examination-of-data.html"><i class="fa fa-check"></i><b>1.3</b> Preliminary examination of data</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="preliminary-examination-of-data.html"><a href="preliminary-examination-of-data.html#summary-statistics"><i class="fa fa-check"></i><b>1.3.1</b> Summary statistics</a></li>
<li class="chapter" data-level="1.3.2" data-path="preliminary-examination-of-data.html"><a href="preliminary-examination-of-data.html#histogram-empirical-probability-density-boxplot-and-visual-assessment-of-normality"><i class="fa fa-check"></i><b>1.3.2</b> Histogram, empirical probability density, boxplot, and visual assessment of normality</a></li>
<li class="chapter" data-level="1.3.3" data-path="preliminary-examination-of-data.html"><a href="preliminary-examination-of-data.html#scatterplots"><i class="fa fa-check"></i><b>1.3.3</b> Scatterplots</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="creating-data-subsets.html"><a href="creating-data-subsets.html"><i class="fa fa-check"></i><b>1.4</b> Creating data subsets</a></li>
<li class="chapter" data-level="1.5" data-path="data-transformation.html"><a href="data-transformation.html"><i class="fa fa-check"></i><b>1.5</b> Data transformation</a></li>
<li class="chapter" data-level="1.6" data-path="exercice.html"><a href="exercice.html"><i class="fa fa-check"></i><b>1.6</b> Exercice</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="power-analysis-with-r-and-gpower.html"><a href="power-analysis-with-r-and-gpower.html"><i class="fa fa-check"></i><b>2</b> Power Analysis with R and G*Power</a>
<ul>
<li class="chapter" data-level="2.1" data-path="the-theory.html"><a href="the-theory.html"><i class="fa fa-check"></i><b>2.1</b> The theory</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="the-theory.html"><a href="the-theory.html#what-is-power"><i class="fa fa-check"></i><b>2.1.1</b> What is power?</a></li>
<li class="chapter" data-level="2.1.2" data-path="the-theory.html"><a href="the-theory.html#why-do-a-power-analysis"><i class="fa fa-check"></i><b>2.1.2</b> Why do a power analysis?</a></li>
<li class="chapter" data-level="2.1.3" data-path="the-theory.html"><a href="the-theory.html#factors-affecting-power"><i class="fa fa-check"></i><b>2.1.3</b> Factors affecting power</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="what-is-gpower.html"><a href="what-is-gpower.html"><i class="fa fa-check"></i><b>2.2</b> What is G*Power?</a></li>
<li class="chapter" data-level="2.3" data-path="how-to-use-gpower.html"><a href="how-to-use-gpower.html"><i class="fa fa-check"></i><b>2.3</b> How to use G*Power</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="how-to-use-gpower.html"><a href="how-to-use-gpower.html#general-principle"><i class="fa fa-check"></i><b>2.3.1</b> General Principle</a></li>
<li class="chapter" data-level="2.3.2" data-path="how-to-use-gpower.html"><a href="how-to-use-gpower.html#types-of-power-analyses"><i class="fa fa-check"></i><b>2.3.2</b> Types of power analyses</a></li>
<li class="chapter" data-level="2.3.3" data-path="how-to-use-gpower.html"><a href="how-to-use-gpower.html#how-to-calculate-effect-size"><i class="fa fa-check"></i><b>2.3.3</b> How to calculate effect size</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="power-analysis-for-a-t-test-on-two-independent-means.html"><a href="power-analysis-for-a-t-test-on-two-independent-means.html"><i class="fa fa-check"></i><b>2.4</b> Power analysis for a t-test on two independent means</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="power-analysis-for-a-t-test-on-two-independent-means.html"><a href="power-analysis-for-a-t-test-on-two-independent-means.html#post-hoc-analysis"><i class="fa fa-check"></i><b>2.4.1</b> Post-hoc analysis</a></li>
<li class="chapter" data-level="2.4.2" data-path="power-analysis-for-a-t-test-on-two-independent-means.html"><a href="power-analysis-for-a-t-test-on-two-independent-means.html#a-priori-analysis"><i class="fa fa-check"></i><b>2.4.2</b> A priori analysis</a></li>
<li class="chapter" data-level="2.4.3" data-path="power-analysis-for-a-t-test-on-two-independent-means.html"><a href="power-analysis-for-a-t-test-on-two-independent-means.html#sensitivity-analysis---calculate-the-detectable-effect-size"><i class="fa fa-check"></i><b>2.4.3</b> Sensitivity analysis - Calculate the detectable effect size</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="important-points-to-remember.html"><a href="important-points-to-remember.html"><i class="fa fa-check"></i><b>2.5</b> Important points to remember</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="correlation-and-simple-linear-regression.html"><a href="correlation-and-simple-linear-regression.html"><i class="fa fa-check"></i><b>3</b> Correlation and simple linear regression</a>
<ul>
<li class="chapter" data-level="3.1" data-path="set-lm.html"><a href="set-lm.html"><i class="fa fa-check"></i><b>3.1</b> R packages and data</a></li>
<li class="chapter" data-level="3.2" data-path="scatter-plots.html"><a href="scatter-plots.html"><i class="fa fa-check"></i><b>3.2</b> Scatter plots</a></li>
<li class="chapter" data-level="3.3" data-path="data-transformations-and-the-product-moment-correlation.html"><a href="data-transformations-and-the-product-moment-correlation.html"><i class="fa fa-check"></i><b>3.3</b> Data transformations and the product-moment correlation</a></li>
<li class="chapter" data-level="3.4" data-path="testing-the-significance-of-correlations-and-bonferroni-probabilities.html"><a href="testing-the-significance-of-correlations-and-bonferroni-probabilities.html"><i class="fa fa-check"></i><b>3.4</b> Testing the significance of correlations and Bonferroni probabilities</a></li>
<li class="chapter" data-level="3.5" data-path="non-parametric-correlations-spearmans-rank-and-kendalls-tau.html"><a href="non-parametric-correlations-spearmans-rank-and-kendalls-tau.html"><i class="fa fa-check"></i><b>3.5</b> Non-parametric correlations: Spearman’s rank and Kendall’s <span class="math inline">\(\tau\)</span></a></li>
<li class="chapter" data-level="3.6" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html"><i class="fa fa-check"></i><b>3.6</b> Simple linear regression</a>
<ul>
<li class="chapter" data-level="3.6.1" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#testing-regression-assumptions"><i class="fa fa-check"></i><b>3.6.1</b> Testing regression assumptions</a></li>
<li class="chapter" data-level="3.6.2" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#formal-tests-of-regression-assumptions"><i class="fa fa-check"></i><b>3.6.2</b> Formal tests of regression assumptions</a></li>
</ul></li>
<li class="chapter" data-level="3.7" data-path="data-transformations-in-regression.html"><a href="data-transformations-in-regression.html"><i class="fa fa-check"></i><b>3.7</b> Data transformations in regression</a></li>
<li class="chapter" data-level="3.8" data-path="dealing-with-outliers.html"><a href="dealing-with-outliers.html"><i class="fa fa-check"></i><b>3.8</b> Dealing with outliers</a></li>
<li class="chapter" data-level="3.9" data-path="quantifying-effect-size-in-regression-and-power-analysis.html"><a href="quantifying-effect-size-in-regression-and-power-analysis.html"><i class="fa fa-check"></i><b>3.9</b> Quantifying effect size in regression and power analysis</a>
<ul>
<li class="chapter" data-level="3.9.1" data-path="quantifying-effect-size-in-regression-and-power-analysis.html"><a href="quantifying-effect-size-in-regression-and-power-analysis.html#power-to-detect-a-given-slope"><i class="fa fa-check"></i><b>3.9.1</b> Power to detect a given slope</a></li>
<li class="chapter" data-level="3.9.2" data-path="quantifying-effect-size-in-regression-and-power-analysis.html"><a href="quantifying-effect-size-in-regression-and-power-analysis.html#sample-size-required-to-achieve-desired-power"><i class="fa fa-check"></i><b>3.9.2</b> Sample size required to achieve desired power</a></li>
</ul></li>
<li class="chapter" data-level="3.10" data-path="bootstrapping-the-simple-linear-regression.html"><a href="bootstrapping-the-simple-linear-regression.html"><i class="fa fa-check"></i><b>3.10</b> Bootstrapping the simple linear regression</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="two---sample-comparisons.html"><a href="two---sample-comparisons.html"><i class="fa fa-check"></i><b>4</b> Two - sample comparisons</a>
<ul>
<li class="chapter" data-level="4.1" data-path="set-ttest.html"><a href="set-ttest.html"><i class="fa fa-check"></i><b>4.1</b> R packages and data</a></li>
<li class="chapter" data-level="4.2" data-path="visual-examination-of-sample-data.html"><a href="visual-examination-of-sample-data.html"><i class="fa fa-check"></i><b>4.2</b> Visual examination of sample data</a></li>
<li class="chapter" data-level="4.3" data-path="comparing-means-of-two-independent-samples-parametric-and-non-parametric-comparisons.html"><a href="comparing-means-of-two-independent-samples-parametric-and-non-parametric-comparisons.html"><i class="fa fa-check"></i><b>4.3</b> Comparing means of two independent samples: parametric and non-parametric comparisons</a></li>
<li class="chapter" data-level="4.4" data-path="bootstrap-and-permutation-tests-to-compare-2-means.html"><a href="bootstrap-and-permutation-tests-to-compare-2-means.html"><i class="fa fa-check"></i><b>4.4</b> Bootstrap and permutation tests to compare 2 means</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="bootstrap-and-permutation-tests-to-compare-2-means.html"><a href="bootstrap-and-permutation-tests-to-compare-2-means.html#bootstrap"><i class="fa fa-check"></i><b>4.4.1</b> Bootstrap</a></li>
<li class="chapter" data-level="4.4.2" data-path="bootstrap-and-permutation-tests-to-compare-2-means.html"><a href="bootstrap-and-permutation-tests-to-compare-2-means.html#permutation"><i class="fa fa-check"></i><b>4.4.2</b> Permutation</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="comparing-the-means-of-paired-samples.html"><a href="comparing-the-means-of-paired-samples.html"><i class="fa fa-check"></i><b>4.5</b> Comparing the means of paired samples</a></li>
<li class="chapter" data-level="4.6" data-path="références.html"><a href="références.html"><i class="fa fa-check"></i><b>4.6</b> Références</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="one-way-anova.html"><a href="one-way-anova.html"><i class="fa fa-check"></i><b>5</b> One-way ANOVA</a>
<ul>
<li class="chapter" data-level="5.1" data-path="set-ano.html"><a href="set-ano.html"><i class="fa fa-check"></i><b>5.1</b> R packages and data</a></li>
<li class="chapter" data-level="5.2" data-path="one-way-anova-with-multiple-comparisons.html"><a href="one-way-anova-with-multiple-comparisons.html"><i class="fa fa-check"></i><b>5.2</b> One-way ANOVA with multiple comparisons</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="one-way-anova-with-multiple-comparisons.html"><a href="one-way-anova-with-multiple-comparisons.html#visualiser-les-données"><i class="fa fa-check"></i><b>5.2.1</b> Visualiser les données</a></li>
<li class="chapter" data-level="5.2.2" data-path="one-way-anova-with-multiple-comparisons.html"><a href="one-way-anova-with-multiple-comparisons.html#testing-the-assumptions-of-a-parametric-anova"><i class="fa fa-check"></i><b>5.2.2</b> Testing the assumptions of a parametric ANOVA</a></li>
<li class="chapter" data-level="5.2.3" data-path="one-way-anova-with-multiple-comparisons.html"><a href="one-way-anova-with-multiple-comparisons.html#performing-the-anova"><i class="fa fa-check"></i><b>5.2.3</b> Performing the ANOVA</a></li>
<li class="chapter" data-level="5.2.4" data-path="one-way-anova-with-multiple-comparisons.html"><a href="one-way-anova-with-multiple-comparisons.html#performing-multiple-comparisons-of-means-test"><i class="fa fa-check"></i><b>5.2.4</b> Performing multiple comparisons of means test</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="data-transformations-and-non-parametric-anova.html"><a href="data-transformations-and-non-parametric-anova.html"><i class="fa fa-check"></i><b>5.3</b> Data transformations and non-parametric ANOVA</a></li>
<li class="chapter" data-level="5.4" data-path="dealing-with-outliers-1.html"><a href="dealing-with-outliers-1.html"><i class="fa fa-check"></i><b>5.4</b> Dealing with outliers</a></li>
<li class="chapter" data-level="5.5" data-path="permutation-test.html"><a href="permutation-test.html"><i class="fa fa-check"></i><b>5.5</b> Permutation test</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="multiway-anova-factorial-and-nested-designs.html"><a href="multiway-anova-factorial-and-nested-designs.html"><i class="fa fa-check"></i><b>6</b> Multiway ANOVA: factorial and nested designs</a>
<ul>
<li class="chapter" data-level="6.1" data-path="set-anomul.html"><a href="set-anomul.html"><i class="fa fa-check"></i><b>6.1</b> R packages and data needed</a></li>
<li class="chapter" data-level="6.2" data-path="two-way-factorial-design-with-replication.html"><a href="two-way-factorial-design-with-replication.html"><i class="fa fa-check"></i><b>6.2</b> Two-way factorial design with replication</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="two-way-factorial-design-with-replication.html"><a href="two-way-factorial-design-with-replication.html#fixed-effects-anova-model-i"><i class="fa fa-check"></i><b>6.2.1</b> Fixed effects ANOVA (Model I)</a></li>
<li class="chapter" data-level="6.2.2" data-path="two-way-factorial-design-with-replication.html"><a href="two-way-factorial-design-with-replication.html#mixed-effects-anova-model-iii"><i class="fa fa-check"></i><b>6.2.2</b> Mixed effects ANOVA (Model III)</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="way-factorial-anova-without-replication.html"><a href="way-factorial-anova-without-replication.html"><i class="fa fa-check"></i><b>6.3</b> 2-way factorial ANOVA without replication</a></li>
<li class="chapter" data-level="6.4" data-path="nested-designs.html"><a href="nested-designs.html"><i class="fa fa-check"></i><b>6.4</b> Nested designs</a></li>
<li class="chapter" data-level="6.5" data-path="two-way-non-parametric-anova.html"><a href="two-way-non-parametric-anova.html"><i class="fa fa-check"></i><b>6.5</b> Two-way non-parametric ANOVA</a></li>
<li class="chapter" data-level="6.6" data-path="multiple-comparisons.html"><a href="multiple-comparisons.html"><i class="fa fa-check"></i><b>6.6</b> Multiple comparisons</a></li>
<li class="chapter" data-level="6.7" data-path="test-de-permutation-pour-lanova-à-deux-facteurs-de-classification.html"><a href="test-de-permutation-pour-lanova-à-deux-facteurs-de-classification.html"><i class="fa fa-check"></i><b>6.7</b> Test de permutation pour l’ANOVA à deux facteurs de classification</a></li>
<li class="chapter" data-level="6.8" data-path="bootstrap-for-two-way-anova.html"><a href="bootstrap-for-two-way-anova.html"><i class="fa fa-check"></i><b>6.8</b> Bootstrap for two-way ANOVA</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="multiple-regression.html"><a href="multiple-regression.html"><i class="fa fa-check"></i><b>7</b> Multiple regression</a>
<ul>
<li class="chapter" data-level="7.1" data-path="set-reg-mul.html"><a href="set-reg-mul.html"><i class="fa fa-check"></i><b>7.1</b> R packages and data</a></li>
<li class="chapter" data-level="7.2" data-path="points-to-keep-in-mind.html"><a href="points-to-keep-in-mind.html"><i class="fa fa-check"></i><b>7.2</b> Points to keep in mind</a></li>
<li class="chapter" data-level="7.3" data-path="first-look-at-the-data.html"><a href="first-look-at-the-data.html"><i class="fa fa-check"></i><b>7.3</b> First look at the data</a></li>
<li class="chapter" data-level="7.4" data-path="multiple-regression-models-from-scratch.html"><a href="multiple-regression-models-from-scratch.html"><i class="fa fa-check"></i><b>7.4</b> Multiple regression models from scratch</a></li>
<li class="chapter" data-level="7.5" data-path="stepwise-multiple-regression-procedures.html"><a href="stepwise-multiple-regression-procedures.html"><i class="fa fa-check"></i><b>7.5</b> Stepwise multiple regression procedures</a></li>
<li class="chapter" data-level="7.6" data-path="detecting-multicollinearity.html"><a href="detecting-multicollinearity.html"><i class="fa fa-check"></i><b>7.6</b> Detecting multicollinearity</a></li>
<li class="chapter" data-level="7.7" data-path="polynomial-regression.html"><a href="polynomial-regression.html"><i class="fa fa-check"></i><b>7.7</b> Polynomial regression</a></li>
<li class="chapter" data-level="7.8" data-path="checking-assumptions-of-a-multiple-regression-model.html"><a href="checking-assumptions-of-a-multiple-regression-model.html"><i class="fa fa-check"></i><b>7.8</b> Checking assumptions of a multiple regression model</a></li>
<li class="chapter" data-level="7.9" data-path="visualizing-effect-size.html"><a href="visualizing-effect-size.html"><i class="fa fa-check"></i><b>7.9</b> Visualizing effect size</a></li>
<li class="chapter" data-level="7.10" data-path="testing-for-interactions.html"><a href="testing-for-interactions.html"><i class="fa fa-check"></i><b>7.10</b> Testing for interactions</a></li>
<li class="chapter" data-level="7.11" data-path="dredging-and-the-information-theoretical-approach.html"><a href="dredging-and-the-information-theoretical-approach.html"><i class="fa fa-check"></i><b>7.11</b> Dredging and the information theoretical approach</a></li>
<li class="chapter" data-level="7.12" data-path="bootstrapping-multiple-regression.html"><a href="bootstrapping-multiple-regression.html"><i class="fa fa-check"></i><b>7.12</b> Bootstrapping multiple regression</a></li>
<li class="chapter" data-level="7.13" data-path="permutation-test-1.html"><a href="permutation-test-1.html"><i class="fa fa-check"></i><b>7.13</b> Permutation test</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="ancova-et-modèle-linéaire-général.html"><a href="ancova-et-modèle-linéaire-général.html"><i class="fa fa-check"></i><b>8</b> ANCOVA et modèle linéaire général</a>
<ul>
<li class="chapter" data-level="8.1" data-path="set-anco.html"><a href="set-anco.html"><i class="fa fa-check"></i><b>8.1</b> R packages and data</a></li>
<li class="chapter" data-level="8.2" data-path="linear-models.html"><a href="linear-models.html"><i class="fa fa-check"></i><b>8.2</b> Linear models</a></li>
<li class="chapter" data-level="8.3" data-path="ancova.html"><a href="ancova.html"><i class="fa fa-check"></i><b>8.3</b> ANCOVA</a></li>
<li class="chapter" data-level="8.4" data-path="homogeneity-of-slopes.html"><a href="homogeneity-of-slopes.html"><i class="fa fa-check"></i><b>8.4</b> Homogeneity of slopes</a>
<ul>
<li class="chapter" data-level="8.4.1" data-path="homogeneity-of-slopes.html"><a href="homogeneity-of-slopes.html#case-1---size-as-a-function-of-age-equal-slopes-example"><i class="fa fa-check"></i><b>8.4.1</b> Case 1 - Size as a function of age (equal slopes example)</a></li>
<li class="chapter" data-level="8.4.2" data-path="homogeneity-of-slopes.html"><a href="homogeneity-of-slopes.html#case-2---size-as-a-function-of-age-different-slopes-example"><i class="fa fa-check"></i><b>8.4.2</b> Case 2 - Size as a function of age (different slopes example)</a></li>
</ul></li>
<li class="chapter" data-level="8.5" data-path="the-ancova-model.html"><a href="the-ancova-model.html"><i class="fa fa-check"></i><b>8.5</b> The ANCOVA model</a></li>
<li class="chapter" data-level="8.6" data-path="comparing-model-fits.html"><a href="comparing-model-fits.html"><i class="fa fa-check"></i><b>8.6</b> Comparing model fits</a></li>
<li class="chapter" data-level="8.7" data-path="bootstrap-1.html"><a href="bootstrap-1.html"><i class="fa fa-check"></i><b>8.7</b> Bootstrap</a></li>
<li class="chapter" data-level="8.8" data-path="permutation-test-2.html"><a href="permutation-test-2.html"><i class="fa fa-check"></i><b>8.8</b> Permutation test</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="analysis-of-frequency-data-contingency-tables-log-linear-models-and-poisson-regression.html"><a href="analysis-of-frequency-data-contingency-tables-log-linear-models-and-poisson-regression.html"><i class="fa fa-check"></i><b>9</b> Analysis of frequency data: Contingency Tables, Log-Linear Models, and Poisson Regression</a>
<ul>
<li class="chapter" data-level="9.1" data-path="set-freq.html"><a href="set-freq.html"><i class="fa fa-check"></i><b>9.1</b> R packages and data</a></li>
<li class="chapter" data-level="9.2" data-path="organizing-the-data-3-forms.html"><a href="organizing-the-data-3-forms.html"><i class="fa fa-check"></i><b>9.2</b> Organizing the data: 3 forms</a></li>
<li class="chapter" data-level="9.3" data-path="graphs-for-contingency-tables-and-testing-for-independence.html"><a href="graphs-for-contingency-tables-and-testing-for-independence.html"><i class="fa fa-check"></i><b>9.3</b> Graphs for contingency tables and testing for independence</a></li>
<li class="chapter" data-level="9.4" data-path="log-linear-models-as-an-alternative-to-chi-square-test-for-contingency-tables.html"><a href="log-linear-models-as-an-alternative-to-chi-square-test-for-contingency-tables.html"><i class="fa fa-check"></i><b>9.4</b> Log-linear models as an alternative to Chi-square test for contingency tables</a></li>
<li class="chapter" data-level="9.5" data-path="testing-an-external-hypothesis.html"><a href="testing-an-external-hypothesis.html"><i class="fa fa-check"></i><b>9.5</b> Testing an external hypothesis</a></li>
<li class="chapter" data-level="9.6" data-path="poisson-regression-to-analyze-multi-way-tables.html"><a href="poisson-regression-to-analyze-multi-way-tables.html"><i class="fa fa-check"></i><b>9.6</b> Poisson regression to analyze multi-way tables</a></li>
<li class="chapter" data-level="9.7" data-path="ex-glm.html"><a href="ex-glm.html"><i class="fa fa-check"></i><b>9.7</b> Exercice</a></li>
</ul></li>
<li class="appendix"><span><b>Appendix</b></span></li>
<li class="chapter" data-level="A" data-path="software-tools.html"><a href="software-tools.html"><i class="fa fa-check"></i><b>A</b> Software Tools</a>
<ul>
<li class="chapter" data-level="A.1" data-path="r-and-r-packages.html"><a href="r-and-r-packages.html"><i class="fa fa-check"></i><b>A.1</b> R and R packages</a></li>
<li class="chapter" data-level="A.2" data-path="pandoc.html"><a href="pandoc.html"><i class="fa fa-check"></i><b>A.2</b> Pandoc</a></li>
<li class="chapter" data-level="A.3" data-path="latex.html"><a href="latex.html"><i class="fa fa-check"></i><b>A.3</b> LaTeX</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://bookdown.org" target="_blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">BIO4158 Applied biostats with R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="one-way-anova-with-multiple-comparisons" class="section level2" number="5.2">
<h2><span class="header-section-number">5.2</span> One-way ANOVA with multiple comparisons</h2>
<p>The one-way ANOVA is the multi-group analog of the <em>t</em>-test, which is used to compare two groups/levels. It makes essentially the same assumptions, and in the case of two groups/levels, is in fact mathematically equivalent to the <em>t</em>-test.</p>
<p>In 1960-1962, the Grand Rapids Dam was built on the Saskatchewan River upstream of Cumberland House. There are anecdotal reports that during dam construction, a number of large sturgeon were stranded and died in shallow pools. Surveys of sturgeon were carried out in 1954, 1958, 1965 and 1966 with fork length (<code>fklngth</code>) and round weight (<code>rdwght</code>) being recorded (not necessarily both measurements for each individual). These data are in the data file <code>Dam10dat.csv</code>.</p>
<div id="visualiser-les-données" class="section level3" number="5.2.1">
<h3><span class="header-section-number">5.2.1</span> Visualiser les données</h3>
<ul>
<li>Using <code>Dam10dat.csv</code>, you must first change the data type of the
numerical variable year , so that R recognizes that we wish to treat this
variable as a factor variable and not a continuous variable.</li>
</ul>
<div class="sourceCode" id="cb168"><pre class="sourceCode r exer"><code class="sourceCode r"><span id="cb168-1"><a href="one-way-anova-with-multiple-comparisons.html#cb168-1" aria-hidden="true"></a>dam10dat &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;data/Dam10dat.csv&quot;</span>)</span>
<span id="cb168-2"><a href="one-way-anova-with-multiple-comparisons.html#cb168-2" aria-hidden="true"></a>dam10dat<span class="op">$</span>year &lt;-<span class="st"> </span><span class="kw">as.factor</span>(dam10dat<span class="op">$</span>year)</span>
<span id="cb168-3"><a href="one-way-anova-with-multiple-comparisons.html#cb168-3" aria-hidden="true"></a><span class="kw">str</span>(dam10dat)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    118 obs. of  21 variables:
##  $ year    : Factor w/ 4 levels &quot;1954&quot;,&quot;1958&quot;,..: 1 1 1 1 1 1 1 1 1 1 ...
##  $ fklngth : num  45 50 39 46 54.5 49 42.5 49 56 54 ...
##  $ totlngth: num  49 NA 43 50.5 NA 51.7 45.5 52 60.2 58.5 ...
##  $ drlngth : logi  NA NA NA NA NA NA ...
##  $ drwght  : num  16 20.5 10 17.5 19.7 21.3 9.5 23.7 31 27.3 ...
##  $ rdwght  : num  24.5 33 15.5 28.5 32.5 35.5 15.3 40.5 51.5 43 ...
##  $ sex     : int  1 1 1 2 1 2 1 1 1 1 ...
##  $ age     : int  24 33 17 31 37 44 23 34 33 47 ...
##  $ lfkl    : num  1.65 1.7 1.59 1.66 1.74 ...
##  $ ltotl   : num  1.69 NA 1.63 1.7 NA ...
##  $ ldrl    : logi  NA NA NA NA NA NA ...
##  $ ldrwght : num  1.2 1.31 1 1.24 1.29 ...
##  $ lrdwght : num  1.39 1.52 1.19 1.45 1.51 ...
##  $ lage    : num  1.38 1.52 1.23 1.49 1.57 ...
##  $ rage    : int  4 6 3 6 7 7 4 6 6 7 ...
##  $ ryear   : int  1954 1954 1954 1954 1954 1954 1954 1954 1954 1954 ...
##  $ ryear2  : int  1958 1958 1958 1958 1958 1958 1958 1958 1958 1958 ...
##  $ ryear3  : int  1966 1966 1966 1966 1966 1966 1966 1966 1966 1966 ...
##  $ location: int  1 1 1 1 1 1 1 1 1 1 ...
##  $ girth   : logi  NA NA NA NA NA NA ...
##  $ lgirth  : logi  NA NA NA NA NA NA ...</code></pre>
<ul>
<li>Next, have a look at the fklngth data, just as we did in the last lab for t-tests. Create a histogram with density line grouped by year to get a feel for what’s happening with your data and a boxplot of length per year. What can you say about these data?</li>
</ul>
<div class="sourceCode" id="cb170"><pre class="sourceCode r exer"><code class="sourceCode r"><span id="cb170-1"><a href="one-way-anova-with-multiple-comparisons.html#cb170-1" aria-hidden="true"></a>mygraph &lt;-<span class="st"> </span><span class="kw">ggplot</span>(dam10dat, <span class="kw">aes</span>(<span class="dt">x =</span> fklngth)) <span class="op">+</span></span>
<span id="cb170-2"><a href="one-way-anova-with-multiple-comparisons.html#cb170-2" aria-hidden="true"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Fork length (cm)&quot;</span>) <span class="op">+</span></span>
<span id="cb170-3"><a href="one-way-anova-with-multiple-comparisons.html#cb170-3" aria-hidden="true"></a><span class="st">  </span><span class="kw">geom_density</span>() <span class="op">+</span></span>
<span id="cb170-4"><a href="one-way-anova-with-multiple-comparisons.html#cb170-4" aria-hidden="true"></a><span class="st">  </span><span class="kw">geom_rug</span>() <span class="op">+</span></span>
<span id="cb170-5"><a href="one-way-anova-with-multiple-comparisons.html#cb170-5" aria-hidden="true"></a><span class="st">  </span><span class="kw">geom_histogram</span>(<span class="kw">aes</span>(<span class="dt">y =</span> ..density..),</span>
<span id="cb170-6"><a href="one-way-anova-with-multiple-comparisons.html#cb170-6" aria-hidden="true"></a>    <span class="dt">color =</span> <span class="st">&quot;black&quot;</span>,</span>
<span id="cb170-7"><a href="one-way-anova-with-multiple-comparisons.html#cb170-7" aria-hidden="true"></a>    <span class="dt">alpha =</span> <span class="fl">0.3</span></span>
<span id="cb170-8"><a href="one-way-anova-with-multiple-comparisons.html#cb170-8" aria-hidden="true"></a>  ) <span class="op">+</span></span>
<span id="cb170-9"><a href="one-way-anova-with-multiple-comparisons.html#cb170-9" aria-hidden="true"></a><span class="st">  </span><span class="kw">stat_function</span>(</span>
<span id="cb170-10"><a href="one-way-anova-with-multiple-comparisons.html#cb170-10" aria-hidden="true"></a>    <span class="dt">fun =</span> dnorm,</span>
<span id="cb170-11"><a href="one-way-anova-with-multiple-comparisons.html#cb170-11" aria-hidden="true"></a>    <span class="dt">args =</span> <span class="kw">list</span>(</span>
<span id="cb170-12"><a href="one-way-anova-with-multiple-comparisons.html#cb170-12" aria-hidden="true"></a>      <span class="dt">mean =</span> <span class="kw">mean</span>(dam10dat<span class="op">$</span>fklngth),</span>
<span id="cb170-13"><a href="one-way-anova-with-multiple-comparisons.html#cb170-13" aria-hidden="true"></a>      <span class="dt">sd =</span> <span class="kw">sd</span>(dam10dat<span class="op">$</span>fklngth)</span>
<span id="cb170-14"><a href="one-way-anova-with-multiple-comparisons.html#cb170-14" aria-hidden="true"></a>    ),</span>
<span id="cb170-15"><a href="one-way-anova-with-multiple-comparisons.html#cb170-15" aria-hidden="true"></a>    <span class="dt">color =</span> <span class="st">&quot;red&quot;</span></span>
<span id="cb170-16"><a href="one-way-anova-with-multiple-comparisons.html#cb170-16" aria-hidden="true"></a>  )</span>
<span id="cb170-17"><a href="one-way-anova-with-multiple-comparisons.html#cb170-17" aria-hidden="true"></a></span>
<span id="cb170-18"><a href="one-way-anova-with-multiple-comparisons.html#cb170-18" aria-hidden="true"></a><span class="co"># display graph, by year</span></span>
<span id="cb170-19"><a href="one-way-anova-with-multiple-comparisons.html#cb170-19" aria-hidden="true"></a>mygraph <span class="op">+</span><span class="st"> </span><span class="kw">facet_wrap</span>(<span class="op">~</span>year, <span class="dt">ncol =</span> <span class="dv">2</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:ano-2"></span>
<img src="Labs_BIO4158_files/figure-html/ano-2-1.svg" alt="Distribution of sturgeon length per year" width="672" />
<p class="caption">
Figure 5.1: Distribution of sturgeon length per year
</p>
</div>
<div class="sourceCode" id="cb171"><pre class="sourceCode r exer"><code class="sourceCode r"><span id="cb171-1"><a href="one-way-anova-with-multiple-comparisons.html#cb171-1" aria-hidden="true"></a><span class="kw">boxplot</span>(fklngth <span class="op">~</span><span class="st"> </span>year, <span class="dt">data =</span> dam10dat)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-38"></span>
<img src="Labs_BIO4158_files/figure-html/unnamed-chunk-38-1.svg" alt="Boxplot of sturgeon length per year" width="672" />
<p class="caption">
Figure 5.2: Boxplot of sturgeon length per year
</p>
</div>
<p>It appears as though there may have been a small drop in <code>fklngth</code> after the construction of the dam, but the data are variable and the effects are not clear. There might also be some problems with normality in the 1954 and 1966 samples, and it looks as though there are outliers in the 1958 and 1966 samples. Let’s proceed with testing the assumptions of the ANOVA by running the analysis and looking at the residuals.</p>
</div>
<div id="testing-the-assumptions-of-a-parametric-anova" class="section level3" number="5.2.2">
<h3><span class="header-section-number">5.2.2</span> Testing the assumptions of a parametric ANOVA</h3>
<p>Parametric one-way ANOVAs have three major assumptions:</p>
<ol style="list-style-type: decimal">
<li>the residuals are normally distributed</li>
<li>the error variance is the same for all groups (homoscedasticity)</li>
<li>the residuals are independent.</li>
</ol>
<p>These assumptions must be tested before we can accept the results of any parametric ANOVA.</p>
<ul>
<li>Carry out a one-way ANOVA on fklngth by year and produce the residual diagnostic plots</li>
</ul>
<div class="sourceCode" id="cb172"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb172-1"><a href="one-way-anova-with-multiple-comparisons.html#cb172-1" aria-hidden="true"></a><span class="co"># Fit anova model and plot residual diagnostics</span></span>
<span id="cb172-2"><a href="one-way-anova-with-multiple-comparisons.html#cb172-2" aria-hidden="true"></a>anova.model1 &lt;-<span class="st"> </span><span class="kw">lm</span>(fklngth <span class="op">~</span><span class="st"> </span>year, <span class="dt">data =</span> dam10dat)</span>
<span id="cb172-3"><a href="one-way-anova-with-multiple-comparisons.html#cb172-3" aria-hidden="true"></a><span class="kw">par</span>(<span class="dt">mfrow =</span> <span class="kw">c</span>(<span class="dv">2</span>, <span class="dv">2</span>))</span>
<span id="cb172-4"><a href="one-way-anova-with-multiple-comparisons.html#cb172-4" aria-hidden="true"></a><span class="kw">plot</span>(anova.model1)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:ano-3"></span>
<img src="Labs_BIO4158_files/figure-html/ano-3-1.svg" alt="Diagnostic plots for a one-way ANOVA" width="672" />
<p class="caption">
Figure 5.3: Diagnostic plots for a one-way ANOVA
</p>
</div>

<div class="rmdwarning">
<p>Double check that the independent variable is a <strong>factor</strong>. If the dependent variable is a <strong>character</strong>, then you will obtain only 3 graphs and an error message like:</p>
<p>`hat values (leverages) are all = 0.1</p>
and there are no factor predictors; no plot no. 5`
</div>
<p>D’après les graphiques, on peut douter de la normalité et de l’homogénéité des variances. Judging from the plots, it looks as though there may be problems with both normality and variance heterogeneity. Note that there is one point (case 59) with large expected values and a large residual that appear to lie well off the line: this is the outlier we noted earlier. This point might be expected to inflate the variance for the group it belongs to. Formal tests may also provide some insight as to whether we should be concerned about normality and variance heterogeneity.</p>
<ul>
<li>Perform a normality test on the residuals from the ANOVA.</li>
</ul>
<div class="sourceCode" id="cb173"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb173-1"><a href="one-way-anova-with-multiple-comparisons.html#cb173-1" aria-hidden="true"></a><span class="kw">shapiro.test</span>(<span class="kw">residuals</span>(anova.model1))</span></code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  residuals(anova.model1)
## W = 0.91571, p-value = 1.63e-06</code></pre>
<p>This test confirms our suspicions from the probability plot: the residuals are not normally distributed. Recall, however, that the power here is high, so only small deviations from normality are required to reject the null.</p>
<ul>
<li>Next, test for homoscedasticity:</li>
</ul>
<div class="sourceCode" id="cb175"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb175-1"><a href="one-way-anova-with-multiple-comparisons.html#cb175-1" aria-hidden="true"></a><span class="kw">leveneTest</span>(fklngth <span class="op">~</span><span class="st"> </span>year, <span class="dt">data =</span> dam10dat)</span></code></pre></div>
<pre><code>## Levene&#39;s Test for Homogeneity of Variance (center = median)
##        Df F value  Pr(&gt;F)  
## group   3  2.8159 0.04234 *
##       114                  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>The probability value tells you that you can reject the null hypothesis that there is no difference in variances among years. Thus, we conclude there is evidence that the variances in the groups are not equal.</p>
</div>
<div id="performing-the-anova" class="section level3" number="5.2.3">
<h3><span class="header-section-number">5.2.3</span> Performing the ANOVA</h3>
<p>Let’s look at the results of the ANOVA, assuming for the moment that assumptions are met well enough.</p>
<div class="sourceCode" id="cb177"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb177-1"><a href="one-way-anova-with-multiple-comparisons.html#cb177-1" aria-hidden="true"></a><span class="kw">summary</span>(anova.model1)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = fklngth ~ year, data = dam10dat)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -11.2116  -2.6866  -0.7116   2.2103  26.7885 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  48.0243     0.8566  56.061  &lt; 2e-16 ***
## year1958      0.1872     1.3335   0.140  0.88859    
## year1965     -5.5077     1.7310  -3.182  0.00189 ** 
## year1966     -3.3127     1.1684  -2.835  0.00542 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 5.211 on 114 degrees of freedom
## Multiple R-squared:  0.1355, Adjusted R-squared:  0.1128 
## F-statistic: 5.957 on 3 and 114 DF,  p-value: 0.0008246</code></pre>
<ul>
<li><em>Coefficients: Estimates</em> Note the 4 coefficients printed. They can be used to obtain the predicted values for the model (i.e. the group means). The mean fklngth for the first year (1954) is 48.0243. The coefficients for the 3 other years are the difference between the mean for that year and for 1954. So, the mean for 1965 is (48.0243-5.5077=42.5166). For each estimated coefficient, there is a standard error, a t-value and associated probability (for H0 that the coefficient is 0). Note here that coefficients for 1965 and 1966 are both negative and significantly less than 0. Fish were smaller after the construction of the dam than in 1954. Take these p-values with a grain of salt: these are not corrected for multiple comparisons, and they constitute only a subset of the possible comparisons. In general, I pay little attention to this part of the output and look more at what comes next.</li>
<li><em>Residual standard error</em>: The square root of the variance of the residuals (observed minus fitted values) corresponds to the amount of variability that is unexplained by the models (here an estimate of how much size varied among fish, once corrected for differences among years)</li>
<li><em>Mutiple R-squared</em> The R-squared is the proportion of the variance of the dependent variable that can be explained by the model. Here the model explains only 13.5% of the variability. Size differences among year are relatively small compared to the ranges of sizes that can occur within years. This corresponds well to the visual impression left by the histograms of <code>fklngth</code> per <code>year</code></li>
</ul>
<ol start="4" style="list-style-type: decimal">
<li><em>F-Statistic</em> This is the p-value for the “omnibus” test, the test that all means are equal. Here it is much smaller than 0.05 and hence we would reject H0 and conclude that fklngth varies among the years</li>
</ol>
<p>The <code>anova()</code> command produces the standard ANOVA table that contains most of the same information:</p>
<div class="sourceCode" id="cb179"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb179-1"><a href="one-way-anova-with-multiple-comparisons.html#cb179-1" aria-hidden="true"></a><span class="kw">anova</span>(anova.model1)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: fklngth
##            Df  Sum Sq Mean Sq F value    Pr(&gt;F)    
## year        3  485.26 161.755  5.9574 0.0008246 ***
## Residuals 114 3095.30  27.152                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>The total variability in fklngth sums of square is partitioned into what can be accounted for by year (485.26) and what is left unexplained as residual variability (3095.30). Year indeed explains <span class="math inline">\((485.26/(3095.30+485.26)=.1355\)</span> or 13.55% of the variability). The mean square of the residuals is their variance.</p>
</div>
<div id="performing-multiple-comparisons-of-means-test" class="section level3" number="5.2.4">
<h3><span class="header-section-number">5.2.4</span> Performing multiple comparisons of means test</h3>
<ul>
<li>The <code>pairwise.t.test()</code> function can be used to compare means and adjust (or not) probabilities for multiple comparisons by choosing one of the options for the argument <code>p.adj</code>:</li>
</ul>
<p>Comparing all means without corrections for multiple comparisons.</p>
<div class="sourceCode" id="cb181"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb181-1"><a href="one-way-anova-with-multiple-comparisons.html#cb181-1" aria-hidden="true"></a><span class="kw">pairwise.t.test</span>(dam10dat<span class="op">$</span>fklngth, dam10dat<span class="op">$</span>year,</span>
<span id="cb181-2"><a href="one-way-anova-with-multiple-comparisons.html#cb181-2" aria-hidden="true"></a>  <span class="dt">p.adj =</span> <span class="st">&quot;none&quot;</span></span>
<span id="cb181-3"><a href="one-way-anova-with-multiple-comparisons.html#cb181-3" aria-hidden="true"></a>)</span></code></pre></div>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  dam10dat$fklngth and dam10dat$year 
## 
##      1954   1958   1965  
## 1958 0.8886 -      -     
## 1965 0.0019 0.0022 -     
## 1966 0.0054 0.0079 0.1996
## 
## P value adjustment method: none</code></pre>
<p>Option <code>"bonf"</code> adjusts the p-values according to the Bonferroni correction. In this case, since there are 6 p-values calculated, it amounts to simply multiplying the uncorrected p-values by 6 (unless the result is above 1, in that case the adjusted p-value is 1).</p>
<div class="sourceCode" id="cb183"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb183-1"><a href="one-way-anova-with-multiple-comparisons.html#cb183-1" aria-hidden="true"></a><span class="kw">pairwise.t.test</span>(dam10dat<span class="op">$</span>fklngth, dam10dat<span class="op">$</span>year,</span>
<span id="cb183-2"><a href="one-way-anova-with-multiple-comparisons.html#cb183-2" aria-hidden="true"></a>  <span class="dt">p.adj =</span> <span class="st">&quot;bonf&quot;</span></span>
<span id="cb183-3"><a href="one-way-anova-with-multiple-comparisons.html#cb183-3" aria-hidden="true"></a>)</span></code></pre></div>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  dam10dat$fklngth and dam10dat$year 
## 
##      1954  1958  1965 
## 1958 1.000 -     -    
## 1965 0.011 0.013 -    
## 1966 0.033 0.047 1.000
## 
## P value adjustment method: bonferroni</code></pre>
<p>Option <code>"holm"</code> is the sequential Bonferroni correction, where the p-values are ranked from (i=1) smallest to (N) largest. The correction factor for p-values is then $<span class="math inline">\((N-i+1)\)</span>. Here, for example, we have N=6 pairs that are compared. The lowest uncorrected p-value is 0.0019 for 1954 vs 1965. The corrected p-value becomes <span class="math inline">\(0.0019*(6-1+1)= 0.011\)</span>. The second lowest p-value is 0.0022. The corrected p/value is therefore <span class="math inline">\(0.0022*(6-2+1)=0.011\)</span>. For the highest p-value, the correction is <span class="math inline">\((N-N+1)=1\)</span>, hence it is equal to the uncorrected probability.</p>
<div class="sourceCode" id="cb185"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb185-1"><a href="one-way-anova-with-multiple-comparisons.html#cb185-1" aria-hidden="true"></a><span class="kw">pairwise.t.test</span>(dam10dat<span class="op">$</span>fklngth, dam10dat<span class="op">$</span>year,</span>
<span id="cb185-2"><a href="one-way-anova-with-multiple-comparisons.html#cb185-2" aria-hidden="true"></a>  <span class="dt">p.adj =</span> <span class="st">&quot;holm&quot;</span></span>
<span id="cb185-3"><a href="one-way-anova-with-multiple-comparisons.html#cb185-3" aria-hidden="true"></a>)</span></code></pre></div>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  dam10dat$fklngth and dam10dat$year 
## 
##      1954  1958  1965 
## 1958 0.889 -     -    
## 1965 0.011 0.011 -    
## 1966 0.022 0.024 0.399
## 
## P value adjustment method: holm</code></pre>
<p>The “fdr” option is for controlling the false discovery rate.</p>
<div class="sourceCode" id="cb187"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb187-1"><a href="one-way-anova-with-multiple-comparisons.html#cb187-1" aria-hidden="true"></a><span class="kw">pairwise.t.test</span>(dam10dat<span class="op">$</span>fklngth, dam10dat<span class="op">$</span>year,</span>
<span id="cb187-2"><a href="one-way-anova-with-multiple-comparisons.html#cb187-2" aria-hidden="true"></a>  <span class="dt">p.adj =</span> <span class="st">&quot;fdr&quot;</span></span>
<span id="cb187-3"><a href="one-way-anova-with-multiple-comparisons.html#cb187-3" aria-hidden="true"></a>)</span></code></pre></div>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  dam10dat$fklngth and dam10dat$year 
## 
##      1954   1958   1965  
## 1958 0.8886 -      -     
## 1965 0.0066 0.0066 -     
## 1966 0.0108 0.0119 0.2395
## 
## P value adjustment method: fdr</code></pre>
<p>The four post-hoc tests here tell us the same thing: differences are all between two groups of years: 1954/58 and 1965/66, since all comparisons show differences between the 50’s and 60’s but no differences within the 50’s or 60’s. So, in this particular case, the conclusion is not affected by the choice of adjustment method. But in other situations, you will observe contradictory results.</p>
<p>Which one to choose? Unadjusted p-values are certainly suspect when there are multiple tests. On the other hand, the traditional <em>Bonferroni</em> correction is very conservative, and becomes even more so when there are a large number of comparisons. Recent work suggest that the <em>fdr</em> approach may be a good compromise when there are a lot of comparisons. The <em>Tukey</em> method of multiple comparisons is one of the most popular and is easily performed with R (note, however, that there is a pesky bug that manifests itself when the independent variable can look like a number rather than a factor, hence the little pirouette with <code>paste0()</code> to add a letter <code>m</code> before the first digit):</p>
<div class="sourceCode" id="cb189"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb189-1"><a href="one-way-anova-with-multiple-comparisons.html#cb189-1" aria-hidden="true"></a>dam10dat<span class="op">$</span>myyear &lt;-<span class="st"> </span><span class="kw">as.factor</span>(<span class="kw">paste0</span>(<span class="st">&quot;m&quot;</span>, dam10dat<span class="op">$</span>year))</span>
<span id="cb189-2"><a href="one-way-anova-with-multiple-comparisons.html#cb189-2" aria-hidden="true"></a><span class="kw">TukeyHSD</span>(<span class="kw">aov</span>(fklngth <span class="op">~</span><span class="st"> </span>myyear, <span class="dt">data =</span> dam10dat))</span></code></pre></div>
<pre><code>##   Tukey multiple comparisons of means
##     95% family-wise confidence level
## 
## Fit: aov(formula = fklngth ~ myyear, data = dam10dat)
## 
## $myyear
##                   diff        lwr        upr     p adj
## m1958-m1954  0.1872141  -3.289570  3.6639986 0.9990071
## m1965-m1954 -5.5076577 -10.021034 -0.9942809 0.0100528
## m1966-m1954 -3.3126964  -6.359223 -0.2661701 0.0274077
## m1965-m1958 -5.6948718 -10.436304 -0.9534397 0.0116943
## m1966-m1958 -3.4999106  -6.875104 -0.1247171 0.0390011
## m1966-m1965  2.1949612  -2.240630  6.6305526 0.5710111</code></pre>
<div class="sourceCode" id="cb191"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb191-1"><a href="one-way-anova-with-multiple-comparisons.html#cb191-1" aria-hidden="true"></a><span class="kw">par</span>(<span class="dt">mar =</span> <span class="kw">c</span>(<span class="dv">4</span>, <span class="dv">7</span>, <span class="dv">2</span>, <span class="dv">1</span>))</span>
<span id="cb191-2"><a href="one-way-anova-with-multiple-comparisons.html#cb191-2" aria-hidden="true"></a><span class="kw">plot</span>(<span class="kw">TukeyHSD</span>(<span class="kw">aov</span>(fklngth <span class="op">~</span><span class="st"> </span>myyear, <span class="dt">data =</span> dam10dat)), <span class="dt">las =</span> <span class="dv">2</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:ano-13"></span>
<img src="Labs_BIO4158_files/figure-html/ano-13-1.svg" alt="Inter-annual differences in sturgeon length" width="672" />
<p class="caption">
Figure 5.4: Inter-annual differences in sturgeon length
</p>
</div>
<p>The confidence intervals, corrected for multiple tests by the Tukey method, are plotted for differences among years. Unfortunately, the labels are not all printed because they would overlap, but the order is the same as in the preceding table. The <code>multcomp</code> 📦 can produce a better plot version, but requires a bit more code:</p>
<div class="sourceCode" id="cb192"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb192-1"><a href="one-way-anova-with-multiple-comparisons.html#cb192-1" aria-hidden="true"></a><span class="co"># Alternative way to compute Tukey multiple comparisons</span></span>
<span id="cb192-2"><a href="one-way-anova-with-multiple-comparisons.html#cb192-2" aria-hidden="true"></a><span class="co"># set up a one-way ANOVA</span></span>
<span id="cb192-3"><a href="one-way-anova-with-multiple-comparisons.html#cb192-3" aria-hidden="true"></a>anova_fkl_year &lt;-<span class="st"> </span><span class="kw">aov</span>(fklngth <span class="op">~</span><span class="st"> </span>myyear, <span class="dt">data =</span> dam10dat)</span>
<span id="cb192-4"><a href="one-way-anova-with-multiple-comparisons.html#cb192-4" aria-hidden="true"></a><span class="co"># set up all-pairs comparisons for factor `year&#39;</span></span>
<span id="cb192-5"><a href="one-way-anova-with-multiple-comparisons.html#cb192-5" aria-hidden="true"></a></span>
<span id="cb192-6"><a href="one-way-anova-with-multiple-comparisons.html#cb192-6" aria-hidden="true"></a>meandiff &lt;-<span class="st"> </span><span class="kw">glht</span>(anova_fkl_year, <span class="dt">linfct =</span> <span class="kw">mcp</span>(</span>
<span id="cb192-7"><a href="one-way-anova-with-multiple-comparisons.html#cb192-7" aria-hidden="true"></a>  <span class="dt">myyear =</span></span>
<span id="cb192-8"><a href="one-way-anova-with-multiple-comparisons.html#cb192-8" aria-hidden="true"></a>    <span class="st">&quot;Tukey&quot;</span></span>
<span id="cb192-9"><a href="one-way-anova-with-multiple-comparisons.html#cb192-9" aria-hidden="true"></a>))</span>
<span id="cb192-10"><a href="one-way-anova-with-multiple-comparisons.html#cb192-10" aria-hidden="true"></a><span class="kw">confint</span>(meandiff)</span></code></pre></div>
<pre><code>## 
##   Simultaneous Confidence Intervals
## 
## Multiple Comparisons of Means: Tukey Contrasts
## 
## 
## Fit: aov(formula = fklngth ~ myyear, data = dam10dat)
## 
## Quantile = 2.5936
## 95% family-wise confidence level
##  
## 
## Linear Hypotheses:
##                    Estimate lwr      upr     
## m1958 - m1954 == 0   0.1872  -3.2713   3.6457
## m1965 - m1954 == 0  -5.5077  -9.9973  -1.0181
## m1966 - m1954 == 0  -3.3127  -6.3432  -0.2822
## m1965 - m1958 == 0  -5.6949 -10.4113  -0.9784
## m1966 - m1958 == 0  -3.4999  -6.8573  -0.1425
## m1966 - m1965 == 0   2.1950  -2.2173   6.6072</code></pre>
<div class="sourceCode" id="cb194"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb194-1"><a href="one-way-anova-with-multiple-comparisons.html#cb194-1" aria-hidden="true"></a><span class="kw">par</span>(<span class="dt">mar =</span> <span class="kw">c</span>(<span class="dv">5</span>, <span class="dv">7</span>, <span class="dv">2</span>, <span class="dv">1</span>))</span>
<span id="cb194-2"><a href="one-way-anova-with-multiple-comparisons.html#cb194-2" aria-hidden="true"></a><span class="kw">plot</span>(meandiff)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:ano-14"></span>
<img src="Labs_BIO4158_files/figure-html/ano-14-1.svg" alt="Inter-annual differences in sturgeon length" width="672" />
<p class="caption">
Figure 5.5: Inter-annual differences in sturgeon length
</p>
</div>
<p>This is better. Also useful is a plot the means and their confidence intervals with the Tukey groupings shown as letters above:</p>
<div class="sourceCode" id="cb195"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb195-1"><a href="one-way-anova-with-multiple-comparisons.html#cb195-1" aria-hidden="true"></a><span class="co"># Compute and plot means and Tukey CI</span></span>
<span id="cb195-2"><a href="one-way-anova-with-multiple-comparisons.html#cb195-2" aria-hidden="true"></a>means &lt;-<span class="st"> </span><span class="kw">glht</span>(</span>
<span id="cb195-3"><a href="one-way-anova-with-multiple-comparisons.html#cb195-3" aria-hidden="true"></a>  anova_fkl_year,</span>
<span id="cb195-4"><a href="one-way-anova-with-multiple-comparisons.html#cb195-4" aria-hidden="true"></a>  <span class="dt">linfct =</span> <span class="kw">mcp</span>(<span class="dt">myyear =</span> <span class="st">&quot;Tukey&quot;</span>)</span>
<span id="cb195-5"><a href="one-way-anova-with-multiple-comparisons.html#cb195-5" aria-hidden="true"></a>)</span>
<span id="cb195-6"><a href="one-way-anova-with-multiple-comparisons.html#cb195-6" aria-hidden="true"></a>cimeans &lt;-<span class="st"> </span><span class="kw">cld</span>(means)</span>
<span id="cb195-7"><a href="one-way-anova-with-multiple-comparisons.html#cb195-7" aria-hidden="true"></a><span class="co"># use sufficiently large upper margin</span></span>
<span id="cb195-8"><a href="one-way-anova-with-multiple-comparisons.html#cb195-8" aria-hidden="true"></a><span class="co"># plot</span></span>
<span id="cb195-9"><a href="one-way-anova-with-multiple-comparisons.html#cb195-9" aria-hidden="true"></a>old_par &lt;-<span class="st"> </span><span class="kw">par</span>(<span class="dt">mai =</span> <span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">1</span>, <span class="fl">1.25</span>, <span class="dv">1</span>))</span>
<span id="cb195-10"><a href="one-way-anova-with-multiple-comparisons.html#cb195-10" aria-hidden="true"></a><span class="kw">plot</span>(cimeans)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:ano-15"></span>
<img src="Labs_BIO4158_files/figure-html/ano-15-1.svg" alt="Inter-annual differences in sturgeon length" width="672" />
<p class="caption">
Figure 5.6: Inter-annual differences in sturgeon length
</p>
</div>
<p>Note the letters appearing on top. Years labelled with the same letter do not differ significantly.</p>
</div>
</div>
<script src="js/solution.js"></script>
            </section>

          </div>
        </div>
      </div>
<a href="set-ano.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="data-transformations-and-non-parametric-anova.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": false,
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/Bio4158-4558-uottawa/lab_manual/edit/master/05-anova.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["Labs_BIO4158.pdf", "Labs_BIO4158.epub", "Labs_BIO4158.mobi"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
