<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>2.4 Power analysis for a t-test on two independent means | BIO4158 Applied biostats with R</title>
  <meta name="description" content="Laboratory manual for BIO4158 Applied biostatistics" />
  <meta name="generator" content="bookdown 0.35 and GitBook 2.6.7" />

  <meta property="og:title" content="2.4 Power analysis for a t-test on two independent means | BIO4158 Applied biostats with R" />
  <meta property="og:type" content="book" />
  <meta property="og:image" content="/images/missing.png" />
  <meta property="og:description" content="Laboratory manual for BIO4158 Applied biostatistics" />
  <meta name="github-repo" content="Bio4158-4558-uottawa/lab_manual/" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="2.4 Power analysis for a t-test on two independent means | BIO4158 Applied biostats with R" />
  
  <meta name="twitter:description" content="Laboratory manual for BIO4158 Applied biostatistics" />
  <meta name="twitter:image" content="/images/missing.png" />

<meta name="author" content="Julien Martin" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="how-to-use-gpower.html"/>
<link rel="next" href="important-points-to-remember.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>
<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="css/style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">BIO4158 Laboratory manual</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Note</a></li>
<li class="chapter" data-level="" data-path="preface.html"><a href="preface.html"><i class="fa fa-check"></i>Preface</a>
<ul>
<li class="chapter" data-level="" data-path="general-points-to-keep-in-mind.html"><a href="general-points-to-keep-in-mind.html"><i class="fa fa-check"></i>General points to keep in mind</a></li>
<li class="chapter" data-level="" data-path="what-is-r-and-why-use-it-in-this-course.html"><a href="what-is-r-and-why-use-it-in-this-course.html"><i class="fa fa-check"></i>What is R and why use it in this course?</a></li>
<li class="chapter" data-level="" data-path="software-installation.html"><a href="software-installation.html"><i class="fa fa-check"></i>Software installation</a>
<ul>
<li class="chapter" data-level="" data-path="software-installation.html"><a href="software-installation.html#r"><i class="fa fa-check"></i>R</a></li>
<li class="chapter" data-level="" data-path="software-installation.html"><a href="software-installation.html#rstudio-or-vs-code"><i class="fa fa-check"></i>Rstudio or VS code</a></li>
<li class="chapter" data-level="" data-path="software-installation.html"><a href="software-installation.html#r-libraries"><i class="fa fa-check"></i>R libraries</a></li>
<li class="chapter" data-level="" data-path="software-installation.html"><a href="software-installation.html#gpower"><i class="fa fa-check"></i>G*Power</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="general-laboratory-instructions.html"><a href="general-laboratory-instructions.html"><i class="fa fa-check"></i>General laboratory instructions</a></li>
<li class="chapter" data-level="" data-path="notes-about-the-manual.html"><a href="notes-about-the-manual.html"><i class="fa fa-check"></i>Notes about the manual</a>
<ul>
<li class="chapter" data-level="" data-path="notes-about-the-manual.html"><a href="notes-about-the-manual.html#resources"><i class="fa fa-check"></i>Resources</a></li>
<li class="chapter" data-level="" data-path="notes-about-the-manual.html"><a href="notes-about-the-manual.html#license"><i class="fa fa-check"></i>License</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="1" data-path="introduction-to-r.html"><a href="introduction-to-r.html"><i class="fa fa-check"></i><b>1</b> Introduction to R</a>
<ul>
<li class="chapter" data-level="1.1" data-path="set-intro.html"><a href="set-intro.html"><i class="fa fa-check"></i><b>1.1</b> Packages and data needed for the lab</a></li>
<li class="chapter" data-level="1.2" data-path="importing-and-exporting-data.html"><a href="importing-and-exporting-data.html"><i class="fa fa-check"></i><b>1.2</b> Importing and exporting data</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="importing-and-exporting-data.html"><a href="importing-and-exporting-data.html#working-directory"><i class="fa fa-check"></i><b>1.2.1</b> Working directory</a></li>
<li class="chapter" data-level="1.2.2" data-path="importing-and-exporting-data.html"><a href="importing-and-exporting-data.html#opening-a-.rdata-file"><i class="fa fa-check"></i><b>1.2.2</b> Opening a <code>.Rdata</code> file</a></li>
<li class="chapter" data-level="1.2.3" data-path="importing-and-exporting-data.html"><a href="importing-and-exporting-data.html#open-a-.csv-file"><i class="fa fa-check"></i><b>1.2.3</b> Open a <code>.csv</code> file</a></li>
<li class="chapter" data-level="1.2.4" data-path="importing-and-exporting-data.html"><a href="importing-and-exporting-data.html#entering-data-in-r"><i class="fa fa-check"></i><b>1.2.4</b> Entering data in R</a></li>
<li class="chapter" data-level="1.2.5" data-path="importing-and-exporting-data.html"><a href="importing-and-exporting-data.html#cleaning-up-correcting-data"><i class="fa fa-check"></i><b>1.2.5</b> Cleaning up / correcting data</a></li>
<li class="chapter" data-level="1.2.6" data-path="importing-and-exporting-data.html"><a href="importing-and-exporting-data.html#exporting-data-from-r"><i class="fa fa-check"></i><b>1.2.6</b> Exporting data from R</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="preliminary-examination-of-data.html"><a href="preliminary-examination-of-data.html"><i class="fa fa-check"></i><b>1.3</b> Preliminary examination of data</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="preliminary-examination-of-data.html"><a href="preliminary-examination-of-data.html#summary-statistics"><i class="fa fa-check"></i><b>1.3.1</b> Summary statistics</a></li>
<li class="chapter" data-level="1.3.2" data-path="preliminary-examination-of-data.html"><a href="preliminary-examination-of-data.html#histogram-empirical-probability-density-boxplot-and-visual-assessment-of-normality"><i class="fa fa-check"></i><b>1.3.2</b> Histogram, empirical probability density, boxplot, and visual assessment of normality</a></li>
<li class="chapter" data-level="1.3.3" data-path="preliminary-examination-of-data.html"><a href="preliminary-examination-of-data.html#scatterplots"><i class="fa fa-check"></i><b>1.3.3</b> Scatterplots</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="creating-data-subsets.html"><a href="creating-data-subsets.html"><i class="fa fa-check"></i><b>1.4</b> Creating data subsets</a></li>
<li class="chapter" data-level="1.5" data-path="data-transformation.html"><a href="data-transformation.html"><i class="fa fa-check"></i><b>1.5</b> Data transformation</a></li>
<li class="chapter" data-level="1.6" data-path="exercice.html"><a href="exercice.html"><i class="fa fa-check"></i><b>1.6</b> Exercice</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="power-analysis-with-r-and-gpower.html"><a href="power-analysis-with-r-and-gpower.html"><i class="fa fa-check"></i><b>2</b> Power Analysis with R and G*Power</a>
<ul>
<li class="chapter" data-level="2.1" data-path="the-theory.html"><a href="the-theory.html"><i class="fa fa-check"></i><b>2.1</b> The theory</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="the-theory.html"><a href="the-theory.html#what-is-power"><i class="fa fa-check"></i><b>2.1.1</b> What is power?</a></li>
<li class="chapter" data-level="2.1.2" data-path="the-theory.html"><a href="the-theory.html#why-do-a-power-analysis"><i class="fa fa-check"></i><b>2.1.2</b> Why do a power analysis?</a></li>
<li class="chapter" data-level="2.1.3" data-path="the-theory.html"><a href="the-theory.html#factors-affecting-power"><i class="fa fa-check"></i><b>2.1.3</b> Factors affecting power</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="what-is-gpower.html"><a href="what-is-gpower.html"><i class="fa fa-check"></i><b>2.2</b> What is G*Power?</a></li>
<li class="chapter" data-level="2.3" data-path="how-to-use-gpower.html"><a href="how-to-use-gpower.html"><i class="fa fa-check"></i><b>2.3</b> How to use G*Power</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="how-to-use-gpower.html"><a href="how-to-use-gpower.html#general-principle"><i class="fa fa-check"></i><b>2.3.1</b> General Principle</a></li>
<li class="chapter" data-level="2.3.2" data-path="how-to-use-gpower.html"><a href="how-to-use-gpower.html#types-of-power-analyses"><i class="fa fa-check"></i><b>2.3.2</b> Types of power analyses</a></li>
<li class="chapter" data-level="2.3.3" data-path="how-to-use-gpower.html"><a href="how-to-use-gpower.html#how-to-calculate-effect-size"><i class="fa fa-check"></i><b>2.3.3</b> How to calculate effect size</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="power-analysis-for-a-t-test-on-two-independent-means.html"><a href="power-analysis-for-a-t-test-on-two-independent-means.html"><i class="fa fa-check"></i><b>2.4</b> Power analysis for a t-test on two independent means</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="power-analysis-for-a-t-test-on-two-independent-means.html"><a href="power-analysis-for-a-t-test-on-two-independent-means.html#post-hoc-analysis"><i class="fa fa-check"></i><b>2.4.1</b> Post-hoc analysis</a></li>
<li class="chapter" data-level="2.4.2" data-path="power-analysis-for-a-t-test-on-two-independent-means.html"><a href="power-analysis-for-a-t-test-on-two-independent-means.html#a-priori-analysis"><i class="fa fa-check"></i><b>2.4.2</b> A priori analysis</a></li>
<li class="chapter" data-level="2.4.3" data-path="power-analysis-for-a-t-test-on-two-independent-means.html"><a href="power-analysis-for-a-t-test-on-two-independent-means.html#sensitivity-analysis---calculate-the-detectable-effect-size"><i class="fa fa-check"></i><b>2.4.3</b> Sensitivity analysis - Calculate the detectable effect size</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="important-points-to-remember.html"><a href="important-points-to-remember.html"><i class="fa fa-check"></i><b>2.5</b> Important points to remember</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="correlation-and-simple-linear-regression.html"><a href="correlation-and-simple-linear-regression.html"><i class="fa fa-check"></i><b>3</b> Correlation and simple linear regression</a>
<ul>
<li class="chapter" data-level="3.1" data-path="set-lm.html"><a href="set-lm.html"><i class="fa fa-check"></i><b>3.1</b> R packages and data</a></li>
<li class="chapter" data-level="3.2" data-path="scatter-plots.html"><a href="scatter-plots.html"><i class="fa fa-check"></i><b>3.2</b> Scatter plots</a></li>
<li class="chapter" data-level="3.3" data-path="data-transformations-and-the-product-moment-correlation.html"><a href="data-transformations-and-the-product-moment-correlation.html"><i class="fa fa-check"></i><b>3.3</b> Data transformations and the product-moment correlation</a></li>
<li class="chapter" data-level="3.4" data-path="testing-the-significance-of-correlations-and-bonferroni-probabilities.html"><a href="testing-the-significance-of-correlations-and-bonferroni-probabilities.html"><i class="fa fa-check"></i><b>3.4</b> Testing the significance of correlations and Bonferroni probabilities</a></li>
<li class="chapter" data-level="3.5" data-path="non-parametric-correlations-spearmans-rank-and-kendalls-tau.html"><a href="non-parametric-correlations-spearmans-rank-and-kendalls-tau.html"><i class="fa fa-check"></i><b>3.5</b> Non-parametric correlations: Spearman’s rank and Kendall’s <span class="math inline">\(\tau\)</span></a></li>
<li class="chapter" data-level="3.6" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html"><i class="fa fa-check"></i><b>3.6</b> Simple linear regression</a>
<ul>
<li class="chapter" data-level="3.6.1" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#testing-regression-assumptions"><i class="fa fa-check"></i><b>3.6.1</b> Testing regression assumptions</a></li>
<li class="chapter" data-level="3.6.2" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#formal-tests-of-regression-assumptions"><i class="fa fa-check"></i><b>3.6.2</b> Formal tests of regression assumptions</a></li>
</ul></li>
<li class="chapter" data-level="3.7" data-path="data-transformations-in-regression.html"><a href="data-transformations-in-regression.html"><i class="fa fa-check"></i><b>3.7</b> Data transformations in regression</a></li>
<li class="chapter" data-level="3.8" data-path="dealing-with-outliers.html"><a href="dealing-with-outliers.html"><i class="fa fa-check"></i><b>3.8</b> Dealing with outliers</a></li>
<li class="chapter" data-level="3.9" data-path="quantifying-effect-size-in-regression-and-power-analysis.html"><a href="quantifying-effect-size-in-regression-and-power-analysis.html"><i class="fa fa-check"></i><b>3.9</b> Quantifying effect size in regression and power analysis</a>
<ul>
<li class="chapter" data-level="3.9.1" data-path="quantifying-effect-size-in-regression-and-power-analysis.html"><a href="quantifying-effect-size-in-regression-and-power-analysis.html#power-to-detect-a-given-slope"><i class="fa fa-check"></i><b>3.9.1</b> Power to detect a given slope</a></li>
<li class="chapter" data-level="3.9.2" data-path="quantifying-effect-size-in-regression-and-power-analysis.html"><a href="quantifying-effect-size-in-regression-and-power-analysis.html#sample-size-required-to-achieve-desired-power"><i class="fa fa-check"></i><b>3.9.2</b> Sample size required to achieve desired power</a></li>
</ul></li>
<li class="chapter" data-level="3.10" data-path="bootstrapping-the-simple-linear-regression.html"><a href="bootstrapping-the-simple-linear-regression.html"><i class="fa fa-check"></i><b>3.10</b> Bootstrapping the simple linear regression</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="two---sample-comparisons.html"><a href="two---sample-comparisons.html"><i class="fa fa-check"></i><b>4</b> Two - sample comparisons</a>
<ul>
<li class="chapter" data-level="4.1" data-path="set-ttest.html"><a href="set-ttest.html"><i class="fa fa-check"></i><b>4.1</b> R packages and data</a></li>
<li class="chapter" data-level="4.2" data-path="visual-examination-of-sample-data.html"><a href="visual-examination-of-sample-data.html"><i class="fa fa-check"></i><b>4.2</b> Visual examination of sample data</a></li>
<li class="chapter" data-level="4.3" data-path="comparing-means-of-two-independent-samples-parametric-and-non-parametric-comparisons.html"><a href="comparing-means-of-two-independent-samples-parametric-and-non-parametric-comparisons.html"><i class="fa fa-check"></i><b>4.3</b> Comparing means of two independent samples: parametric and non-parametric comparisons</a></li>
<li class="chapter" data-level="4.4" data-path="bootstrap-and-permutation-tests-to-compare-2-means.html"><a href="bootstrap-and-permutation-tests-to-compare-2-means.html"><i class="fa fa-check"></i><b>4.4</b> Bootstrap and permutation tests to compare 2 means</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="bootstrap-and-permutation-tests-to-compare-2-means.html"><a href="bootstrap-and-permutation-tests-to-compare-2-means.html#bootstrap"><i class="fa fa-check"></i><b>4.4.1</b> Bootstrap</a></li>
<li class="chapter" data-level="4.4.2" data-path="bootstrap-and-permutation-tests-to-compare-2-means.html"><a href="bootstrap-and-permutation-tests-to-compare-2-means.html#permutation"><i class="fa fa-check"></i><b>4.4.2</b> Permutation</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="comparing-the-means-of-paired-samples.html"><a href="comparing-the-means-of-paired-samples.html"><i class="fa fa-check"></i><b>4.5</b> Comparing the means of paired samples</a></li>
<li class="chapter" data-level="4.6" data-path="bibliography.html"><a href="bibliography.html"><i class="fa fa-check"></i><b>4.6</b> Bibliography</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="one-way-anova.html"><a href="one-way-anova.html"><i class="fa fa-check"></i><b>5</b> One-way ANOVA</a>
<ul>
<li class="chapter" data-level="5.1" data-path="set-ano.html"><a href="set-ano.html"><i class="fa fa-check"></i><b>5.1</b> R packages and data</a></li>
<li class="chapter" data-level="5.2" data-path="one-way-anova-with-multiple-comparisons.html"><a href="one-way-anova-with-multiple-comparisons.html"><i class="fa fa-check"></i><b>5.2</b> One-way ANOVA with multiple comparisons</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="one-way-anova-with-multiple-comparisons.html"><a href="one-way-anova-with-multiple-comparisons.html#visualiser-les-données"><i class="fa fa-check"></i><b>5.2.1</b> Visualiser les données</a></li>
<li class="chapter" data-level="5.2.2" data-path="one-way-anova-with-multiple-comparisons.html"><a href="one-way-anova-with-multiple-comparisons.html#testing-the-assumptions-of-a-parametric-anova"><i class="fa fa-check"></i><b>5.2.2</b> Testing the assumptions of a parametric ANOVA</a></li>
<li class="chapter" data-level="5.2.3" data-path="one-way-anova-with-multiple-comparisons.html"><a href="one-way-anova-with-multiple-comparisons.html#performing-the-anova"><i class="fa fa-check"></i><b>5.2.3</b> Performing the ANOVA</a></li>
<li class="chapter" data-level="5.2.4" data-path="one-way-anova-with-multiple-comparisons.html"><a href="one-way-anova-with-multiple-comparisons.html#performing-multiple-comparisons-of-means-test"><i class="fa fa-check"></i><b>5.2.4</b> Performing multiple comparisons of means test</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="data-transformations-and-non-parametric-anova.html"><a href="data-transformations-and-non-parametric-anova.html"><i class="fa fa-check"></i><b>5.3</b> Data transformations and non-parametric ANOVA</a></li>
<li class="chapter" data-level="5.4" data-path="dealing-with-outliers-1.html"><a href="dealing-with-outliers-1.html"><i class="fa fa-check"></i><b>5.4</b> Dealing with outliers</a></li>
<li class="chapter" data-level="5.5" data-path="permutation-test.html"><a href="permutation-test.html"><i class="fa fa-check"></i><b>5.5</b> Permutation test</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="multiway-anova-factorial-and-nested-designs.html"><a href="multiway-anova-factorial-and-nested-designs.html"><i class="fa fa-check"></i><b>6</b> Multiway ANOVA: factorial and nested designs</a>
<ul>
<li class="chapter" data-level="6.1" data-path="set-anomul.html"><a href="set-anomul.html"><i class="fa fa-check"></i><b>6.1</b> R packages and data needed</a></li>
<li class="chapter" data-level="6.2" data-path="two-way-factorial-design-with-replication.html"><a href="two-way-factorial-design-with-replication.html"><i class="fa fa-check"></i><b>6.2</b> Two-way factorial design with replication</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="two-way-factorial-design-with-replication.html"><a href="two-way-factorial-design-with-replication.html#fixed-effects-anova-model-i"><i class="fa fa-check"></i><b>6.2.1</b> Fixed effects ANOVA (Model I)</a></li>
<li class="chapter" data-level="6.2.2" data-path="two-way-factorial-design-with-replication.html"><a href="two-way-factorial-design-with-replication.html#mixed-effects-anova-model-iii"><i class="fa fa-check"></i><b>6.2.2</b> Mixed effects ANOVA (Model III)</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="way-factorial-anova-without-replication.html"><a href="way-factorial-anova-without-replication.html"><i class="fa fa-check"></i><b>6.3</b> 2-way factorial ANOVA without replication</a></li>
<li class="chapter" data-level="6.4" data-path="nested-designs.html"><a href="nested-designs.html"><i class="fa fa-check"></i><b>6.4</b> Nested designs</a></li>
<li class="chapter" data-level="6.5" data-path="two-way-non-parametric-anova.html"><a href="two-way-non-parametric-anova.html"><i class="fa fa-check"></i><b>6.5</b> Two-way non-parametric ANOVA</a></li>
<li class="chapter" data-level="6.6" data-path="multiple-comparisons.html"><a href="multiple-comparisons.html"><i class="fa fa-check"></i><b>6.6</b> Multiple comparisons</a></li>
<li class="chapter" data-level="6.7" data-path="test-de-permutation-pour-lanova-à-deux-facteurs-de-classification.html"><a href="test-de-permutation-pour-lanova-à-deux-facteurs-de-classification.html"><i class="fa fa-check"></i><b>6.7</b> Test de permutation pour l’ANOVA à deux facteurs de classification</a></li>
<li class="chapter" data-level="6.8" data-path="bootstrap-for-two-way-anova.html"><a href="bootstrap-for-two-way-anova.html"><i class="fa fa-check"></i><b>6.8</b> Bootstrap for two-way ANOVA</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="multiple-regression.html"><a href="multiple-regression.html"><i class="fa fa-check"></i><b>7</b> Multiple regression</a>
<ul>
<li class="chapter" data-level="7.1" data-path="set-reg-mul.html"><a href="set-reg-mul.html"><i class="fa fa-check"></i><b>7.1</b> R packages and data</a></li>
<li class="chapter" data-level="7.2" data-path="points-to-keep-in-mind.html"><a href="points-to-keep-in-mind.html"><i class="fa fa-check"></i><b>7.2</b> Points to keep in mind</a></li>
<li class="chapter" data-level="7.3" data-path="first-look-at-the-data.html"><a href="first-look-at-the-data.html"><i class="fa fa-check"></i><b>7.3</b> First look at the data</a></li>
<li class="chapter" data-level="7.4" data-path="multiple-regression-models-from-scratch.html"><a href="multiple-regression-models-from-scratch.html"><i class="fa fa-check"></i><b>7.4</b> Multiple regression models from scratch</a></li>
<li class="chapter" data-level="7.5" data-path="stepwise-multiple-regression-procedures.html"><a href="stepwise-multiple-regression-procedures.html"><i class="fa fa-check"></i><b>7.5</b> Stepwise multiple regression procedures</a></li>
<li class="chapter" data-level="7.6" data-path="detecting-multicollinearity.html"><a href="detecting-multicollinearity.html"><i class="fa fa-check"></i><b>7.6</b> Detecting multicollinearity</a></li>
<li class="chapter" data-level="7.7" data-path="polynomial-regression.html"><a href="polynomial-regression.html"><i class="fa fa-check"></i><b>7.7</b> Polynomial regression</a></li>
<li class="chapter" data-level="7.8" data-path="checking-assumptions-of-a-multiple-regression-model.html"><a href="checking-assumptions-of-a-multiple-regression-model.html"><i class="fa fa-check"></i><b>7.8</b> Checking assumptions of a multiple regression model</a></li>
<li class="chapter" data-level="7.9" data-path="visualizing-effect-size.html"><a href="visualizing-effect-size.html"><i class="fa fa-check"></i><b>7.9</b> Visualizing effect size</a></li>
<li class="chapter" data-level="7.10" data-path="testing-for-interactions.html"><a href="testing-for-interactions.html"><i class="fa fa-check"></i><b>7.10</b> Testing for interactions</a></li>
<li class="chapter" data-level="7.11" data-path="dredging-and-the-information-theoretical-approach.html"><a href="dredging-and-the-information-theoretical-approach.html"><i class="fa fa-check"></i><b>7.11</b> Dredging and the information theoretical approach</a></li>
<li class="chapter" data-level="7.12" data-path="bootstrapping-multiple-regression.html"><a href="bootstrapping-multiple-regression.html"><i class="fa fa-check"></i><b>7.12</b> Bootstrapping multiple regression</a></li>
<li class="chapter" data-level="7.13" data-path="permutation-test-1.html"><a href="permutation-test-1.html"><i class="fa fa-check"></i><b>7.13</b> Permutation test</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="ancova-and-general-linear-model.html"><a href="ancova-and-general-linear-model.html"><i class="fa fa-check"></i><b>8</b> ANCOVA and general linear model</a>
<ul>
<li class="chapter" data-level="8.1" data-path="set-anco.html"><a href="set-anco.html"><i class="fa fa-check"></i><b>8.1</b> R packages and data</a></li>
<li class="chapter" data-level="8.2" data-path="linear-models.html"><a href="linear-models.html"><i class="fa fa-check"></i><b>8.2</b> Linear models</a></li>
<li class="chapter" data-level="8.3" data-path="ancova.html"><a href="ancova.html"><i class="fa fa-check"></i><b>8.3</b> ANCOVA</a></li>
<li class="chapter" data-level="8.4" data-path="homogeneity-of-slopes.html"><a href="homogeneity-of-slopes.html"><i class="fa fa-check"></i><b>8.4</b> Homogeneity of slopes</a>
<ul>
<li class="chapter" data-level="8.4.1" data-path="homogeneity-of-slopes.html"><a href="homogeneity-of-slopes.html#case-1---size-as-a-function-of-age-equal-slopes-example"><i class="fa fa-check"></i><b>8.4.1</b> Case 1 - Size as a function of age (equal slopes example)</a></li>
<li class="chapter" data-level="8.4.2" data-path="homogeneity-of-slopes.html"><a href="homogeneity-of-slopes.html#case-2---size-as-a-function-of-age-different-slopes-example"><i class="fa fa-check"></i><b>8.4.2</b> Case 2 - Size as a function of age (different slopes example)</a></li>
</ul></li>
<li class="chapter" data-level="8.5" data-path="the-ancova-model.html"><a href="the-ancova-model.html"><i class="fa fa-check"></i><b>8.5</b> The ANCOVA model</a></li>
<li class="chapter" data-level="8.6" data-path="comparing-model-fits.html"><a href="comparing-model-fits.html"><i class="fa fa-check"></i><b>8.6</b> Comparing model fits</a></li>
<li class="chapter" data-level="8.7" data-path="bootstrap-1.html"><a href="bootstrap-1.html"><i class="fa fa-check"></i><b>8.7</b> Bootstrap</a></li>
<li class="chapter" data-level="8.8" data-path="permutation-test-2.html"><a href="permutation-test-2.html"><i class="fa fa-check"></i><b>8.8</b> Permutation test</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="analysis-of-frequency-data-contingency-tables-log-linear-models-and-poisson-regression.html"><a href="analysis-of-frequency-data-contingency-tables-log-linear-models-and-poisson-regression.html"><i class="fa fa-check"></i><b>9</b> Analysis of frequency data: Contingency Tables, Log-Linear Models, and Poisson Regression</a>
<ul>
<li class="chapter" data-level="9.1" data-path="set-freq.html"><a href="set-freq.html"><i class="fa fa-check"></i><b>9.1</b> R packages and data</a></li>
<li class="chapter" data-level="9.2" data-path="organizing-the-data-3-forms.html"><a href="organizing-the-data-3-forms.html"><i class="fa fa-check"></i><b>9.2</b> Organizing the data: 3 forms</a></li>
<li class="chapter" data-level="9.3" data-path="graphs-for-contingency-tables-and-testing-for-independence.html"><a href="graphs-for-contingency-tables-and-testing-for-independence.html"><i class="fa fa-check"></i><b>9.3</b> Graphs for contingency tables and testing for independence</a></li>
<li class="chapter" data-level="9.4" data-path="log-linear-models-as-an-alternative-to-chi-square-test-for-contingency-tables.html"><a href="log-linear-models-as-an-alternative-to-chi-square-test-for-contingency-tables.html"><i class="fa fa-check"></i><b>9.4</b> Log-linear models as an alternative to Chi-square test for contingency tables</a></li>
<li class="chapter" data-level="9.5" data-path="testing-an-external-hypothesis.html"><a href="testing-an-external-hypothesis.html"><i class="fa fa-check"></i><b>9.5</b> Testing an external hypothesis</a></li>
<li class="chapter" data-level="9.6" data-path="poisson-regression-to-analyze-multi-way-tables.html"><a href="poisson-regression-to-analyze-multi-way-tables.html"><i class="fa fa-check"></i><b>9.6</b> Poisson regression to analyze multi-way tables</a></li>
<li class="chapter" data-level="9.7" data-path="ex-glm.html"><a href="ex-glm.html"><i class="fa fa-check"></i><b>9.7</b> Exercice</a></li>
</ul></li>
<li class="appendix"><span><b>Appendix</b></span></li>
<li class="chapter" data-level="A" data-path="software-tools.html"><a href="software-tools.html"><i class="fa fa-check"></i><b>A</b> Software Tools</a>
<ul>
<li class="chapter" data-level="A.1" data-path="r-and-r-packages.html"><a href="r-and-r-packages.html"><i class="fa fa-check"></i><b>A.1</b> R and R packages</a></li>
<li class="chapter" data-level="A.2" data-path="pandoc.html"><a href="pandoc.html"><i class="fa fa-check"></i><b>A.2</b> Pandoc</a></li>
<li class="chapter" data-level="A.3" data-path="latex.html"><a href="latex.html"><i class="fa fa-check"></i><b>A.3</b> LaTeX</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://bookdown.org" target="_blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">BIO4158 Applied biostats with R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="power-analysis-for-a-t-test-on-two-independent-means" class="section level2 hasAnchor" number="2.4">
<h2><span class="header-section-number">2.4</span> Power analysis for a t-test on two independent means<a href="power-analysis-for-a-t-test-on-two-independent-means.html#power-analysis-for-a-t-test-on-two-independent-means" class="anchor-section" aria-label="Anchor link to header"></a></h2>

<div class="rmdimportant">
<p>All the power analysis presented in this chapter can be done using 2 functions
in R.</p>
<ul>
<li><code>pwr.t.test()</code> when the two samples have a similar size</li>
<li><code>pwr.t2n.test()</code> when samples have different numbers of observations</li>
</ul>
</div>
<p>The objective of this lab is to learn to use G*Power and understand how the 4 parameters of power analyses (<span class="math inline">\(\alpha\)</span>, <span class="math inline">\(\beta\)</span>, sample size and effect size) are related to each other. For this, you will only use the standard t-test to compare two independent means. This is the test most used by biologists, you have all used it, and it will serve admirably for this lab. What you will learn today will be applicable to all other power analyses.</p>
<p>Jaynie Stephenson studied the productivity of streams in the Ottawa region. She has measured fish biomass in 36 streams, 18 on the Shield and 18 in the Ottawa Valley. She found that fish biomass was lower in streams from the valley (2.64 <span class="math inline">\(g/m^2\)</span> , standard deviation = 3.28) than from the Shield (3.31 <span class="math inline">\(g/m^2\)</span> , standard deviation = 2.79.).</p>
<p>When she tested the null hypothesis that fish biomass is the same in the two regions by a t-test, she obtained:</p>
<pre><code>Pooled-Variance Two-Sample t-Test
t = -0.5746, df = 34, p-value = 0.5693</code></pre>
<p>She therefore accepted the null hypothesis (since p is much larger than 0.05) and concluded that fish biomass is the same in the two regions.</p>
<div id="post-hoc-analysis" class="section level3 hasAnchor" number="2.4.1">
<h3><span class="header-section-number">2.4.1</span> Post-hoc analysis<a href="power-analysis-for-a-t-test-on-two-independent-means.html#post-hoc-analysis" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Using the observed means and standard deviations, we can use G*Power to calculate the power of the two-tailed t-test for two independent means, using the observed effect size (the difference between the two means, weighted by the standard deviations) for <span class="math inline">\(\alpha\)</span> = 0.05.</p>
<p>Start G*Power.</p>
<ol style="list-style-type: decimal">
<li>In *<strong>Test family</strong> , choose: t tests</li>
<li>For <strong>Statistical test</strong> , choose: Means: Difference between two independent means (two groups)</li>
<li>For <strong>Type of power analysis</strong> , choose: Post hoc: Compute achieved power - given <span class="math inline">\(\alpha\)</span>, sample size, and effect size</li>
<li>At <strong>Input Parameters</strong> ,</li>
</ol>
<ul>
<li>in the box <strong>Tail(s)</strong> , chose: Two,</li>
<li>check that <span class="math inline">\(\alpha\)</span> <strong>err prob</strong> is equal to 0.05</li>
<li>Enter 18 for the <strong>Sample size</strong> of group 1 and of group 2</li>
<li>then, to calculate effect size (d), click on <strong>Determine =&gt;</strong></li>
</ul>
<ol start="5" style="list-style-type: decimal">
<li>In the window that opens,</li>
</ol>
<ul>
<li>select <strong>n1 = n2</strong> , then</li>
<li>enter the two means (<strong>Mean group</strong> 1 et 2)</li>
<li>the two standard deviations(<strong>SD group</strong> 1 et 2)</li>
<li>click on <strong>Calculate</strong> and <strong>transfer to main window</strong></li>
</ul>
<ol start="6" style="list-style-type: decimal">
<li>After you click on the <strong>Calculate button</strong> in the main window, you
should get the following:</li>
</ol>
<div class="figure"><span style="display:block;" id="fig:gpower-1"></span>
<img src="images/gpower_1.png" alt="Post-hoc analysis with estimated effect size" width="100%" />
<p class="caption">
Figure 2.1: Post-hoc analysis with estimated effect size
</p>
</div>
<p>Similar analysis can be done in R. You first need to calculate the effect size <code>d</code> for a t-test comparing 2 means, and then use the <code>pwr.t.test()</code> function from the <code>pwr</code> 📦.
The easiest is to create anew function in R to estimate the effect size <code>d</code>since we are going to reuse it multiple times during the lab.</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="power-analysis-for-a-t-test-on-two-independent-means.html#cb32-1" aria-hidden="true"></a><span class="co"># load package pwr</span></span>
<span id="cb32-2"><a href="power-analysis-for-a-t-test-on-two-independent-means.html#cb32-2" aria-hidden="true"></a><span class="kw">library</span>(pwr)</span>
<span id="cb32-3"><a href="power-analysis-for-a-t-test-on-two-independent-means.html#cb32-3" aria-hidden="true"></a><span class="co"># define d for a 2 sample t-test</span></span>
<span id="cb32-4"><a href="power-analysis-for-a-t-test-on-two-independent-means.html#cb32-4" aria-hidden="true"></a>d &lt;-<span class="st"> </span><span class="cf">function</span>(u1, u2, sd1, sd2) {</span>
<span id="cb32-5"><a href="power-analysis-for-a-t-test-on-two-independent-means.html#cb32-5" aria-hidden="true"></a>  <span class="kw">abs</span>(u1 <span class="op">-</span><span class="st"> </span>u2) <span class="op">/</span><span class="st"> </span><span class="kw">sqrt</span>((sd1<span class="op">^</span><span class="dv">2</span> <span class="op">+</span><span class="st"> </span>sd2<span class="op">^</span><span class="dv">2</span>) <span class="op">/</span><span class="st"> </span><span class="dv">2</span>)</span>
<span id="cb32-6"><a href="power-analysis-for-a-t-test-on-two-independent-means.html#cb32-6" aria-hidden="true"></a>}</span>
<span id="cb32-7"><a href="power-analysis-for-a-t-test-on-two-independent-means.html#cb32-7" aria-hidden="true"></a></span>
<span id="cb32-8"><a href="power-analysis-for-a-t-test-on-two-independent-means.html#cb32-8" aria-hidden="true"></a><span class="co"># power analysis</span></span>
<span id="cb32-9"><a href="power-analysis-for-a-t-test-on-two-independent-means.html#cb32-9" aria-hidden="true"></a><span class="kw">pwr.t.test</span>(</span>
<span id="cb32-10"><a href="power-analysis-for-a-t-test-on-two-independent-means.html#cb32-10" aria-hidden="true"></a>  <span class="dt">n =</span> <span class="dv">18</span>,</span>
<span id="cb32-11"><a href="power-analysis-for-a-t-test-on-two-independent-means.html#cb32-11" aria-hidden="true"></a>  <span class="dt">d =</span> <span class="kw">d</span>(<span class="dt">u1 =</span> <span class="fl">2.64</span>, <span class="dt">sd1 =</span> <span class="fl">3.28</span>, <span class="dt">u2 =</span> <span class="fl">3.31</span>, <span class="dt">sd2 =</span> <span class="fl">2.79</span>),</span>
<span id="cb32-12"><a href="power-analysis-for-a-t-test-on-two-independent-means.html#cb32-12" aria-hidden="true"></a>  <span class="dt">sig.level =</span> <span class="fl">0.05</span>,</span>
<span id="cb32-13"><a href="power-analysis-for-a-t-test-on-two-independent-means.html#cb32-13" aria-hidden="true"></a>  <span class="dt">type =</span> <span class="st">&quot;two.sample&quot;</span>)</span></code></pre></div>
<pre><code>## 
##      Two-sample t test power calculation 
## 
##               n = 18
##               d = 0.220042
##       sig.level = 0.05
##           power = 0.09833902
##     alternative = two.sided
## 
## NOTE: n is number in *each* group</code></pre>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="power-analysis-for-a-t-test-on-two-independent-means.html#cb34-1" aria-hidden="true"></a><span class="co"># plot similar to G*Power</span></span>
<span id="cb34-2"><a href="power-analysis-for-a-t-test-on-two-independent-means.html#cb34-2" aria-hidden="true"></a>x &lt;-<span class="st"> </span><span class="kw">seq</span>(<span class="op">-</span><span class="dv">4</span>, <span class="dv">4</span>, <span class="dt">length =</span> <span class="dv">200</span>)</span>
<span id="cb34-3"><a href="power-analysis-for-a-t-test-on-two-independent-means.html#cb34-3" aria-hidden="true"></a><span class="kw">plot</span>(x, <span class="kw">dnorm</span>(x), <span class="dt">type =</span> <span class="st">&quot;l&quot;</span>, <span class="dt">col =</span> <span class="st">&quot;red&quot;</span>, <span class="dt">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb34-4"><a href="power-analysis-for-a-t-test-on-two-independent-means.html#cb34-4" aria-hidden="true"></a>qc &lt;-<span class="st"> </span><span class="kw">qt</span>(<span class="fl">0.025</span>, <span class="dv">16</span>)</span>
<span id="cb34-5"><a href="power-analysis-for-a-t-test-on-two-independent-means.html#cb34-5" aria-hidden="true"></a><span class="kw">abline</span>(<span class="dt">v =</span> qc, <span class="dt">col =</span> <span class="st">&quot;green&quot;</span>)</span>
<span id="cb34-6"><a href="power-analysis-for-a-t-test-on-two-independent-means.html#cb34-6" aria-hidden="true"></a><span class="kw">abline</span>(<span class="dt">v =</span> <span class="op">-</span>qc, <span class="dt">col =</span> <span class="st">&quot;green&quot;</span>)</span>
<span id="cb34-7"><a href="power-analysis-for-a-t-test-on-two-independent-means.html#cb34-7" aria-hidden="true"></a><span class="kw">lines</span>(x, <span class="kw">dnorm</span>(x, <span class="dt">mean =</span> (<span class="fl">3.31</span> <span class="op">-</span><span class="st"> </span><span class="fl">2.64</span>)), <span class="dt">type =</span> <span class="st">&quot;l&quot;</span>, <span class="dt">col =</span> <span class="st">&quot;blue&quot;</span>, <span class="dt">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb34-8"><a href="power-analysis-for-a-t-test-on-two-independent-means.html#cb34-8" aria-hidden="true"></a></span>
<span id="cb34-9"><a href="power-analysis-for-a-t-test-on-two-independent-means.html#cb34-9" aria-hidden="true"></a><span class="co"># power corresponds to the shaded area</span></span>
<span id="cb34-10"><a href="power-analysis-for-a-t-test-on-two-independent-means.html#cb34-10" aria-hidden="true"></a>y &lt;-<span class="st"> </span><span class="kw">dnorm</span>(x, <span class="dt">mean =</span> (<span class="fl">3.31</span> <span class="op">-</span><span class="st"> </span><span class="fl">2.64</span>))</span>
<span id="cb34-11"><a href="power-analysis-for-a-t-test-on-two-independent-means.html#cb34-11" aria-hidden="true"></a><span class="kw">polygon</span>(</span>
<span id="cb34-12"><a href="power-analysis-for-a-t-test-on-two-independent-means.html#cb34-12" aria-hidden="true"></a>  <span class="kw">c</span>(x[x <span class="op">&lt;=</span><span class="st"> </span><span class="op">-</span>qc], <span class="op">-</span>qc), <span class="kw">c</span>(y[x <span class="op">&lt;=</span><span class="st"> </span><span class="op">-</span>qc], <span class="dv">0</span>),</span>
<span id="cb34-13"><a href="power-analysis-for-a-t-test-on-two-independent-means.html#cb34-13" aria-hidden="true"></a>  <span class="dt">col =</span> <span class="kw">rgb</span>(<span class="dt">red =</span> <span class="dv">0</span>, <span class="dt">green =</span> <span class="fl">0.2</span>, <span class="dt">blue =</span> <span class="dv">1</span>, <span class="dt">alpha =</span> <span class="fl">0.5</span>))</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:r-power"></span>
<img src="Labs_BIO4158_files/figure-html/r-power-1.svg" alt="Post-hoc analysis with estimated effect size in R" width="672" />
<p class="caption">
Figure 2.2: Post-hoc analysis with estimated effect size in R
</p>
</div>
<p>Let’s examine the figure <a href="power-analysis-for-a-t-test-on-two-independent-means.html#fig:gpower-1">2.1</a>.</p>
<ul>
<li>The curve on the left, in red, corresponds to the expected distribution of the t-statistics when <span class="math inline">\(H_0\)</span> is true (<em>i.e.</em> when the two means are equal) given the sample size (18 per region) and the observed standard deviations.</li>
<li>The vertical green lines correspond to the critical values of t for <span class="math inline">\(\alpha = 0.05\)</span> and a total sample size of 36 (2x18).</li>
<li>The shaded pink regions correspond to the rejection zones for <span class="math inline">\(H_0\)</span>. If Jaynie had obtained a <em>t-value</em> outside the interval delimited by the critical values ranging from -2.03224 to 2.03224, she would then have rejected <span class="math inline">\(H_0\)</span> , the null hypothesis of equal means. In fact, she obtained a t-value of -0.5746 and concluded that the biomass is equal in the two regions.</li>
<li>The curve on the right, in blue, corresponds to the expected distribution of the t-statistics if <span class="math inline">\(H_1\)</span> is true (here <span class="math inline">\(H_1\)</span> is that there is a difference in biomass between the two regions equal to <span class="math inline">\(3.33 - 2.64 = 0.69 g/m^2\)</span> , given the observed standard deviations). This distribution is what we should observe if <span class="math inline">\(H_1\)</span> was true and we repeated a large number of times the experiment using random samples of 18 streams in each of the two regions and calculated a t-statistic for each sample. On average, we would obtain a t-statistic of about 0.6.</li>
<li>Note that there is considerable overlap of the two distributions and that a large fraction of the surface under the right curve is within the interval where <span class="math inline">\(H_0\)</span> is accepted between the two vertical green lines at -2.03224 and 2.03224. This proportion, shaded in blue under the distribution on the right is labeled <span class="math inline">\(\beta\)</span> and corresponds to the risk of <em>type II error</em> (accept <span class="math inline">\(H_0\)</span> when <span class="math inline">\(H_1\)</span> is true).</li>
<li>Power is simply <span class="math inline">\(1-\beta\)</span>, and is here 0.098339. Therefore, if the mean biomass differed by <span class="math inline">\(0.69 g/m^2\)</span> between the two regions, Jaynie had only 9.8% chance of being able to detect it as a statistically significant difference at =5% with a sample size of 18 streams in each region.</li>
</ul>
<p><strong>Let’s recapitulate</strong>: The difference in biomass between regions is not statistically significant according to the t-test. It is because the difference is relatively small relative to the precision of the measurements. It is therefore not surprising that that power, i.e. the probability of detecting a statistically significant difference, is small. Therefore, this analysis is not very informative.</p>
<p><strong>Indeed, a post hoc power analysis using the observed effect size is not useful</strong>. It is much more informative to conduct a post hoc power analysis for an effect size that is different from the observed effect size. But what effect size to use? It is the biology of the system under study that will guide you. For example, with respect to fish biomass in streams, one could argue that a two fold change in biomass (say from 2.64 to 5.28 g/m<sup>2</sup> ) has ecologically significant repercussions. We would therefore want to know if Jaynie had a good chance of detecting a difference as large as this before accepting her conclusion that the biomass is the same in the two regions. So, what were the odds that Jaynie could detect a difference of 2.64 g/m<sup>2</sup> between the two regions? G*Power can tell you if you cajole it the right way.</p>

<div class="rmdcode">
Change the mean of group 2 to 5.28, recalculate effect size, and click on Calculate to obtain figure <a href="power-analysis-for-a-t-test-on-two-independent-means.html#fig:gpower-2">2.3</a>.
</div>
<div class="figure"><span style="display:block;" id="fig:gpower-2"></span>
<img src="images/gpower_2.png" alt="Post-hoc analysis using an effect size different from the one estimated" width="100%" />
<p class="caption">
Figure 2.3: Post-hoc analysis using an effect size different from the one estimated
</p>
</div>
<p>Same analysis using R (without all the code for the interesting but not really useful plot)</p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="power-analysis-for-a-t-test-on-two-independent-means.html#cb35-1" aria-hidden="true"></a><span class="kw">pwr.t.test</span>(</span>
<span id="cb35-2"><a href="power-analysis-for-a-t-test-on-two-independent-means.html#cb35-2" aria-hidden="true"></a>  <span class="dt">n =</span> <span class="dv">18</span>,</span>
<span id="cb35-3"><a href="power-analysis-for-a-t-test-on-two-independent-means.html#cb35-3" aria-hidden="true"></a>  <span class="dt">d =</span> <span class="kw">d</span>(<span class="dt">u1 =</span> <span class="fl">2.64</span>, <span class="dt">sd1 =</span> <span class="fl">3.28</span>, <span class="dt">u2 =</span> <span class="fl">5.28</span>, <span class="dt">sd2 =</span> <span class="fl">2.79</span>),</span>
<span id="cb35-4"><a href="power-analysis-for-a-t-test-on-two-independent-means.html#cb35-4" aria-hidden="true"></a>  <span class="dt">sig.level =</span> <span class="fl">0.05</span>,</span>
<span id="cb35-5"><a href="power-analysis-for-a-t-test-on-two-independent-means.html#cb35-5" aria-hidden="true"></a>  <span class="dt">type =</span> <span class="st">&quot;two.sample&quot;</span>)</span></code></pre></div>
<pre><code>## 
##      Two-sample t test power calculation 
## 
##               n = 18
##               d = 0.8670313
##       sig.level = 0.05
##           power = 0.7146763
##     alternative = two.sided
## 
## NOTE: n is number in *each* group</code></pre>
<p>The power is 0.71, therefore Jaynie had a reasonable chance (71%) of detecting a doubling of biomass with 18 streams in each region.</p>
<p>Note that this post hoc power analysis, done for an effect size considered biologically meaningful, is much more informative than the preceeding one done with the observed effect size (which is what too many students do because it is the default of so many power calculation programs). Jaynie did not detect a difference between the two regions. There are two possibilities: 1) there is really no difference between the regions, or 2) the precision of measurements is so low (because the sample size is small and/or there is large variability within a region) that it is very unlikely to be able to detect even large differences. The second power analysis can eliminate this second possibility because Jaynie had 71% chances of detecting a doubling of biomass.</p>
</div>
<div id="a-priori-analysis" class="section level3 hasAnchor" number="2.4.2">
<h3><span class="header-section-number">2.4.2</span> A priori analysis<a href="power-analysis-for-a-t-test-on-two-independent-means.html#a-priori-analysis" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Suppose that a difference in biomass of <span class="math inline">\(3.31-2.64 = 0.67 g/m^2\)</span> can be ecologically significant. The next field season should be planned so that Jaynie would have a good chance of detecting such a difference in fish biomass between regions. How many streams should Jaynie sample in each region to have 80% of detecting such a difference (given the observed variability)?</p>

<div class="rmdcode">
Change the type of power analysis in G*Power to <strong>A priori: Compute sample size - given <span class="math inline">\(\alpha\)</span> , power, and effect size</strong>. Ensure that the values for means and standard deviations are those obtained by Jaynie. Recalculate the effect size metric and enter 0.8 for power and you will obtain (<a href="power-analysis-for-a-t-test-on-two-independent-means.html#fig:gpower-3">2.4</a>.
</div>
<div class="figure"><span style="display:block;" id="fig:gpower-3"></span>
<img src="images/gpower_3.png" alt="A priori analysis" width="100%" />
<p class="caption">
Figure 2.4: A priori analysis
</p>
</div>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="power-analysis-for-a-t-test-on-two-independent-means.html#cb37-1" aria-hidden="true"></a><span class="kw">pwr.t.test</span>(</span>
<span id="cb37-2"><a href="power-analysis-for-a-t-test-on-two-independent-means.html#cb37-2" aria-hidden="true"></a>  <span class="dt">power =</span> <span class="fl">0.8</span>,</span>
<span id="cb37-3"><a href="power-analysis-for-a-t-test-on-two-independent-means.html#cb37-3" aria-hidden="true"></a>  <span class="dt">d =</span> <span class="kw">d</span>(<span class="dt">u1 =</span> <span class="fl">2.64</span>, <span class="dt">sd1 =</span> <span class="fl">3.28</span>, <span class="dt">u2 =</span> <span class="fl">3.31</span>, <span class="dt">sd2 =</span> <span class="fl">2.79</span>),</span>
<span id="cb37-4"><a href="power-analysis-for-a-t-test-on-two-independent-means.html#cb37-4" aria-hidden="true"></a>  <span class="dt">sig.level =</span> <span class="fl">0.05</span>,</span>
<span id="cb37-5"><a href="power-analysis-for-a-t-test-on-two-independent-means.html#cb37-5" aria-hidden="true"></a>  <span class="dt">type =</span> <span class="st">&quot;two.sample&quot;</span>)</span></code></pre></div>
<pre><code>## 
##      Two-sample t test power calculation 
## 
##               n = 325.1723
##               d = 0.220042
##       sig.level = 0.05
##           power = 0.8
##     alternative = two.sided
## 
## NOTE: n is number in *each* group</code></pre>
<p><strong>Ouch!</strong> The required sample would be of 326 streams in each region! It would cost a fortune and require several field teams otherwise only a few dozen streams could be sampled over the summer and it would be very unlikely that such a small difference in biomass could be detected. Sampling fewer streams would probably be in vain and could be considered as a waste of effort and time: why do the work on several dozens of streams if the odds of success are that low?</p>
<p>If we recalculate for a power of 95%, we find that 538 streams would be required from each region. Increasing power means more work!</p>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="power-analysis-for-a-t-test-on-two-independent-means.html#cb39-1" aria-hidden="true"></a><span class="kw">pwr.t.test</span>(</span>
<span id="cb39-2"><a href="power-analysis-for-a-t-test-on-two-independent-means.html#cb39-2" aria-hidden="true"></a>  <span class="dt">power =</span> <span class="fl">0.95</span>,</span>
<span id="cb39-3"><a href="power-analysis-for-a-t-test-on-two-independent-means.html#cb39-3" aria-hidden="true"></a>  <span class="dt">d =</span> <span class="kw">d</span>(<span class="dt">u1 =</span> <span class="fl">2.64</span>, <span class="dt">sd1 =</span> <span class="fl">3.28</span>, <span class="dt">u2 =</span> <span class="fl">3.31</span>, <span class="dt">sd2 =</span> <span class="fl">2.79</span>),</span>
<span id="cb39-4"><a href="power-analysis-for-a-t-test-on-two-independent-means.html#cb39-4" aria-hidden="true"></a>  <span class="dt">sig.level =</span> <span class="fl">0.05</span>,</span>
<span id="cb39-5"><a href="power-analysis-for-a-t-test-on-two-independent-means.html#cb39-5" aria-hidden="true"></a>  <span class="dt">type =</span> <span class="st">&quot;two.sample&quot;</span>)</span></code></pre></div>
<pre><code>## 
##      Two-sample t test power calculation 
## 
##               n = 537.7286
##               d = 0.220042
##       sig.level = 0.05
##           power = 0.95
##     alternative = two.sided
## 
## NOTE: n is number in *each* group</code></pre>
</div>
<div id="sensitivity-analysis---calculate-the-detectable-effect-size" class="section level3 hasAnchor" number="2.4.3">
<h3><span class="header-section-number">2.4.3</span> Sensitivity analysis - Calculate the detectable effect size<a href="power-analysis-for-a-t-test-on-two-independent-means.html#sensitivity-analysis---calculate-the-detectable-effect-size" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Given the observed variability, a sampling effort of 18 streams per region, and with <span class="math inline">\(\alpha\)</span> = 0.05, what effect size could Jaynie detect with 80% probability <span class="math inline">\(\beta=0.2\)</span>)?</p>

<div class="rmdcode">
Change analysis type in G*Power to <strong>Sensitivity: Compute required effect size - given <span class="math inline">\(\alpha\)</span> , power, and sample size</strong> and size is 18 in each region.
</div>
<div class="figure"><span style="display:block;" id="fig:gpower-4"></span>
<img src="images/gpower_4.png" alt="Analyse de sensitivité" width="100%" />
<p class="caption">
Figure 2.5: Analyse de sensitivité
</p>
</div>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="power-analysis-for-a-t-test-on-two-independent-means.html#cb41-1" aria-hidden="true"></a><span class="kw">pwr.t.test</span>(</span>
<span id="cb41-2"><a href="power-analysis-for-a-t-test-on-two-independent-means.html#cb41-2" aria-hidden="true"></a>  <span class="dt">power =</span> <span class="fl">0.8</span>,</span>
<span id="cb41-3"><a href="power-analysis-for-a-t-test-on-two-independent-means.html#cb41-3" aria-hidden="true"></a>  <span class="dt">n =</span> <span class="dv">18</span>,</span>
<span id="cb41-4"><a href="power-analysis-for-a-t-test-on-two-independent-means.html#cb41-4" aria-hidden="true"></a>  <span class="dt">sig.level =</span> <span class="fl">0.05</span>,</span>
<span id="cb41-5"><a href="power-analysis-for-a-t-test-on-two-independent-means.html#cb41-5" aria-hidden="true"></a>  <span class="dt">type =</span> <span class="st">&quot;two.sample&quot;</span>)</span></code></pre></div>
<pre><code>## 
##      Two-sample t test power calculation 
## 
##               n = 18
##               d = 0.9612854
##       sig.level = 0.05
##           power = 0.8
##     alternative = two.sided
## 
## NOTE: n is number in *each* group</code></pre>
<p>The detectable effect size for this sample size, <span class="math inline">\(\alpha = 0.05\)</span> and <span class="math inline">\(\beta = 0.2\)</span> (or power of 80%) is 0.961296.</p>

<div class="rmdcaution">
Attention, this effect size is the metric <code>d</code> and is dependent on sampling variability.
</div>
<p>Here, <code>d</code> is approximately equal to</p>
<p><span class="math display">\[ d = \frac{| \bar{X_1} \bar{X_2} |} {\sqrt{\frac{{s_1}^2 +{s_2}^2}{2}}}\]</span></p>
<p>To convert this d value without units into a value for the detectable difference in biomass between the two regions, you need to multiply <code>d</code> by the denominator of the equation.</p>
<p><span class="math display">\[
| \bar{X_1} - \bar{X_2} | = d * \sqrt{\frac{{s_1}^2 +{s_2}^2}{2}}
\]</span></p>
<p>In R this can be done with the following code</p>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="power-analysis-for-a-t-test-on-two-independent-means.html#cb43-1" aria-hidden="true"></a><span class="kw">pwr.t.test</span>(</span>
<span id="cb43-2"><a href="power-analysis-for-a-t-test-on-two-independent-means.html#cb43-2" aria-hidden="true"></a>  <span class="dt">power =</span> <span class="fl">0.8</span>,</span>
<span id="cb43-3"><a href="power-analysis-for-a-t-test-on-two-independent-means.html#cb43-3" aria-hidden="true"></a>  <span class="dt">n =</span> <span class="dv">18</span>,</span>
<span id="cb43-4"><a href="power-analysis-for-a-t-test-on-two-independent-means.html#cb43-4" aria-hidden="true"></a>  <span class="dt">sig.level =</span> <span class="fl">0.05</span>,</span>
<span id="cb43-5"><a href="power-analysis-for-a-t-test-on-two-independent-means.html#cb43-5" aria-hidden="true"></a>  <span class="dt">type =</span> <span class="st">&quot;two.sample&quot;</span>)<span class="op">$</span>d <span class="op">*</span><span class="st"> </span><span class="kw">sqrt</span>((<span class="fl">3.28</span><span class="op">^</span><span class="dv">2</span> <span class="op">+</span><span class="st"> </span><span class="fl">2.79</span><span class="op">^</span><span class="dv">2</span>) <span class="op">/</span><span class="st"> </span><span class="dv">2</span>)</span></code></pre></div>
<pre><code>## [1] 2.926992</code></pre>
<p>Therefore, with 18 streams per region, <span class="math inline">\(\alpha\)</span> = 0.05 and <span class="math inline">\(\beta\)</span> = 0.2 (so power of 80%), Jaynie could detect a difference of 2.93 g/m<sup>2</sup> between regions, a bit more than a doubling of biomass.</p>
</div>
</div>
<script src="js/solution.js"></script>
            </section>

          </div>
        </div>
      </div>
<a href="how-to-use-gpower.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="important-points-to-remember.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": false,
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/Bio4158-4558-uottawa/lab_manual/edit/main/02-Gpower.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["Labs_BIO4158.pdf", "Labs_BIO4158.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
