<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>8.5 The ANCOVA model | BIO4158 Applied biostats with R</title>
  <meta name="description" content="Laboratory manual for BIO4158 Applied biostatistics" />
  <meta name="generator" content="bookdown 0.24 and GitBook 2.6.7" />

  <meta property="og:title" content="8.5 The ANCOVA model | BIO4158 Applied biostats with R" />
  <meta property="og:type" content="book" />
  
  <meta property="og:image" content="/images/missing.png" />
  <meta property="og:description" content="Laboratory manual for BIO4158 Applied biostatistics" />
  <meta name="github-repo" content="Bio4158-4558-uottawa/lab_manual/" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="8.5 The ANCOVA model | BIO4158 Applied biostats with R" />
  
  <meta name="twitter:description" content="Laboratory manual for BIO4158 Applied biostatistics" />
  <meta name="twitter:image" content="/images/missing.png" />

<meta name="author" content="Julien Martin" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="homogeneity-of-slopes.html"/>
<link rel="next" href="comparing-model-fits.html"/>
<script src="libs/header-attrs-2.11/header-attrs.js"></script>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>
<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="css/style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">BIO4158 Laboratory manual</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Note</a></li>
<li class="chapter" data-level="" data-path="preface.html"><a href="preface.html"><i class="fa fa-check"></i>Preface</a>
<ul>
<li class="chapter" data-level="" data-path="general-points-to-keep-in-mind.html"><a href="general-points-to-keep-in-mind.html"><i class="fa fa-check"></i>General points to keep in mind</a></li>
<li class="chapter" data-level="" data-path="what-is-r-and-why-use-it-in-this-course.html"><a href="what-is-r-and-why-use-it-in-this-course.html"><i class="fa fa-check"></i>What is R and why use it in this course?</a></li>
<li class="chapter" data-level="" data-path="software-installation.html"><a href="software-installation.html"><i class="fa fa-check"></i>Software installation</a>
<ul>
<li class="chapter" data-level="" data-path="software-installation.html"><a href="software-installation.html#r"><i class="fa fa-check"></i>R</a></li>
<li class="chapter" data-level="" data-path="software-installation.html"><a href="software-installation.html#rstudio-or-vs-code"><i class="fa fa-check"></i>Rstudio or VS code</a></li>
<li class="chapter" data-level="" data-path="software-installation.html"><a href="software-installation.html#r-libraries"><i class="fa fa-check"></i>R libraries</a></li>
<li class="chapter" data-level="" data-path="software-installation.html"><a href="software-installation.html#gpower"><i class="fa fa-check"></i>G*Power</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="general-laboratory-instructions.html"><a href="general-laboratory-instructions.html"><i class="fa fa-check"></i>General laboratory instructions</a></li>
<li class="chapter" data-level="" data-path="notes-about-the-manual.html"><a href="notes-about-the-manual.html"><i class="fa fa-check"></i>Notes about the manual</a>
<ul>
<li class="chapter" data-level="" data-path="notes-about-the-manual.html"><a href="notes-about-the-manual.html#resources"><i class="fa fa-check"></i>Resources</a></li>
<li class="chapter" data-level="" data-path="notes-about-the-manual.html"><a href="notes-about-the-manual.html#license"><i class="fa fa-check"></i>License</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="1" data-path="introduction-to-r.html"><a href="introduction-to-r.html"><i class="fa fa-check"></i><b>1</b> Introduction to R</a>
<ul>
<li class="chapter" data-level="1.1" data-path="set-intro.html"><a href="set-intro.html"><i class="fa fa-check"></i><b>1.1</b> Packages and data needed for the lab</a></li>
<li class="chapter" data-level="1.2" data-path="importing-and-exporting-data.html"><a href="importing-and-exporting-data.html"><i class="fa fa-check"></i><b>1.2</b> Importing and exporting data</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="importing-and-exporting-data.html"><a href="importing-and-exporting-data.html#working-directory"><i class="fa fa-check"></i><b>1.2.1</b> Working directory</a></li>
<li class="chapter" data-level="1.2.2" data-path="importing-and-exporting-data.html"><a href="importing-and-exporting-data.html#opening-a-.rdata-file"><i class="fa fa-check"></i><b>1.2.2</b> Opening a <code>.Rdata</code> file</a></li>
<li class="chapter" data-level="1.2.3" data-path="importing-and-exporting-data.html"><a href="importing-and-exporting-data.html#open-a-.csv-file"><i class="fa fa-check"></i><b>1.2.3</b> Open a <code>.csv</code> file</a></li>
<li class="chapter" data-level="1.2.4" data-path="importing-and-exporting-data.html"><a href="importing-and-exporting-data.html#entering-data-in-r"><i class="fa fa-check"></i><b>1.2.4</b> Entering data in R</a></li>
<li class="chapter" data-level="1.2.5" data-path="importing-and-exporting-data.html"><a href="importing-and-exporting-data.html#cleaning-up-correcting-data"><i class="fa fa-check"></i><b>1.2.5</b> Cleaning up / correcting data</a></li>
<li class="chapter" data-level="1.2.6" data-path="importing-and-exporting-data.html"><a href="importing-and-exporting-data.html#exporting-data-from-r"><i class="fa fa-check"></i><b>1.2.6</b> Exporting data from R</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="preliminary-examination-of-data.html"><a href="preliminary-examination-of-data.html"><i class="fa fa-check"></i><b>1.3</b> Preliminary examination of data</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="preliminary-examination-of-data.html"><a href="preliminary-examination-of-data.html#summary-statistics"><i class="fa fa-check"></i><b>1.3.1</b> Summary statistics</a></li>
<li class="chapter" data-level="1.3.2" data-path="preliminary-examination-of-data.html"><a href="preliminary-examination-of-data.html#histogram-empirical-probability-density-boxplot-and-visual-assessment-of-normality"><i class="fa fa-check"></i><b>1.3.2</b> Histogram, empirical probability density, boxplot, and visual assessment of normality</a></li>
<li class="chapter" data-level="1.3.3" data-path="preliminary-examination-of-data.html"><a href="preliminary-examination-of-data.html#scatterplots"><i class="fa fa-check"></i><b>1.3.3</b> Scatterplots</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="creating-data-subsets.html"><a href="creating-data-subsets.html"><i class="fa fa-check"></i><b>1.4</b> Creating data subsets</a></li>
<li class="chapter" data-level="1.5" data-path="data-transformation.html"><a href="data-transformation.html"><i class="fa fa-check"></i><b>1.5</b> Data transformation</a></li>
<li class="chapter" data-level="1.6" data-path="exercice.html"><a href="exercice.html"><i class="fa fa-check"></i><b>1.6</b> Exercice</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="power-analysis-with-r-and-gpower.html"><a href="power-analysis-with-r-and-gpower.html"><i class="fa fa-check"></i><b>2</b> Power Analysis with R and G*Power</a>
<ul>
<li class="chapter" data-level="2.1" data-path="the-theory.html"><a href="the-theory.html"><i class="fa fa-check"></i><b>2.1</b> The theory</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="the-theory.html"><a href="the-theory.html#what-is-power"><i class="fa fa-check"></i><b>2.1.1</b> What is power?</a></li>
<li class="chapter" data-level="2.1.2" data-path="the-theory.html"><a href="the-theory.html#why-do-a-power-analysis"><i class="fa fa-check"></i><b>2.1.2</b> Why do a power analysis?</a></li>
<li class="chapter" data-level="2.1.3" data-path="the-theory.html"><a href="the-theory.html#factors-affecting-power"><i class="fa fa-check"></i><b>2.1.3</b> Factors affecting power</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="what-is-gpower.html"><a href="what-is-gpower.html"><i class="fa fa-check"></i><b>2.2</b> What is G*Power?</a></li>
<li class="chapter" data-level="2.3" data-path="how-to-use-gpower.html"><a href="how-to-use-gpower.html"><i class="fa fa-check"></i><b>2.3</b> How to use G*Power</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="how-to-use-gpower.html"><a href="how-to-use-gpower.html#general-principle"><i class="fa fa-check"></i><b>2.3.1</b> General Principle</a></li>
<li class="chapter" data-level="2.3.2" data-path="how-to-use-gpower.html"><a href="how-to-use-gpower.html#types-of-power-analyses"><i class="fa fa-check"></i><b>2.3.2</b> Types of power analyses</a></li>
<li class="chapter" data-level="2.3.3" data-path="how-to-use-gpower.html"><a href="how-to-use-gpower.html#how-to-calculate-effect-size"><i class="fa fa-check"></i><b>2.3.3</b> How to calculate effect size</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="power-analysis-for-a-t-test-on-two-independent-means.html"><a href="power-analysis-for-a-t-test-on-two-independent-means.html"><i class="fa fa-check"></i><b>2.4</b> Power analysis for a t-test on two independent means</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="power-analysis-for-a-t-test-on-two-independent-means.html"><a href="power-analysis-for-a-t-test-on-two-independent-means.html#post-hoc-analysis"><i class="fa fa-check"></i><b>2.4.1</b> Post-hoc analysis</a></li>
<li class="chapter" data-level="2.4.2" data-path="power-analysis-for-a-t-test-on-two-independent-means.html"><a href="power-analysis-for-a-t-test-on-two-independent-means.html#a-priori-analysis"><i class="fa fa-check"></i><b>2.4.2</b> A priori analysis</a></li>
<li class="chapter" data-level="2.4.3" data-path="power-analysis-for-a-t-test-on-two-independent-means.html"><a href="power-analysis-for-a-t-test-on-two-independent-means.html#sensitivity-analysis---calculate-the-detectable-effect-size"><i class="fa fa-check"></i><b>2.4.3</b> Sensitivity analysis - Calculate the detectable effect size</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="important-points-to-remember.html"><a href="important-points-to-remember.html"><i class="fa fa-check"></i><b>2.5</b> Important points to remember</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="correlation-and-simple-linear-regression.html"><a href="correlation-and-simple-linear-regression.html"><i class="fa fa-check"></i><b>3</b> Correlation and simple linear regression</a>
<ul>
<li class="chapter" data-level="3.1" data-path="set-lm.html"><a href="set-lm.html"><i class="fa fa-check"></i><b>3.1</b> R packages and data</a></li>
<li class="chapter" data-level="3.2" data-path="scatter-plots.html"><a href="scatter-plots.html"><i class="fa fa-check"></i><b>3.2</b> Scatter plots</a></li>
<li class="chapter" data-level="3.3" data-path="data-transformations-and-the-product-moment-correlation.html"><a href="data-transformations-and-the-product-moment-correlation.html"><i class="fa fa-check"></i><b>3.3</b> Data transformations and the product-moment correlation</a></li>
<li class="chapter" data-level="3.4" data-path="testing-the-significance-of-correlations-and-bonferroni-probabilities.html"><a href="testing-the-significance-of-correlations-and-bonferroni-probabilities.html"><i class="fa fa-check"></i><b>3.4</b> Testing the significance of correlations and Bonferroni probabilities</a></li>
<li class="chapter" data-level="3.5" data-path="non-parametric-correlations-spearmans-rank-and-kendalls-tau.html"><a href="non-parametric-correlations-spearmans-rank-and-kendalls-tau.html"><i class="fa fa-check"></i><b>3.5</b> Non-parametric correlations: Spearman’s rank and Kendall’s <span class="math inline">\(\tau\)</span></a></li>
<li class="chapter" data-level="3.6" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html"><i class="fa fa-check"></i><b>3.6</b> Simple linear regression</a>
<ul>
<li class="chapter" data-level="3.6.1" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#testing-regression-assumptions"><i class="fa fa-check"></i><b>3.6.1</b> Testing regression assumptions</a></li>
<li class="chapter" data-level="3.6.2" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#formal-tests-of-regression-assumptions"><i class="fa fa-check"></i><b>3.6.2</b> Formal tests of regression assumptions</a></li>
</ul></li>
<li class="chapter" data-level="3.7" data-path="data-transformations-in-regression.html"><a href="data-transformations-in-regression.html"><i class="fa fa-check"></i><b>3.7</b> Data transformations in regression</a></li>
<li class="chapter" data-level="3.8" data-path="dealing-with-outliers.html"><a href="dealing-with-outliers.html"><i class="fa fa-check"></i><b>3.8</b> Dealing with outliers</a></li>
<li class="chapter" data-level="3.9" data-path="quantifying-effect-size-in-regression-and-power-analysis.html"><a href="quantifying-effect-size-in-regression-and-power-analysis.html"><i class="fa fa-check"></i><b>3.9</b> Quantifying effect size in regression and power analysis</a>
<ul>
<li class="chapter" data-level="3.9.1" data-path="quantifying-effect-size-in-regression-and-power-analysis.html"><a href="quantifying-effect-size-in-regression-and-power-analysis.html#power-to-detect-a-given-slope"><i class="fa fa-check"></i><b>3.9.1</b> Power to detect a given slope</a></li>
<li class="chapter" data-level="3.9.2" data-path="quantifying-effect-size-in-regression-and-power-analysis.html"><a href="quantifying-effect-size-in-regression-and-power-analysis.html#sample-size-required-to-achieve-desired-power"><i class="fa fa-check"></i><b>3.9.2</b> Sample size required to achieve desired power</a></li>
</ul></li>
<li class="chapter" data-level="3.10" data-path="bootstrapping-the-simple-linear-regression.html"><a href="bootstrapping-the-simple-linear-regression.html"><i class="fa fa-check"></i><b>3.10</b> Bootstrapping the simple linear regression</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="two---sample-comparisons.html"><a href="two---sample-comparisons.html"><i class="fa fa-check"></i><b>4</b> Two - sample comparisons</a>
<ul>
<li class="chapter" data-level="4.1" data-path="set-ttest.html"><a href="set-ttest.html"><i class="fa fa-check"></i><b>4.1</b> R packages and data</a></li>
<li class="chapter" data-level="4.2" data-path="visual-examination-of-sample-data.html"><a href="visual-examination-of-sample-data.html"><i class="fa fa-check"></i><b>4.2</b> Visual examination of sample data</a></li>
<li class="chapter" data-level="4.3" data-path="comparing-means-of-two-independent-samples-parametric-and-non-parametric-comparisons.html"><a href="comparing-means-of-two-independent-samples-parametric-and-non-parametric-comparisons.html"><i class="fa fa-check"></i><b>4.3</b> Comparing means of two independent samples: parametric and non-parametric comparisons</a></li>
<li class="chapter" data-level="4.4" data-path="bootstrap-and-permutation-tests-to-compare-2-means.html"><a href="bootstrap-and-permutation-tests-to-compare-2-means.html"><i class="fa fa-check"></i><b>4.4</b> Bootstrap and permutation tests to compare 2 means</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="bootstrap-and-permutation-tests-to-compare-2-means.html"><a href="bootstrap-and-permutation-tests-to-compare-2-means.html#bootstrap"><i class="fa fa-check"></i><b>4.4.1</b> Bootstrap</a></li>
<li class="chapter" data-level="4.4.2" data-path="bootstrap-and-permutation-tests-to-compare-2-means.html"><a href="bootstrap-and-permutation-tests-to-compare-2-means.html#permutation"><i class="fa fa-check"></i><b>4.4.2</b> Permutation</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="comparing-the-means-of-paired-samples.html"><a href="comparing-the-means-of-paired-samples.html"><i class="fa fa-check"></i><b>4.5</b> Comparing the means of paired samples</a></li>
<li class="chapter" data-level="4.6" data-path="références.html"><a href="références.html"><i class="fa fa-check"></i><b>4.6</b> Références</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="one-way-anova.html"><a href="one-way-anova.html"><i class="fa fa-check"></i><b>5</b> One-way ANOVA</a>
<ul>
<li class="chapter" data-level="5.1" data-path="set-ano.html"><a href="set-ano.html"><i class="fa fa-check"></i><b>5.1</b> R packages and data</a></li>
<li class="chapter" data-level="5.2" data-path="one-way-anova-with-multiple-comparisons.html"><a href="one-way-anova-with-multiple-comparisons.html"><i class="fa fa-check"></i><b>5.2</b> One-way ANOVA with multiple comparisons</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="one-way-anova-with-multiple-comparisons.html"><a href="one-way-anova-with-multiple-comparisons.html#visualiser-les-données"><i class="fa fa-check"></i><b>5.2.1</b> Visualiser les données</a></li>
<li class="chapter" data-level="5.2.2" data-path="one-way-anova-with-multiple-comparisons.html"><a href="one-way-anova-with-multiple-comparisons.html#testing-the-assumptions-of-a-parametric-anova"><i class="fa fa-check"></i><b>5.2.2</b> Testing the assumptions of a parametric ANOVA</a></li>
<li class="chapter" data-level="5.2.3" data-path="one-way-anova-with-multiple-comparisons.html"><a href="one-way-anova-with-multiple-comparisons.html#performing-the-anova"><i class="fa fa-check"></i><b>5.2.3</b> Performing the ANOVA</a></li>
<li class="chapter" data-level="5.2.4" data-path="one-way-anova-with-multiple-comparisons.html"><a href="one-way-anova-with-multiple-comparisons.html#performing-multiple-comparisons-of-means-test"><i class="fa fa-check"></i><b>5.2.4</b> Performing multiple comparisons of means test</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="data-transformations-and-non-parametric-anova.html"><a href="data-transformations-and-non-parametric-anova.html"><i class="fa fa-check"></i><b>5.3</b> Data transformations and non-parametric ANOVA</a></li>
<li class="chapter" data-level="5.4" data-path="dealing-with-outliers-1.html"><a href="dealing-with-outliers-1.html"><i class="fa fa-check"></i><b>5.4</b> Dealing with outliers</a></li>
<li class="chapter" data-level="5.5" data-path="permutation-test.html"><a href="permutation-test.html"><i class="fa fa-check"></i><b>5.5</b> Permutation test</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="multiway-anova-factorial-and-nested-designs.html"><a href="multiway-anova-factorial-and-nested-designs.html"><i class="fa fa-check"></i><b>6</b> Multiway ANOVA: factorial and nested designs</a>
<ul>
<li class="chapter" data-level="6.1" data-path="set-anomul.html"><a href="set-anomul.html"><i class="fa fa-check"></i><b>6.1</b> R packages and data needed</a></li>
<li class="chapter" data-level="6.2" data-path="two-way-factorial-design-with-replication.html"><a href="two-way-factorial-design-with-replication.html"><i class="fa fa-check"></i><b>6.2</b> Two-way factorial design with replication</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="two-way-factorial-design-with-replication.html"><a href="two-way-factorial-design-with-replication.html#fixed-effects-anova-model-i"><i class="fa fa-check"></i><b>6.2.1</b> Fixed effects ANOVA (Model I)</a></li>
<li class="chapter" data-level="6.2.2" data-path="two-way-factorial-design-with-replication.html"><a href="two-way-factorial-design-with-replication.html#mixed-effects-anova-model-iii"><i class="fa fa-check"></i><b>6.2.2</b> Mixed effects ANOVA (Model III)</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="way-factorial-anova-without-replication.html"><a href="way-factorial-anova-without-replication.html"><i class="fa fa-check"></i><b>6.3</b> 2-way factorial ANOVA without replication</a></li>
<li class="chapter" data-level="6.4" data-path="nested-designs.html"><a href="nested-designs.html"><i class="fa fa-check"></i><b>6.4</b> Nested designs</a></li>
<li class="chapter" data-level="6.5" data-path="two-way-non-parametric-anova.html"><a href="two-way-non-parametric-anova.html"><i class="fa fa-check"></i><b>6.5</b> Two-way non-parametric ANOVA</a></li>
<li class="chapter" data-level="6.6" data-path="multiple-comparisons.html"><a href="multiple-comparisons.html"><i class="fa fa-check"></i><b>6.6</b> Multiple comparisons</a></li>
<li class="chapter" data-level="6.7" data-path="test-de-permutation-pour-lanova-à-deux-facteurs-de-classification.html"><a href="test-de-permutation-pour-lanova-à-deux-facteurs-de-classification.html"><i class="fa fa-check"></i><b>6.7</b> Test de permutation pour l’ANOVA à deux facteurs de classification</a></li>
<li class="chapter" data-level="6.8" data-path="bootstrap-for-two-way-anova.html"><a href="bootstrap-for-two-way-anova.html"><i class="fa fa-check"></i><b>6.8</b> Bootstrap for two-way ANOVA</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="multiple-regression.html"><a href="multiple-regression.html"><i class="fa fa-check"></i><b>7</b> Multiple regression</a>
<ul>
<li class="chapter" data-level="7.1" data-path="set-reg-mul.html"><a href="set-reg-mul.html"><i class="fa fa-check"></i><b>7.1</b> R packages and data</a></li>
<li class="chapter" data-level="7.2" data-path="points-to-keep-in-mind.html"><a href="points-to-keep-in-mind.html"><i class="fa fa-check"></i><b>7.2</b> Points to keep in mind</a></li>
<li class="chapter" data-level="7.3" data-path="first-look-at-the-data.html"><a href="first-look-at-the-data.html"><i class="fa fa-check"></i><b>7.3</b> First look at the data</a></li>
<li class="chapter" data-level="7.4" data-path="multiple-regression-models-from-scratch.html"><a href="multiple-regression-models-from-scratch.html"><i class="fa fa-check"></i><b>7.4</b> Multiple regression models from scratch</a></li>
<li class="chapter" data-level="7.5" data-path="stepwise-multiple-regression-procedures.html"><a href="stepwise-multiple-regression-procedures.html"><i class="fa fa-check"></i><b>7.5</b> Stepwise multiple regression procedures</a></li>
<li class="chapter" data-level="7.6" data-path="detecting-multicollinearity.html"><a href="detecting-multicollinearity.html"><i class="fa fa-check"></i><b>7.6</b> Detecting multicollinearity</a></li>
<li class="chapter" data-level="7.7" data-path="polynomial-regression.html"><a href="polynomial-regression.html"><i class="fa fa-check"></i><b>7.7</b> Polynomial regression</a></li>
<li class="chapter" data-level="7.8" data-path="checking-assumptions-of-a-multiple-regression-model.html"><a href="checking-assumptions-of-a-multiple-regression-model.html"><i class="fa fa-check"></i><b>7.8</b> Checking assumptions of a multiple regression model</a></li>
<li class="chapter" data-level="7.9" data-path="visualizing-effect-size.html"><a href="visualizing-effect-size.html"><i class="fa fa-check"></i><b>7.9</b> Visualizing effect size</a></li>
<li class="chapter" data-level="7.10" data-path="testing-for-interactions.html"><a href="testing-for-interactions.html"><i class="fa fa-check"></i><b>7.10</b> Testing for interactions</a></li>
<li class="chapter" data-level="7.11" data-path="dredging-and-the-information-theoretical-approach.html"><a href="dredging-and-the-information-theoretical-approach.html"><i class="fa fa-check"></i><b>7.11</b> Dredging and the information theoretical approach</a></li>
<li class="chapter" data-level="7.12" data-path="bootstrapping-multiple-regression.html"><a href="bootstrapping-multiple-regression.html"><i class="fa fa-check"></i><b>7.12</b> Bootstrapping multiple regression</a></li>
<li class="chapter" data-level="7.13" data-path="permutation-test-1.html"><a href="permutation-test-1.html"><i class="fa fa-check"></i><b>7.13</b> Permutation test</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="ancova-et-modèle-linéaire-général.html"><a href="ancova-et-modèle-linéaire-général.html"><i class="fa fa-check"></i><b>8</b> ANCOVA et modèle linéaire général</a>
<ul>
<li class="chapter" data-level="8.1" data-path="set-anco.html"><a href="set-anco.html"><i class="fa fa-check"></i><b>8.1</b> R packages and data</a></li>
<li class="chapter" data-level="8.2" data-path="linear-models.html"><a href="linear-models.html"><i class="fa fa-check"></i><b>8.2</b> Linear models</a></li>
<li class="chapter" data-level="8.3" data-path="ancova.html"><a href="ancova.html"><i class="fa fa-check"></i><b>8.3</b> ANCOVA</a></li>
<li class="chapter" data-level="8.4" data-path="homogeneity-of-slopes.html"><a href="homogeneity-of-slopes.html"><i class="fa fa-check"></i><b>8.4</b> Homogeneity of slopes</a>
<ul>
<li class="chapter" data-level="8.4.1" data-path="homogeneity-of-slopes.html"><a href="homogeneity-of-slopes.html#case-1---size-as-a-function-of-age-equal-slopes-example"><i class="fa fa-check"></i><b>8.4.1</b> Case 1 - Size as a function of age (equal slopes example)</a></li>
<li class="chapter" data-level="8.4.2" data-path="homogeneity-of-slopes.html"><a href="homogeneity-of-slopes.html#case-2---size-as-a-function-of-age-different-slopes-example"><i class="fa fa-check"></i><b>8.4.2</b> Case 2 - Size as a function of age (different slopes example)</a></li>
</ul></li>
<li class="chapter" data-level="8.5" data-path="the-ancova-model.html"><a href="the-ancova-model.html"><i class="fa fa-check"></i><b>8.5</b> The ANCOVA model</a></li>
<li class="chapter" data-level="8.6" data-path="comparing-model-fits.html"><a href="comparing-model-fits.html"><i class="fa fa-check"></i><b>8.6</b> Comparing model fits</a></li>
<li class="chapter" data-level="8.7" data-path="bootstrap-1.html"><a href="bootstrap-1.html"><i class="fa fa-check"></i><b>8.7</b> Bootstrap</a></li>
<li class="chapter" data-level="8.8" data-path="permutation-test-2.html"><a href="permutation-test-2.html"><i class="fa fa-check"></i><b>8.8</b> Permutation test</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="analysis-of-frequency-data-contingency-tables-log-linear-models-and-poisson-regression.html"><a href="analysis-of-frequency-data-contingency-tables-log-linear-models-and-poisson-regression.html"><i class="fa fa-check"></i><b>9</b> Analysis of frequency data: Contingency Tables, Log-Linear Models, and Poisson Regression</a>
<ul>
<li class="chapter" data-level="9.1" data-path="set-freq.html"><a href="set-freq.html"><i class="fa fa-check"></i><b>9.1</b> R packages and data</a></li>
<li class="chapter" data-level="9.2" data-path="organizing-the-data-3-forms.html"><a href="organizing-the-data-3-forms.html"><i class="fa fa-check"></i><b>9.2</b> Organizing the data: 3 forms</a></li>
<li class="chapter" data-level="9.3" data-path="graphs-for-contingency-tables-and-testing-for-independence.html"><a href="graphs-for-contingency-tables-and-testing-for-independence.html"><i class="fa fa-check"></i><b>9.3</b> Graphs for contingency tables and testing for independence</a></li>
<li class="chapter" data-level="9.4" data-path="log-linear-models-as-an-alternative-to-chi-square-test-for-contingency-tables.html"><a href="log-linear-models-as-an-alternative-to-chi-square-test-for-contingency-tables.html"><i class="fa fa-check"></i><b>9.4</b> Log-linear models as an alternative to Chi-square test for contingency tables</a></li>
<li class="chapter" data-level="9.5" data-path="testing-an-external-hypothesis.html"><a href="testing-an-external-hypothesis.html"><i class="fa fa-check"></i><b>9.5</b> Testing an external hypothesis</a></li>
<li class="chapter" data-level="9.6" data-path="poisson-regression-to-analyze-multi-way-tables.html"><a href="poisson-regression-to-analyze-multi-way-tables.html"><i class="fa fa-check"></i><b>9.6</b> Poisson regression to analyze multi-way tables</a></li>
<li class="chapter" data-level="9.7" data-path="ex-glm.html"><a href="ex-glm.html"><i class="fa fa-check"></i><b>9.7</b> Exercice</a></li>
</ul></li>
<li class="appendix"><span><b>Appendix</b></span></li>
<li class="chapter" data-level="A" data-path="software-tools.html"><a href="software-tools.html"><i class="fa fa-check"></i><b>A</b> Software Tools</a>
<ul>
<li class="chapter" data-level="A.1" data-path="r-and-r-packages.html"><a href="r-and-r-packages.html"><i class="fa fa-check"></i><b>A.1</b> R and R packages</a></li>
<li class="chapter" data-level="A.2" data-path="pandoc.html"><a href="pandoc.html"><i class="fa fa-check"></i><b>A.2</b> Pandoc</a></li>
<li class="chapter" data-level="A.3" data-path="latex.html"><a href="latex.html"><i class="fa fa-check"></i><b>A.3</b> LaTeX</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://bookdown.org" target="_blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">BIO4158 Applied biostats with R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="the-ancova-model" class="section level2" number="8.5">
<h2><span class="header-section-number">8.5</span> The ANCOVA model</h2>
<p>If the test for homogeneity of slopes indicates that the two or more slopes are not significantly different, i.e. there is no significant interaction between the categorical and continuous variable, then a single slope parameter can be fit. How about the intercepts? Do they differ among levels of the categorical variable? There are two school of thoughts on how to proceed to test for equality of intercepts when slopes are equal:</p>
<ul>
<li>The old school fits a reduced model, with the categorical and continuous variables, but no interactions (this is the ANCOVA model, <em>sensus stricto</em>) and uses the partitioned sums of squares to test for significance, say with the <code>Anova()</code> function. This approach is the one presented in many statistical textbooks.</li>
<li>Others simply use the full model results, and test significance of each term from the partial sums of squares. This approach has the advantage of being faster as only one model needs to be fitted to make all inferences. However, this approach is less powerful.</li>
</ul>
<p>In most practical cases, it does not matter unless one has very complex models with a large number of terms and higher level interactions and that many of these terms are not significant. My suggestion is that you use the faster approach first, and use the traditional approach only when you accept the null hypothesis for equal intercepts. Why? Since the faster approach is less powerful, if you nevertheless reject H0, then this conclusion will not be changed, only reinforced, by using the traditional approach.</p>
<p>Here I will compare the old school and the other approach. Recall that we want to assess equality of intercepts once we determined that slopes are equal. Test for equality of intercepts when slopes differ (or, if you prefer, when there is a significant interaction) are rarely directly meaningful, are often misinterpreted, and should rarely be conducted.</p>
<p>Going back to <code>anc1dat.csv</code>, comparing the relationships between lfkl and lage among sexes, we obtained the following results for the full model with interactions</p>
<div class="sourceCode" id="cb398"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb398-1"><a href="the-ancova-model.html#cb398-1" aria-hidden="true"></a><span class="kw">Anova</span>(model.full1, <span class="dt">type =</span> <span class="dv">3</span>)</span></code></pre></div>
<pre><code>## Anova Table (Type III tests)
## 
## Response: lfkl
##              Sum Sq Df  F value    Pr(&gt;F)    
## (Intercept) 0.64444  1 794.8182 &lt; 2.2e-16 ***
## sex         0.00041  1   0.5043    0.4795    
## lage        0.07259  1  89.5312 4.588e-15 ***
## sex:lage    0.00027  1   0.3367    0.5632    
## Residuals   0.07135 88                       
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>We already concluded that the slope of the regression for males and females does not differ (the interaction sex:lage is not significant). Note that the p-values associated with sex (0.4795) is not significant either.</p>
<p>For the old-school approach, one would fit a reduced model (the <em>sensus stricto</em> ANCOVA model):</p>
<div class="sourceCode" id="cb400"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb400-1"><a href="the-ancova-model.html#cb400-1" aria-hidden="true"></a>model.ancova &lt;-<span class="st"> </span><span class="kw">lm</span>(lfkl <span class="op">~</span><span class="st"> </span>sex <span class="op">+</span><span class="st"> </span>lage, <span class="dt">data =</span> anc1dat)</span>
<span id="cb400-2"><a href="the-ancova-model.html#cb400-2" aria-hidden="true"></a><span class="kw">Anova</span>(model.ancova, <span class="dt">type =</span> <span class="dv">3</span>)</span></code></pre></div>
<pre><code>## Anova Table (Type III tests)
## 
## Response: lfkl
##              Sum Sq Df   F value Pr(&gt;F)    
## (Intercept) 1.13480  1 1410.1232 &lt;2e-16 ***
## sex         0.00149  1    1.8513 0.1771    
## lage        0.14338  1  178.1627 &lt;2e-16 ***
## Residuals   0.07162 89                     
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode" id="cb402"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb402-1"><a href="the-ancova-model.html#cb402-1" aria-hidden="true"></a><span class="kw">summary</span>(model.ancova)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = lfkl ~ sex + lage, data = anc1dat)
## 
## Residuals:
##       Min        1Q    Median        3Q       Max 
## -0.093992 -0.018457 -0.000876  0.022491  0.081161 
## 
## Coefficients:
##                  Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)      1.225533   0.032636  37.552   &lt;2e-16 ***
## sexMALE         -0.008473   0.006228  -1.361    0.177    
## lage             0.327253   0.024517  13.348   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.02837 on 89 degrees of freedom
## Multiple R-squared:  0.696,  Adjusted R-squared:  0.6892 
## F-statistic: 101.9 on 2 and 89 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>According to this test, sex is not significant and therefore we can conclude that the intercept does not vary significantly between males and females. Note that the p-value is lower this time (0.1771 vs 0.4795), reflecting the higher power of this old-school approach. However, the conclusion remains qualitatively the same: intercepts do not differ.</p>
<p>So we accept the null hypothesis that the intercepts are the same for the two sexes. Running the residual diagnostics, we find no problems with linearity, independence, homogeneity of variances, and normality.</p>

<div class="rmdcode">
You will notice, in the above analysis that the residuals plots flag three data points (cases 19, 49, and 50) as having high residuals. These points are a bit worrisome, and may be having a disproportionate effect on your analysis. Eliminate these “outliers” and re-run the analysis. Now what do you conclude?
</div>
<div class="sourceCode" id="cb404"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb404-1"><a href="the-ancova-model.html#cb404-1" aria-hidden="true"></a>model.ancova.nooutliers &lt;-<span class="st"> </span><span class="kw">lm</span>(lfkl <span class="op">~</span><span class="st"> </span>sex <span class="op">+</span><span class="st"> </span>lage, <span class="dt">data =</span> anc1dat[<span class="kw">c</span>(<span class="op">-</span><span class="dv">49</span>, <span class="dv">-50</span>, <span class="dv">-19</span>),])</span>
<span id="cb404-2"><a href="the-ancova-model.html#cb404-2" aria-hidden="true"></a><span class="kw">Anova</span>(model.ancova.nooutliers, <span class="dt">type =</span> <span class="dv">3</span>)</span></code></pre></div>
<pre><code>## Anova Table (Type III tests)
## 
## Response: lfkl
##              Sum Sq Df   F value  Pr(&gt;F)    
## (Intercept) 1.09160  1 1896.5204 &lt; 2e-16 ***
## sex         0.00232  1    4.0374 0.04764 *  
## lage        0.13992  1  243.0946 &lt; 2e-16 ***
## Residuals   0.04950 86                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode" id="cb406"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb406-1"><a href="the-ancova-model.html#cb406-1" aria-hidden="true"></a><span class="kw">summary</span>(model.ancova.nooutliers)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = lfkl ~ sex + lage, data = anc1dat[c(-49, -50, -19), 
##     ])
## 
## Residuals:
##       Min        1Q    Median        3Q       Max 
## -0.058397 -0.018469 -0.000976  0.020696  0.040288 
## 
## Coefficients:
##                  Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)      1.224000   0.028106  43.549   &lt;2e-16 ***
## sexMALE         -0.010823   0.005386  -2.009   0.0476 *  
## lage             0.328604   0.021076  15.591   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.02399 on 86 degrees of freedom
## Multiple R-squared:  0.7706, Adjusted R-squared:  0.7653 
## F-statistic: 144.4 on 2 and 86 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Well, well. Now we would, according to convention, reject the null hypothesis, and conclude that in fact, the intercepts of the regressions for the two sexes are different! This is a qualitatively different result from that obtained using all the data. Why? There are two possible reasons:</p>
<ol style="list-style-type: decimal">
<li>the “outliers” have significant impacts on the fitted regression lines, so that the intercepts of the lines change depending on whether the “outliers” are included (or not);</li>
<li>the exclusion of the outliers increases the precision, i.e. reduces the standard error of the intercept estimates, and therefore increases the likelihood that the two intercepts will in fact be “statistically” different.</li>
</ol>
<ol style="list-style-type: decimal">
<li>is unlikely, since none of the outliers had high leverage (hence Cook’s distances were not large), so (2) is more likely, and you can verify this by fitting separate regressions for each sex with and without these three outliers. If you do, you will notice that the estimated intercepts for each sex do not change very much, but the standard errors of these intercepts change quite a lot.</li>
</ol>

<div class="rmdcode">
Fit separate regresssions by sex with vs. without the outliers. Pay attention to the intercepts.
</div>
<p>Including all data.</p>
<div class="sourceCode" id="cb408"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb408-1"><a href="the-ancova-model.html#cb408-1" aria-hidden="true"></a><span class="kw">by</span>(</span>
<span id="cb408-2"><a href="the-ancova-model.html#cb408-2" aria-hidden="true"></a>  anc1dat,</span>
<span id="cb408-3"><a href="the-ancova-model.html#cb408-3" aria-hidden="true"></a>  anc1dat[, <span class="st">&quot;sex&quot;</span>],</span>
<span id="cb408-4"><a href="the-ancova-model.html#cb408-4" aria-hidden="true"></a>  <span class="cf">function</span>(x) {</span>
<span id="cb408-5"><a href="the-ancova-model.html#cb408-5" aria-hidden="true"></a>    <span class="kw">summary</span>(<span class="kw">lm</span>(lfkl <span class="op">~</span><span class="st"> </span>lage, <span class="dt">data =</span> x))</span>
<span id="cb408-6"><a href="the-ancova-model.html#cb408-6" aria-hidden="true"></a>  }</span>
<span id="cb408-7"><a href="the-ancova-model.html#cb408-7" aria-hidden="true"></a>)</span></code></pre></div>
<pre><code>## anc1dat[, &quot;sex&quot;]: FEMALE      
## 
## Call:
## lm(formula = lfkl ~ lage, data = x)
## 
## Residuals:
##       Min        1Q    Median        3Q       Max 
## -0.093728 -0.020510 -0.000618  0.024066  0.078844 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  1.24264    0.04660  26.664  &lt; 2e-16 ***
## lage         0.31431    0.03512   8.949 4.16e-12 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.03011 on 52 degrees of freedom
## Multiple R-squared:  0.6063, Adjusted R-squared:  0.5987 
## F-statistic: 80.09 on 1 and 52 DF,  p-value: 4.16e-12
## 
## ------------------------------------------------------------ 
## anc1dat[, &quot;sex&quot;]: MALE        
## 
## Call:
## lm(formula = lfkl ~ lage, data = x)
## 
## Residuals:
##       Min        1Q    Median        3Q       Max 
## -0.046663 -0.014875 -0.004275  0.013489  0.078910 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  1.19730    0.04209   28.45  &lt; 2e-16 ***
## lage         0.34300    0.03337   10.28 2.97e-12 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.02594 on 36 degrees of freedom
## Multiple R-squared:  0.7458, Adjusted R-squared:  0.7388 
## F-statistic: 105.6 on 1 and 36 DF,  p-value: 2.972e-12</code></pre>
<p>Difference in intercept is indeed really small. Now let’s have a look when we exclude outliers.</p>
<div class="sourceCode" id="cb410"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb410-1"><a href="the-ancova-model.html#cb410-1" aria-hidden="true"></a><span class="kw">by</span>(</span>
<span id="cb410-2"><a href="the-ancova-model.html#cb410-2" aria-hidden="true"></a>  anc1dat,</span>
<span id="cb410-3"><a href="the-ancova-model.html#cb410-3" aria-hidden="true"></a>  anc1dat[, <span class="st">&quot;sex&quot;</span>],</span>
<span id="cb410-4"><a href="the-ancova-model.html#cb410-4" aria-hidden="true"></a>  <span class="cf">function</span>(x) {</span>
<span id="cb410-5"><a href="the-ancova-model.html#cb410-5" aria-hidden="true"></a>    <span class="kw">summary</span>(<span class="kw">lm</span>(lfkl <span class="op">~</span><span class="st"> </span>lage, <span class="dt">data =</span> x[<span class="kw">c</span>(<span class="op">-</span><span class="dv">49</span>, <span class="dv">-50</span>, <span class="dv">-19</span>), ]))</span>
<span id="cb410-6"><a href="the-ancova-model.html#cb410-6" aria-hidden="true"></a>  }</span>
<span id="cb410-7"><a href="the-ancova-model.html#cb410-7" aria-hidden="true"></a>)</span></code></pre></div>
<pre><code>## anc1dat[, &quot;sex&quot;]: FEMALE      
## 
## Call:
## lm(formula = lfkl ~ lage, data = x[c(-49, -50, -19), ])
## 
## Residuals:
##       Min        1Q    Median        3Q       Max 
## -0.092746 -0.020176 -0.000078  0.023779  0.079995 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  1.24029    0.04815  25.760  &lt; 2e-16 ***
## lage         0.31533    0.03614   8.724 1.53e-11 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.03021 on 49 degrees of freedom
## Multiple R-squared:  0.6083, Adjusted R-squared:  0.6003 
## F-statistic: 76.11 on 1 and 49 DF,  p-value: 1.526e-11
## 
## ------------------------------------------------------------ 
## anc1dat[, &quot;sex&quot;]: MALE        
## 
## Call:
## lm(formula = lfkl ~ lage, data = x[c(-49, -50, -19), ])
## 
## Residuals:
##       Min        1Q    Median        3Q       Max 
## -0.047429 -0.012818 -0.005274  0.013495  0.077538 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  1.19361    0.04188   28.50  &lt; 2e-16 ***
## lage         0.34662    0.03325   10.42 2.83e-12 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.02574 on 35 degrees of freedom
## Multiple R-squared:  0.7563, Adjusted R-squared:  0.7494 
## F-statistic: 108.6 on 1 and 35 DF,  p-value: 2.835e-12</code></pre>
<p>Differences in intercepts are really small and similar than in previous models but now the precision (i.e. standard error) is much smaller for the models without outliers.</p>

<div class="rmdnote">
It is often the case that by eliminating outliers, new outliers appear. This is simply because the “outlier” designation is usually based on a standardized residual: if you eliminate a couple of outliers, then the residual sums of squares decreases, i.e. the “average” (absolute) residual decreases. Thus, points which were not “far from the average” when the original average residual was comparatively large (i.e. were not “outliers”), may now become so because the average residual has been decreased. Remember also that as you eliminate outliers, N decreases, and the increase in R<sup>2</sup> may be more than compensated for by decreased power. So be wary of eliminating outliers!
</div>
</div>
<script src="js/solution.js"></script>
            </section>

          </div>
        </div>
      </div>
<a href="homogeneity-of-slopes.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="comparing-model-fits.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": false,
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/Bio4158-4558-uottawa/lab_manual/edit/master/08-ancova_glm.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["Labs_BIO4158.pdf", "Labs_BIO4158.epub", "Labs_BIO4158.mobi"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
